import { createHash, randomUUID } from 'node:crypto';
import { Decimal128 } from 'mongodb';
import type { Db } from 'mongodb';
import { Router } from 'express';
import { z } from 'zod';
import { created, fail, ok, paginated, parsePagination } from '../../core/api.js';
import { tenantCollection, tenantFilter, withMongoTransaction } from '../../core/db.js';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';
import type { FinanceAccount, FinanceCategory, FinancePayment, FinanceTransfer } from './types.js';
import type { FinancialEntry } from '../../core/models.js';

const id=z.string().uuid(); const idem=z.string().uuid();
const money=z.string().trim().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/).refine(v=>v!=='0','amount must be greater than zero');
const date=z.string().datetime({offset:true});
const accountSchema=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(120),type:z.enum(['cash','bank','wallet','credit_card']),currency:z.string().trim().regex(/^[A-Z]{3}$/),openingBalance:money.default('0')});
const categorySchema=z.object({code:z.string().trim().min(1).max(40),name:z.string().trim().min(1).max(120),direction:z.enum(['income','expense'])});
const paymentSchema=z.object({entryId:id,accountId:id,amount:money,paidAt:date,method:z.enum(['cash','bank_transfer','pix','card','other']),reference:z.string().trim().max(120).optional()});
const transferSchema=z.object({fromAccountId:id,toAccountId:id,amount:money,transferredAt:date,reference:z.string().trim().max(120).optional()}).refine(v=>v.fromAccountId!==v.toAccountId,'source and destination accounts must differ');
type Actor={id:string;companyId:string;role:Role};
function actor(res:Parameters<typeof requireAuth>[1]):Actor{return res.locals.user as Actor;}
function read(res:Parameters<typeof requireAuth>[1]){return hasPermission(actor(res).role,'finance:read');}
function write(res:Parameters<typeof requireAuth>[1]){return hasPermission(actor(res).role,'finance:write');}
function key(req:Parameters<typeof requireAuth>[0]){const raw=req.get('Idempotency-Key');return raw?idem.parse(raw):undefined;}
function hash(v:unknown){return createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function cents(v:Decimal128){const [w='0',f='']=v.toString().split('.');return BigInt(w)*100n+BigInt((f+'00').slice(0,2));}
function amount(v:bigint){return Decimal128.fromString(`${v/100n}.${(v<0n?-v:v)%100n.toString().padStart(2,'0')}`);}
function safeAccount(v:FinanceAccount){return {...v,openingBalance:v.openingBalance.toString()};}
function safeCategory(v:FinanceCategory){return v;}

export function financeAdvancedRouter(db:Db):Router{
 const r=Router();r.use(requireAuth);
 const accounts=tenantCollection<FinanceAccount>(db,'finance_accounts');
 const categories=tenantCollection<FinanceCategory>(db,'finance_categories');
 const payments=tenantCollection<FinancePayment>(db,'finance_payments');
 const transfers=tenantCollection<FinanceTransfer>(db,'finance_transfers');
 const entries=tenantCollection<FinancialEntry>(db,'financial_entries');
 r.get('/accounts',async(req,res,next)=>{try{if(!read(res)){fail(res,403,'FORBIDDEN');return;}const a=actor(res),p=parsePagination(req.query);const [items,total]=await Promise.all([accounts.find(a.companyId,{active:true}).sort({code:1}).skip(p.offset).limit(p.limit).toArray(),accounts.find(a.companyId,{active:true}).count()]);paginated(res,items.map(safeAccount),total,p);}catch(e){next(e);}});
 r.post('/accounts',async(req,res,next)=>{try{if(!write(res)){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=accountSchema.parse(req.body),k=key(req),h=hash(input);if(k){const prior=await accounts.findOne(a.companyId,{idempotencyKey:k} as never);if(prior){if((prior as FinanceAccount&{idempotencyKey?:string;operationHash?:string}).operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{account:safeAccount(prior)});return;}}const now=new Date();const doc=await withMongoTransaction(db,async()=>{const value=Object.assign({_id:randomUUID(),companyId:a.companyId,code:input.code,name:input.name,type:input.type,currency:input.currency,openingBalance:Decimal128.fromString(input.openingBalance),active:true,createdAt:now,updatedAt:now},{idempotencyKey:k,operationHash:h});await accounts.insertOne(a.companyId,value);await db.collection('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:'finance.account.create',resource:'finance_account',resourceId:value._id,createdAt:now});return value;});created(res,{account:safeAccount(doc)});}catch(e){next(e);}});
 r.get('/categories',async(req,res,next)=>{try{if(!read(res)){fail(res,403,'FORBIDDEN');return;}const a=actor(res),p=parsePagination(req.query);const [items,total]=await Promise.all([categories.find(a.companyId,{active:true}).sort({code:1}).skip(p.offset).limit(p.limit).toArray(),categories.find(a.companyId,{active:true}).count()]);paginated(res,items.map(safeCategory),total,p);}catch(e){next(e);}});
 r.post('/categories',async(req,res,next)=>{try{if(!write(res)){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=categorySchema.parse(req.body),now=new Date(),value:FinanceCategory={_id:randomUUID(),companyId:a.companyId,...input,active:true,createdAt:now,updatedAt:now};await categories.insertOne(a.companyId,value);await db.collection('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:'finance.category.create',resource:'finance_category',resourceId:value._id,createdAt:now});created(res,{category:value});}catch(e){next(e);}});
 r.post('/payments',async(req,res,next)=>{try{if(!write(res)){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=paymentSchema.parse(req.body),k=key(req),h=hash(input);if(k){const prior=await payments.findOne(a.companyId,{idempotencyKey:k} as never);if(prior){const p=prior as FinancePayment&{operationHash?:string};if(p.operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{payment:prior});return;}}const value=await withMongoTransaction(db,async()=>{const entry=await entries.findOne(a.companyId,{_id:input.entryId,status:'open'});if(!entry)throw new Error('ENTRY_NOT_OPEN');const account=await accounts.findOne(a.companyId,{_id:input.accountId,active:true});if(!account)throw new Error('ACCOUNT_NOT_FOUND');const paid=cents(entry.paidAmount??Decimal128.fromString('0'));const requested=cents(Decimal128.fromString(input.amount));if(paid+requested>cents(entry.amount))throw new Error('PAYMENT_EXCEEDS_ENTRY');const now=new Date();const payment=Object.assign({_id:randomUUID(),companyId:a.companyId,entryId:entry._id,accountId:account._id,amount:Decimal128.fromString(input.amount),paidAt:new Date(input.paidAt),method:input.method,reference:input.reference,actorUserId:a.id,createdAt:now},{idempotencyKey:k,operationHash:h});await payments.insertOne(a.companyId,payment);const next=paid+requested;await entries.updateOne(a.companyId,{_id:entry._id,status:'open'},{$set:{paidAmount:Decimal128.fromString(`${next/100n}.${(next%100n).toString().padStart(2,'0')}`),status:next===cents(entry.amount)?'paid':'open',paidAt:next===cents(entry.amount)?new Date(input.paidAt):entry.paidAt,updatedAt:now}});await db.collection('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:'finance.payment.create',resource:'finance_payment',resourceId:payment._id,metadata:{entryId:entry._id,accountId:account._id,amount:input.amount},createdAt:now});return payment;});created(res,{payment:value});}catch(e){if(e instanceof Error){if(e.message==='ENTRY_NOT_OPEN'){fail(res,409,'CONFLICT','Financial entry is not open');return;}if(e.message==='ACCOUNT_NOT_FOUND'){fail(res,404,'NOT_FOUND','Financial account not found');return;}if(e.message==='PAYMENT_EXCEEDS_ENTRY'){fail(res,409,'CONFLICT','Payment exceeds outstanding amount');return;}}next(e);}});
 r.post('/transfers',async(req,res,next)=>{try{if(!write(res)){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=transferSchema.parse(req.body),k=key(req),h=hash(input);if(k){const prior=await transfers.findOne(a.companyId,{idempotencyKey:k} as never);if(prior){const t=prior as FinanceTransfer&{operationHash?:string};if(t.operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{transfer:prior});return;}}const value=await withMongoTransaction(db,async()=>{const [from,to]=await Promise.all([accounts.findOne(a.companyId,{_id:input.fromAccountId,active:true}),accounts.findOne(a.companyId,{_id:input.toAccountId,active:true})]);if(!from||!to)throw new Error('ACCOUNT_NOT_FOUND');if(from.currency!==to.currency)throw new Error('CURRENCY_MISMATCH');const now=new Date();const value=Object.assign({_id:randomUUID(),companyId:a.companyId,fromAccountId:from._id,toAccountId:to._id,amount:Decimal128.fromString(input.amount),transferredAt:new Date(input.transferredAt),reference:input.reference,actorUserId:a.id,createdAt:now},{idempotencyKey:k,operationHash:h});await transfers.insertOne(a.companyId,value);await db.collection('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:'finance.transfer.create',resource:'finance_transfer',resourceId:value._id,metadata:{fromAccountId:from._id,toAccountId:to._id,amount:input.amount},createdAt:now});return value;});created(res,{transfer:value});}catch(e){if(e instanceof Error&&e.message==='ACCOUNT_NOT_FOUND'){fail(res,404,'NOT_FOUND','Finance account not found');return;}if(e instanceof Error&&e.message==='CURRENCY_MISMATCH'){fail(res,409,'CONFLICT','Account currencies must match');return;}next(e);}});
 return r;
}
