import { randomUUID } from 'node:crypto';
import type { Db } from 'mongodb';
import type { ClientSession } from 'mongodb';

const MAX_ATTEMPTS=8,BASE_BACKOFF_MS=1000,POLL_INTERVAL_MS=2000,LEASE_MS=60000;
export type FinanceOutboxEvent={_id:string;companyId:string;type:string;schemaVersion:number;correlationId:string;aggregateType:string;aggregateId:string;payload:Record<string,unknown>;attempts:number;status:'pending'|'processing'|'published'|'dead_letter';availableAt:Date;createdAt:Date;updatedAt:Date;lastError?:string};
type IntegrationEvent={_id:string;sourceEventId:string;companyId:string;type:string;schemaVersion:number;correlationId:string;aggregateType:string;aggregateId:string;payload:Record<string,unknown>;publishedAt:Date;createdAt:Date};
export async function enqueueFinanceEvent(db:Db,session:ClientSession, input:{companyId:string;type:string;aggregateType:string;aggregateId:string;correlationId?:string;payload:Record<string,unknown>}):Promise<void>{const now=new Date();await db.collection<FinanceOutboxEvent>('finance_outbox_events').insertOne({_id:randomUUID(),companyId:input.companyId,type:input.type,schemaVersion:1,correlationId:input.correlationId??input.aggregateId,aggregateType:input.aggregateType,aggregateId:input.aggregateId,payload:input.payload,attempts:0,status:'pending',availableAt:now,createdAt:now,updatedAt:now},{session});}
async function publish(db:Db,event:FinanceOutboxEvent){try{await db.collection<IntegrationEvent>('integration_events').insertOne({_id:randomUUID(),sourceEventId:event._id,companyId:event.companyId,type:event.type,schemaVersion:event.schemaVersion,correlationId:event.correlationId,aggregateType:event.aggregateType,aggregateId:event.aggregateId,payload:event.payload,publishedAt:new Date(),createdAt:event.createdAt});}catch(e){if(e&&typeof e==='object'&&'code' in e&&(e as {code?:unknown}).code===11000)return;throw e;}}
async function processOne(db:Db){const now=new Date(),c=db.collection<FinanceOutboxEvent>('finance_outbox_events'),event=await c.findOneAndUpdate({status:'pending',availableAt:{$lte:now}},{$set:{status:'processing',updatedAt:now},$inc:{attempts:1}},{sort:{availableAt:1,createdAt:1},returnDocument:'after'});if(!event)return false;try{await publish(db,event);await c.updateOne({_id:event._id,status:'processing'},{$set:{status:'published',updatedAt:new Date()},$unset:{lastError:''}});}catch(e){const terminal=event.attempts>=MAX_ATTEMPTS,updated=terminal?{status:'dead_letter' as const,updatedAt:new Date()}:{status:'pending' as const,availableAt:new Date(Date.now()+BASE_BACKOFF_MS*2**Math.min(event.attempts-1,6)),updatedAt:new Date()};await c.updateOne({_id:event._id,status:'processing'},{$set:{...updated,lastError:e instanceof Error?e.message:String(e)}});}return true;}
export async function ensureFinanceOutboxCollections(db:Db){const existing=new Set((await db.listCollections({}, {nameOnly:true}).toArray()).map(x=>x.name));if(!existing.has('finance_outbox_events'))await db.createCollection('finance_outbox_events');if(!existing.has('integration_events'))await db.createCollection('integration_events');await db.collection<FinanceOutboxEvent>('finance_outbox_events').createIndex({companyId:1,status:1,availableAt:1,createdAt:1},{name:'finance_outbox_pending'});await db.collection<FinanceOutboxEvent>('finance_outbox_events').createIndex({companyId:1,createdAt:-1},{name:'finance_outbox_company_created'});await db.collection<IntegrationEvent>('integration_events').createIndex({sourceEventId:1},{unique:true,name:'integration_events_source_unique'});await db.collection<IntegrationEvent>('integration_events').createIndex({companyId:1,createdAt:-1},{name:'integration_events_company_created'});await db.collection<FinanceOutboxEvent>('finance_outbox_events').updateMany({status:'processing',updatedAt:{$lt:new Date(Date.now()-LEASE_MS)}},{$set:{status:'pending',availableAt:new Date(),updatedAt:new Date(),lastError:'Recovered stale processing lease'}});}
export function startFinanceOutboxWorker(db:Db){let stopped=false,running=false;const tick=async()=>{if(stopped||running)return;running=true;try{while(!stopped&&await processOne(db)){} }catch(e){console.error('Finance outbox worker error:',e);}finally{running=false;}};const timer=setInterval(()=>void tick(),POLL_INTERVAL_MS);timer.unref?.();void tick();return()=>{stopped=true;clearInterval(timer);};}
