services:
  - type: web
    name: kz-erp-api
    runtime: docker
    rootDir: apps/api
    plan: free
    healthCheckPath: /health/live
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: ERP
      - key: CORS_ORIGIN
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: CORE_BOOTSTRAP_KEY
        sync: false
      - key: CORE_TENANT_PROVISIONING_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: APP_VERSION
        value: 0.1.3
