import { createHash, randomUUID } from 'node:crypto';
import { Decimal128, MongoServerError } from 'mongodb';
import type { Db, Filter } from 'mongodb';
import { Router } from 'express';
import { created, fail, ok, paginated, parsePagination } from '../../core/api.js';
import { currentMongoSession, tenantCollection, withMongoTransaction } from '../../core/db.js';
import type { Customer, Product, SalesOrder, DocumentLine } from '../../core/models.js';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';

const id = z.string().uuid(); const idem = z.string().uuid();
const money = z.string().trim().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/, 'money must be a decimal string with up to 2 decimal places');
const quantity = z.string().trim().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/, 'quantity must be a decimal string with up to 6 decimal places').refine(v => v !== '0', 'quantity must be greater than zero');
const lineSchema = z.object({ productId: id, quantity, unitPrice: money });
const createSchema = z.object({ number: z.string().trim().min(1).max(80), customerId: id, lines: z.array(lineSchema).min(1).max(500) });
const updateSchema = z.object({ customerId: id.optional(), lines: z.array(lineSchema).min(1).max(500).optional() }).refine(v => v.customerId !== undefined || v.lines !== undefined, 'at least one field is required');
type Actor = { id: string; companyId: string; role: Role };
type Audit = { _id: string; companyId: string; actorUserId: string; action: string; resource: string; resourceId: string; metadata?: Record<string, unknown>; createdAt: Date };
function actor(res: Parameters<typeof requireAuth>[1]): Actor { return res.locals.user as Actor; }
function moneyDecimal(v: string) { return Decimal128.fromString(v); }
function scale(v: string) { const [w = '0', f = ''] = v.split('.'); return BigInt(w) * 100n + BigInt(f.padEnd(2, '0')); }
function moneyString(v: bigint) { const sign = v < 0n ? '-' : ''; const absolute = v < 0n ? -v : v; const w = absolute / 100n, f = (absolute % 100n).toString().padStart(2, '0'); return `${sign}${w}${f === '00' ? '' : `.${f}`}`; }
function lineTotal(q: string, p: string) { const [w = '0', f = ''] = q.split('.'); const qs = BigInt(w) * 1_000_000n + BigInt(f.padEnd(6, '0')); const cents = qs * scale(p); return moneyDecimal(moneyString((cents + 500_000n) / 1_000_000n)); }
function hash(v: unknown) { return createHash('sha256').update(JSON.stringify(v)).digest('hex'); }
function serialize(o: SalesOrder) { return { id: String(o._id), number: o.number, customerId: o.customerId, status: o.status, lines: o.lines.map(l => ({ productId: l.productId, description: l.description, quantity: l.quantity.toString(), unitPrice: l.unitPrice.toString(), total: l.total.toString() })), subtotal: o.subtotal.toString(), total: o.total.toString(), createdAt: o.createdAt, updatedAt: o.updatedAt }; }
function key(req: Parameters<typeof requireAuth>[0]) { const raw = req.get('Idempotency-Key'); return raw ? idem.parse(raw) : undefined; }
function canRead(res: Parameters<typeof requireAuth>[1]) { return hasPermission(actor(res).role, 'sales:read'); }
function canWrite(res: Parameters<typeof requireAuth>[1]) { return hasPermission(actor(res).role, 'sales:write'); }

export function salesRouter(db: Db): Router {
 const router = Router(); router.use(requireAuth); const orders = tenantCollection<SalesOrder>(db, 'sales_orders'); const products = tenantCollection<Product>(db, 'products'); const customers = tenantCollection<Customer>(db, 'customers');
 const audit = (a: Actor, action: string, resourceId: string, metadata?: Record<string, unknown>) => db.collection<Audit>('audit_logs').insertOne({ _id: randomUUID(), companyId: a.companyId, actorUserId: a.id, action, resource: 'sales_order', resourceId, metadata, createdAt: new Date() }, { session: currentMongoSession() });
 async function buildLines(companyId: string, input: z.infer<typeof createSchema>['lines']) { const ids = [...new Set(input.map(l => l.productId))]; const found = await products.find(companyId, { _id: { $in: ids }, active: true }).toArray(); if (found.length !== ids.length) throw new Error('PRODUCT_NOT_FOUND'); const lines: DocumentLine[] = input.map(l => ({ productId: l.productId, description: found.find(p => p._id === l.productId)?.name ?? '', quantity: Decimal128.fromString(l.quantity), unitPrice: moneyDecimal(l.unitPrice), total: lineTotal(l.quantity, l.unitPrice) })); return { lines, subtotal: moneyDecimal(moneyString(lines.reduce((s, l) => s + scale(l.total.toString()), 0n))) }; }
 router.get('/orders', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res), p = parsePagination(req.query), filter: Filter<SalesOrder> = {}; if (typeof req.query.status === 'string') filter.status = z.enum(['draft', 'confirmed', 'cancelled', 'completed']).parse(req.query.status); if (typeof req.query.customerId === 'string') filter.customerId = id.parse(req.query.customerId); const [items, total] = await Promise.all([orders.find(a.companyId, filter).sort({ createdAt: -1 }).skip(p.offset).limit(p.limit).toArray(), orders.find(a.companyId, filter).count()]); paginated(res, items.map(serialize), total, p); } catch (e) { next(e); } });
 router.get('/orders/:id', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res), o = await orders.findOne(a.companyId, { _id: id.parse(req.params.id) }); if (!o) { fail(res, 404, 'NOT_FOUND', 'Order not found'); return; } ok(res, { order: serialize(o) }); } catch (e) { next(e); } });
 router.post('/orders', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res), input = createSchema.parse(req.body), k = key(req), h = hash(input); if (k) { const prior = await orders.findOne(a.companyId, { idempotencyKey: k }); if (prior) { if (prior.operationHash !== h) { fail(res, 409, 'CONFLICT', 'Idempotency-Key was already used for a different operation'); return; } created(res, { order: serialize(prior) }); return; } } const result = await withMongoTransaction(db, async () => { if (!(await customers.findOne(a.companyId, { _id: input.customerId, active: true }))) throw new Error('CUSTOMER_NOT_FOUND'); const built = await buildLines(a.companyId, input.lines); const now = new Date(); const order: SalesOrder = { _id: randomUUID(), companyId: a.companyId, number: input.number, customerId: input.customerId, status: 'draft', lines: built.lines, subtotal: built.subtotal, total: built.subtotal, idempotencyKey: k, operationHash: h, createdAt: now, updatedAt: now }; await orders.insertOne(a.companyId, order); await audit(a, 'sales.order.create', order._id!, { number: order.number, total: order.total.toString() }); return order; }); created(res, { order: serialize(result) }); } catch (e) { if (e instanceof Error && e.message === 'PRODUCT_NOT_FOUND') { fail(res, 400, 'VALIDATION_ERROR', 'One or more products are invalid'); return; } if (e instanceof Error && e.message === 'CUSTOMER_NOT_FOUND') { fail(res, 404, 'NOT_FOUND', 'Customer not found'); return; } if (e instanceof MongoServerError && e.code === 11000 && req.get('Idempotency-Key')) { try { const k = idem.parse(req.get('Idempotency-Key')!); const prior = await orders.findOne(actor(res).companyId, { idempotencyKey: k }); if (prior && prior.operationHash === hash(createSchema.parse(req.body))) { created(res, { order: serialize(prior) }); return; } } catch { /* handled below */ } } next(e); } });
 router.patch('/orders/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res), oid = id.parse(req.params.id), input = updateSchema.parse(req.body); const result = await withMongoTransaction(db, async () => { const current = await orders.findOne(a.companyId, { _id: oid }); if (!current) throw new Error('ORDER_NOT_FOUND'); if (current.status !== 'draft') throw new Error('ORDER_NOT_DRAFT'); if (input.customerId && !(await customers.findOne(a.companyId, { _id: input.customerId, active: true }))) throw new Error('CUSTOMER_NOT_FOUND'); let lines = current.lines, subtotal = current.subtotal; if (input.lines) ({ lines, subtotal } = await buildLines(a.companyId, input.lines)); const r = await orders.updateOne(a.companyId, { _id: oid, status: 'draft' }, { $set: { customerId: input.customerId ?? current.customerId, lines, subtotal, total: subtotal, updatedAt: new Date() } }); if (!r.matchedCount) throw new Error('ORDER_NOT_DRAFT'); const updated = await orders.findOne(a.companyId, { _id: oid }); if (!updated) throw new Error('ORDER_DISAPPEARED'); await audit(a, 'sales.order.update', oid); return updated; }); ok(res, { order: serialize(result) }); } catch (e) { if (e instanceof Error && e.message === 'ORDER_NOT_FOUND') { fail(res, 404, 'NOT_FOUND', 'Order not found'); return; } if (e instanceof Error && e.message === 'ORDER_NOT_DRAFT') { fail(res, 409, 'CONFLICT', 'Only draft orders can be edited'); return; } if (e instanceof Error && e.message === 'CUSTOMER_NOT_FOUND') { fail(res, 404, 'NOT_FOUND', 'Customer not found'); return; } if (e instanceof Error && e.message === 'PRODUCT_NOT_FOUND') { fail(res, 400, 'VALIDATION_ERROR', 'One or more products are invalid'); return; } next(e); } });
 async function transition(req: Parameters<typeof requireAuth>[0], res: Parameters<typeof requireAuth>[1], next: Parameters<typeof requireAuth>[2], action: 'confirm' | 'cancel') { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res), oid = id.parse(req.params.id); const result = await withMongoTransaction(db, async () => { const filter: Filter<SalesOrder> = action === 'confirm' ? { _id: oid, status: 'draft' } : { _id: oid, status: { $in: ['draft', 'confirmed'] } }; const status = action === 'confirm' ? 'confirmed' : 'cancelled'; const r = await orders.updateOne(a.companyId, filter, { $set: { status, updatedAt: new Date() } }); if (!r.matchedCount) { const current = await orders.findOne(a.companyId, { _id: oid }); if (!current) throw new Error('ORDER_NOT_FOUND'); throw new Error('INVALID_TRANSITION'); } const updated = await orders.findOne(a.companyId, { _id: oid }); if (!updated) throw new Error('ORDER_DISAPPEARED'); await audit(a, `sales.order.${action}`, oid); return updated; }); ok(res, { order: serialize(result) }); } catch (e) { if (e instanceof Error && e.message === 'ORDER_NOT_FOUND') { fail(res, 404, 'NOT_FOUND', 'Order not found'); return; } if (e instanceof Error && e.message === 'INVALID_TRANSITION') { fail(res, 409, 'CONFLICT', action === 'confirm' ? 'Only draft orders can be confirmed' : 'Order cannot be cancelled in its current state'); return; } next(e); } }
 router.post('/orders/:id/confirm', (req, res, next) => void transition(req, res, next, 'confirm')); router.post('/orders/:id/cancel', (req, res, next) => void transition(req, res, next, 'cancel'));
 return router;
}
