import { randomUUID } from 'node:crypto';
import type { Db } from 'mongodb';
import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';
import { tenantCollection } from '../../core/db.js';
import { fail, ok } from '../../core/api.js';
type Doc={_id:string;companyId:string;createdAt:Date;updatedAt:Date;[key:string]:unknown}; type Audit={_id:string;companyId:string;actorUserId:string;action:string;resource:string;resourceId:string;metadata?:Record<string,unknown>;createdAt:Date};
const id=z.string().uuid();
const entitySchema=z.object({products:z.object({sku:z.string().min(1).max(80),name:z.string().min(1).max(160),description:z.string().max(2000).optional(),unit:z.string().min(1).max(20),price:z.union([z.string(),z.number().finite().min(0)]),active:z.boolean().default(true)}),parties:z.object({code:z.string().min(1).max(80),kind:z.enum(['person','company']),roles:z.array(z.string()).min(1).max(5),name:z.string().min(1).max(160),legalName:z.string().max(200).optional(),document:z.string().max(40).optional(),email:z.string().email().max(320).optional(),phone:z.string().max(40).optional(),active:z.boolean().default(true)}),addresses:z.object({partyId:id,code:z.string().min(1).max(80),type:z.string().min(1).max(40),postalCode:z.string().min(3).max(20),street:z.string().min(1).max(160),number:z.string().min(1).max(30),district:z.string().min(1).max(120),city:z.string().min(1).max(120),state:z.string().min(1).max(120),country:z.string().min(2).max(80).default('BR'),active:z.boolean().default(true)}),units:z.object({code:z.string().min(1).max(20),name:z.string().min(1).max(80),symbol:z.string().min(1).max(12),kind:z.string().min(1).max(30),decimalPlaces:z.number().int().min(0).max(6).default(0),active:z.boolean().default(true)}),price_lists:z.object({code:z.string().min(1).max(40),name:z.string().min(1).max(120),currency:z.string().regex(/^[A-Z]{3}$/),active:z.boolean().default(true)}),prices:z.object({priceListId:id,productId:id,amount:z.union([z.string(),z.number().finite().min(0)]),minQuantity:z.number().int().positive().default(1),active:z.boolean().default(true)}),warehouses:z.object({code:z.string().min(1).max(80),name:z.string().min(1).max(160),active:z.boolean().default(true)})});
function actor(res:{locals:{user?:unknown}}){return res.locals.user as {id:string;companyId:string;role:Role}}
export function f2IoRouter(db:Db):Router{const r=Router();r.use(requireAuth);const names=['products','parties','addresses','units','price_lists','prices','warehouses'] as const;const collections:any={};for(const n of names)collections[n]=tenantCollection<Doc>(db,n);
r.get('/bulk/export/:entity',async(req,res,next)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:read'))return fail(res,403,'FORBIDDEN');if(!names.includes(req.params.entity as never))return fail(res,404,'NOT_FOUND','Unsupported master-data entity');const docs=await collections[req.params.entity].find(a.companyId,{}).sort({createdAt:1}).toArray();ok(res,{entity:req.params.entity,count:docs.length,records:docs.map(({companyId,...d}:Doc)=>d)})}catch(e){next(e)}});
r.post('/bulk/import/:entity',async(req,res,next)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:write'))return fail(res,403,'FORBIDDEN');if(!names.includes(req.params.entity as never))return fail(res,404,'NOT_FOUND','Unsupported master-data entity');if(!Array.isArray(req.body))return fail(res,400,'VALIDATION_ERROR','Import body must be an array');if(req.body.length>1000)return fail(res,413,'VALIDATION_ERROR','Maximum 1000 records per import');const schema=(entitySchema.shape as any)[req.params.entity];const c=collections[req.params.entity];let inserted=0,failed=0;const errors:any[]=[];for(let i=0;i<req.body.length;i++){try{const input=schema.parse(req.body[i]),now=new Date(),d:any={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};await c.insertOne(a.companyId,d);inserted++}catch(e){failed++;errors.push({index:i,error:e instanceof Error?e.message:String(e)})}}await db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:`master-data.${req.params.entity}.bulk-import`,resource:req.params.entity,resourceId:randomUUID(),metadata:{inserted,failed},createdAt:new Date()});ok(res,{entity:req.params.entity,inserted,failed,errors})}catch(e){next(e)}});return r}
