import { randomUUID } from 'node:crypto';
import type { Db } from 'mongodb';
import { GridFSBucket } from 'mongodb';
import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';
import { tenantCollection } from '../../core/db.js';
import { fail, noContent, ok } from '../../core/api.js';
import { validateF2ImportReferences, validateF2Reference } from './f2-hardening.js';

type Doc={_id:string;companyId:string;createdAt:Date;updatedAt:Date;[key:string]:unknown};
type Audit={_id:string;companyId:string;actorUserId:string;action:string;resource:string;resourceId:string;metadata?:Record<string,unknown>;createdAt:Date;updatedAt:Date};
type Actor={id:string;companyId:string;role:Role};
const id=z.string().uuid();const MAX_ATTACHMENT_BYTES=50_000_000;
const base=z.object({code:z.string().trim().min(1).max(80),name:z.string().trim().min(1).max(160),description:z.string().trim().max(2000).optional(),active:z.boolean().default(true)});
const entitySchema:any={products:z.object({sku:z.string().min(1).max(80),name:z.string().min(1).max(160),description:z.string().max(2000).optional(),unit:z.string().min(1).max(20),price:z.union([z.string(),z.number().finite().min(0)]),active:z.boolean().default(true)}),parties:z.object({code:z.string().min(1).max(80),kind:z.enum(['person','company']),roles:z.array(z.string()).min(1).max(5),name:z.string().min(1).max(160),legalName:z.string().max(200).optional(),document:z.string().max(40).optional(),email:z.string().email().max(320).optional(),phone:z.string().max(40).optional(),active:z.boolean().default(true)}),addresses:z.object({partyId:id,code:z.string().min(1).max(80),type:z.string().min(1).max(40),postalCode:z.string().min(3).max(20),street:z.string().min(1).max(160),number:z.string().min(1).max(30),district:z.string().min(1).max(120),city:z.string().min(1).max(120),state:z.string().min(1).max(120),country:z.string().min(2).max(80).default('BR'),active:z.boolean().default(true)}),units:z.object({code:z.string().min(1).max(20),name:z.string().min(1).max(80),symbol:z.string().min(1).max(12),kind:z.string().min(1).max(30),decimalPlaces:z.number().int().min(0).max(6).default(0),active:z.boolean().default(true)}),price_lists:z.object({code:z.string().min(1).max(40),name:z.string().min(1).max(120),currency:z.string().regex(/^[A-Z]{3}$/),active:z.boolean().default(true)}),prices:z.object({priceListId:id,productId:id,amount:z.union([z.string(),z.number().finite().min(0)]),minQuantity:z.number().int().positive().default(1),active:z.boolean().default(true)}),warehouses:z.object({code:z.string().min(1).max(80),name:z.string().min(1).max(160),active:z.boolean().default(true)}),categories:base.extend({parentId:id.optional()}),brands:base,contacts:z.object({partyId:id,name:z.string().trim().min(1).max(160),role:z.string().trim().max(80).optional(),email:z.string().email().max(320).optional(),phone:z.string().trim().max(40).optional(),mobile:z.string().trim().max(40).optional(),active:z.boolean().default(true)}),locations:base.extend({warehouseId:id,parentId:id.optional(),kind:z.enum(['zone','aisle','rack','shelf','bin']),capacity:z.number().finite().nonnegative().max(1e12).optional()}),classifications:base.extend({type:z.string().trim().min(1).max(80),parentId:id.optional()}),attachments:z.object({entityType:z.string().trim().min(1).max(80),entityId:id,fileName:z.string().trim().min(1).max(255),mimeType:z.string().trim().min(1).max(160),size:z.number().int().nonnegative().max(MAX_ATTACHMENT_BYTES),storageKey:z.string().trim().min(1).max(500),checksum:z.string().trim().max(128).optional(),metadata:z.record(z.string(),z.unknown()).optional()}),relationships:z.object({sourceType:z.string().trim().min(1).max(80),sourceId:id,relation:z.string().trim().min(1).max(80),targetType:z.string().trim().min(1).max(80),targetId:id,metadata:z.record(z.string(),z.unknown()).optional()})};
function actor(res:{locals:{user?:unknown}}):Actor{return res.locals.user as Actor}function header(req:Request,name:string){const value=req.header(name);return value?.trim()||undefined}
export function f2IoRouter(db:Db):Router{const r=Router();r.use(requireAuth);const names=['products','parties','addresses','units','price_lists','prices','warehouses','categories','brands','contacts','locations','classifications','attachments','relationships'] as const;const physical:Record<string,string>={products:'products',parties:'parties',addresses:'addresses',units:'units',price_lists:'price_lists',prices:'prices',warehouses:'warehouses',categories:'product_categories',brands:'product_brands',contacts:'party_contacts',locations:'warehouse_locations',classifications:'classifications',attachments:'master_attachments',relationships:'master_relationships'};const collections:any={};for(const n of names)collections[n]=tenantCollection<Doc>(db,physical[n]);const bucket=new GridFSBucket(db,{bucketName:'f2_attachments'});const attachments=collections.attachments;
  r.post('/attachments/upload',async(req:Request,res:Response,next:NextFunction)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:write'))return fail(res,403,'FORBIDDEN');const entityType=header(req,'x-f2-entity-type'),entityId=header(req,'x-f2-entity-id'),fileName=header(req,'x-f2-file-name'),mimeType=header(req,'x-f2-mime-type')??'application/octet-stream';const size=Number(req.header('content-length')??0);if(!entityType||!entityId||!fileName)return fail(res,400,'VALIDATION_ERROR','x-f2-entity-type, x-f2-entity-id and x-f2-file-name are required');if(!Number.isInteger(size)||size<1||size>MAX_ATTACHMENT_BYTES)return fail(res,413,'VALIDATION_ERROR','Attachment size must be between 1 byte and 50 MB');const referenceError=await validateF2Reference(db,a.companyId,entityType,entityId,'Attachment target');if(referenceError)return fail(res,422,'VALIDATION_ERROR',referenceError);const attachmentId=randomUUID(),storageKey=`f2_attachments/${a.companyId}/${attachmentId}`,upload=bucket.openUploadStreamWithId(attachmentId as any,fileName,{metadata:{companyId:a.companyId,entityType,entityId,mimeType}});let received=0,aborted=false;req.on('data',(chunk:Buffer)=>{received+=chunk.length;if(received>MAX_ATTACHMENT_BYTES&&!aborted){aborted=true;req.destroy(new Error('Attachment exceeds 50 MB'));}});upload.on('error',next);upload.on('finish',async()=>{if(aborted||received!==size){try{await bucket.delete(attachmentId as any)}catch{}if(!res.headersSent)return fail(res,400,'VALIDATION_ERROR','Attachment byte count does not match Content-Length');return;}try{const now=new Date(),doc:Doc={_id:attachmentId,companyId:a.companyId,entityType,entityId,fileName,mimeType,size,storageKey,storageManaged:true,createdAt:now,updatedAt:now};await attachments.insertOne(a.companyId,doc);await db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:'master-data.attachment.upload',resource:'attachment',resourceId:attachmentId,metadata:{size,entityType,entityId},createdAt:now,updatedAt:now});ok(res,{attachment:{id:attachmentId,entityType,entityId,fileName,mimeType,size,storageKey,createdAt:now,updatedAt:now}})}catch(error){try{await bucket.delete(attachmentId as any)}catch{}next(error)}});req.pipe(upload)}catch(e){next(e)}});
  r.get('/attachments/:id/download',async(req,res,next)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:read'))return fail(res,403,'FORBIDDEN');const attachmentId=String(req.params.id),doc=await attachments.findOne(a.companyId,{_id:attachmentId});if(!doc)return fail(res,404,'NOT_FOUND');res.setHeader('Content-Type',String(doc.mimeType));res.setHeader('Content-Length',String(doc.size));res.setHeader('Content-Disposition',`attachment; filename="${String(doc.fileName).replace(/["\\\r\n]/g,'_')}"`);const stream=bucket.openDownloadStream(attachmentId as any);stream.on('error',next);stream.pipe(res)}catch(e){next(e)}});
  r.delete('/attachments/:id/file',async(req,res,next)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:write'))return fail(res,403,'FORBIDDEN');const attachmentId=String(req.params.id),doc=await attachments.findOne(a.companyId,{_id:attachmentId});if(!doc)return fail(res,404,'NOT_FOUND');await bucket.delete(attachmentId as any).catch(()=>undefined);await attachments.deleteOne(a.companyId,{_id:attachmentId});await db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:'master-data.attachment.delete-file',resource:'attachment',resourceId:attachmentId,createdAt:new Date(),updatedAt:new Date()});noContent(res)}catch(e){next(e)}});
  r.get('/bulk/export/:entity',async(req,res,next)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:read'))return fail(res,403,'FORBIDDEN');const entity=String(req.params.entity);if(!names.includes(entity as any))return fail(res,404,'NOT_FOUND','Unsupported master-data entity');const docs=await collections[entity].find(a.companyId,{}).sort({createdAt:1}).toArray();await db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:`master-data.${entity}.bulk-export`,resource:entity,resourceId:randomUUID(),metadata:{count:docs.length},createdAt:new Date(),updatedAt:new Date()});ok(res,{entity,count:docs.length,records:docs.map(({companyId,...d}:Doc)=>d)})}catch(e){next(e)}});
  r.post('/bulk/import/:entity',async(req,res,next)=>{try{const a=actor(res);if(!hasPermission(a.role,'master-data:write'))return fail(res,403,'FORBIDDEN');const entity=String(req.params.entity);if(!names.includes(entity as any))return fail(res,404,'NOT_FOUND','Unsupported master-data entity');if(!Array.isArray(req.body))return fail(res,400,'VALIDATION_ERROR','Import body must be an array');if(req.body.length>1000)return fail(res,413,'VALIDATION_ERROR','Maximum 1000 records per import');const schema=entitySchema[entity];const c=collections[entity];let inserted=0,failed=0;const errors:any[]=[];for(let i=0;i<req.body.length;i++){try{const input=schema.parse(req.body[i]);const ref=await validateF2ImportReferences(db,a.companyId,entity,input);if(ref)throw new Error(ref);const now=new Date(),d:any={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};if(entity==='locations'){const warehouse=await validateF2Reference(db,a.companyId,'warehouse',String(input.warehouseId),'Warehouse');if(warehouse)throw new Error(warehouse)}await c.insertOne(a.companyId,d);inserted++}catch(e){failed++;errors.push({index:i,error:e instanceof Error?e.message:String(e)})}}await db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action:`master-data.${entity}.bulk-import`,resource:entity,resourceId:randomUUID(),metadata:{inserted,failed},createdAt:new Date(),updatedAt:new Date()});ok(res,{entity,inserted,failed,errors})}catch(e){next(e)}});return r}
