import type { Db, Document, InsertOneResult } from 'mongodb';
import { Decimal128 } from 'mongodb';
import { randomUUID } from 'node:crypto';
import type { ZodType } from 'zod';
import { F2_ENTITY_COLLECTIONS, f2EntityCollection, validateF2Reference, validLocationParentKind } from './f2-hardening.js';
export type F2ImportResult={inserted:number;failed:number;errors:Array<{index:number;error:string}>};
type ImportRecord=Record<string,unknown>&{id?:string};type TenantCollection<T extends Document&{companyId:string}>={findOne:(companyId:string,filter?:Record<string,unknown>)=>Promise<T|null>;find:(companyId:string,filter?:Record<string,unknown>)=>{toArray:()=>Promise<T[]>};insertOne:(companyId:string,document:Omit<T,'companyId'>&Partial<Pick<T,'companyId'>>)=>Promise<InsertOneResult<T>>;deleteOne:(companyId:string,filter:Record<string,unknown>)=>Promise<unknown>};
type ImportOptions={db:Db;companyId:string;entity:string;records:unknown[];schema:ZodType;collection:TenantCollection<ImportDocument>};type ImportDocument=Document&{_id:string;companyId:string;createdAt:Date;updatedAt:Date;[key:string]:unknown};
const ENTITY_TYPE:Record<string,string>={products:'product',parties:'party',addresses:'address',units:'unit',price_lists:'price_list',prices:'price',warehouses:'warehouse',categories:'category',brands:'brand',contacts:'contact',locations:'location',classifications:'classification'};
function asId(v:unknown){return typeof v==='string'&&v.length>0?v:undefined}function batchId(r:ImportRecord){return asId(r.id)??randomUUID()}function logicalType(e:string){return ENTITY_TYPE[e]??e}function detectParentCycle(map:Map<string,string|undefined>,id:string){const seen=new Set([id]);let current=map.get(id);while(current){if(seen.has(current))return true;seen.add(current);current=map.get(current)}return false}
async function existingIds(db:Db,companyId:string,type:string){const c=f2EntityCollection(db,type);if(!c)return new Set<string>();const rows=await c.find({companyId},{projection:{_id:1}}).toArray();return new Set(rows.map((r:Document)=>String(r._id)))}
async function referenceExists(db:Db,companyId:string,type:string,id:string,batchIds:Set<string>,sameEntity:boolean){if(sameEntity&&batchIds.has(id))return true;return(await validateF2Reference(db,companyId,type,id))===null}
async function validateRecord(db:Db,companyId:string,entity:string,record:ImportRecord,batchIds:Set<string>,parentById:Map<string,string|undefined>,kindById:Map<string,string>,warehouseById:Map<string,string>){
 if(entity==='products'){const unit=typeof record.unit==='string'?record.unit:undefined;if(!unit||!await db.collection<any>(F2_ENTITY_COLLECTIONS.unit).findOne({companyId,code:unit},{projection:{_id:1}}))return `Unit '${String(record.unit)}' not found`}
 if(entity==='addresses'||entity==='contacts'){const partyId=asId(record.partyId);if(!partyId||!await referenceExists(db,companyId,'party',partyId,batchIds,false))return `Party '${String(record.partyId)}' not found`}
 if(entity==='prices'){const productId=asId(record.productId),priceListId=asId(record.priceListId);if(!productId||!await referenceExists(db,companyId,'product',productId,batchIds,false))return `Product '${String(record.productId)}' not found`;if(!priceListId||!await referenceExists(db,companyId,'price_list',priceListId,batchIds,false))return `Price list '${String(record.priceListId)}' not found`}
 if(entity==='attachments'){if(record.storageManaged===true)return 'Managed attachments must be restored through the binary upload endpoint';const targetType=typeof record.entityType==='string'?record.entityType:'';const targetId=asId(record.entityId);if(!targetId||!await referenceExists(db,companyId,targetType,targetId,batchIds,false))return `Attachment target '${targetType}:${String(record.entityId)}' not found`}
 if(entity==='relationships'){const sourceType=typeof record.sourceType==='string'?record.sourceType:'',sourceId=asId(record.sourceId),targetType=typeof record.targetType==='string'?record.targetType:'',targetId=asId(record.targetId);if(!sourceId||!await referenceExists(db,companyId,sourceType,sourceId,batchIds,false))return `Relationship source '${sourceType}:${String(record.sourceId)}' not found`;if(!targetId||!await referenceExists(db,companyId,targetType,targetId,batchIds,false))return `Relationship target '${targetType}:${String(record.targetId)}' not found`}
 if(entity==='locations'){const warehouseId=asId(record.warehouseId);if(!warehouseId||!await referenceExists(db,companyId,'warehouse',warehouseId,batchIds,false))return `Warehouse '${String(record.warehouseId)}' not found`;const parentId=asId(record.parentId);if(parentId){if(!await referenceExists(db,companyId,'location',parentId,batchIds,true))return 'Location parent not found';const childKind=String(record.kind??''),parentKind=kindById.get(parentId)??String((await db.collection<any>(F2_ENTITY_COLLECTIONS.location).findOne({_id:parentId,companyId},{projection:{kind:1}}))?.kind??''),parentWarehouse=warehouseById.get(parentId)??String((await db.collection<any>(F2_ENTITY_COLLECTIONS.location).findOne({_id:parentId,companyId},{projection:{warehouseId:1}}))?.warehouseId??'');if(!validLocationParentKind(childKind,parentKind)||parentWarehouse!==warehouseId)return 'Invalid location hierarchy'}else if(String(record.kind)!=='zone')return 'Root warehouse location must be a zone'}
 if(entity==='categories'||entity==='classifications'){const parentId=asId(record.parentId);if(parentId&&!await referenceExists(db,companyId,logicalType(entity),parentId,batchIds,true))return 'Parent not found'}
 if((entity==='categories'||entity==='classifications'||entity==='locations')&&detectParentCycle(parentById,String(record.id)))return 'Hierarchy cycle detected';return null
}
function normalizeRecord(entity:string, value:ImportRecord):ImportRecord { const normalized={...value}; if(entity==='products' && typeof normalized.price==='number') normalized.price=normalized.price.toFixed(6); if(entity==='prices' && typeof normalized.amount==='number') normalized.amount=normalized.amount.toFixed(6); if(entity==='products' && typeof normalized.price==='string') normalized.price=Decimal128.fromString(normalized.price); if(entity==='prices' && typeof normalized.amount==='string') normalized.amount=Decimal128.fromString(normalized.amount); return normalized }
export async function importF2Batch(options:ImportOptions):Promise<F2ImportResult>{const{db,companyId,entity,records,schema,collection}=options;const parsed:Array<{index:number;id:string;value:ImportRecord}>=[],errors:F2ImportResult['errors']=[],seenIds=new Set<string>();for(let index=0;index<records.length;index++){try{const value=schema.parse(records[index])as ImportRecord;const id=batchId(value);if(seenIds.has(id))throw new Error(`Duplicate id '${id}' in import batch`);seenIds.add(id);parsed.push({index,id,value:normalizeRecord(entity,{...value,id})})}catch(error){errors.push({index,error:error instanceof Error?error.message:String(error)})}}
 const type=logicalType(entity),existing=await existingIds(db,companyId,type);for(const row of parsed)if(existing.has(row.id))errors.push({index:row.index,error:`Entity '${row.id}' already exists`});const batchIds=new Set(parsed.map(r=>r.id)),parentById=new Map<string,string|undefined>(),kindById=new Map<string,string>(),warehouseById=new Map<string,string>();for(const row of parsed){parentById.set(row.id,asId(row.value.parentId));if(entity==='locations'){kindById.set(row.id,String(row.value.kind??''));warehouseById.set(row.id,asId(row.value.warehouseId)??'')}}
 const pending=parsed.filter(r=>!errors.some(e=>e.index===r.index)),insertedIds=new Set<string>();let progress=true;while(pending.length>0&&progress){progress=false;for(let i=pending.length-1;i>=0;i--){const row=pending[i],parentId=asId(row.value.parentId);if(parentId&&batchIds.has(parentId)&&!insertedIds.has(parentId))continue;const validation=await validateRecord(db,companyId,entity,row.value,batchIds,parentById,kindById,warehouseById);if(validation){if(parentId&&batchIds.has(parentId)&&!insertedIds.has(parentId)&&(validation==='Parent not found'||validation==='Location parent not found'||validation==='Invalid location hierarchy'))continue;errors.push({index:row.index,error:validation});pending.splice(i,1);continue}const now=new Date(),{id:_id,...body}=row.value;try{await collection.insertOne(companyId,{_id:row.id,companyId,...body,createdAt:now,updatedAt:now});insertedIds.add(row.id);pending.splice(i,1);progress=true}catch(error){errors.push({index:row.index,error:error instanceof Error?error.message:String(error)});pending.splice(i,1)}}}
 for(const row of pending)errors.push({index:row.index,error:'Unresolvable dependency or hierarchy cycle'});errors.sort((a,b)=>a.index-b.index);
 if(errors.length>0&&insertedIds.size>0){for(const insertedId of insertedIds)await collection.deleteOne(companyId,{_id:insertedId});insertedIds.clear()}
 return{inserted:insertedIds.size,failed:records.length-insertedIds.size,errors}}
export function assertF2ImportEntity(entity:string):void{const supported=new Set([...Object.keys(F2_ENTITY_COLLECTIONS),'categories','brands','contacts','locations','classifications','attachments','relationships']);if(!supported.has(entity))throw new Error(`Unsupported master-data entity '${entity}'`)}
