import { randomUUID } from 'node:crypto';
import type { Db } from 'mongodb';
import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';
import { tenantCollection } from '../../core/db.js';
import { created, fail, noContent, ok, paginated, parsePagination } from '../../core/api.js';

type Base = { _id:string; companyId:string; code:string; name:string; active:boolean; createdAt:Date; updatedAt:Date };
type Category = Base & { parentId?:string; description?:string };
type Brand = Base & { description?:string };
type Contact = { _id:string; companyId:string; partyId:string; name:string; role?:string; email?:string; phone?:string; mobile?:string; active:boolean; createdAt:Date; updatedAt:Date };
type Location = Base & { warehouseId:string; parentId?:string; kind:'zone'|'aisle'|'rack'|'shelf'|'bin'; capacity?:number };
type Classification = Base & { type:string; parentId?:string; description?:string };
type Attachment = { _id:string; companyId:string; entityType:string; entityId:string; fileName:string; mimeType:string; size:number; storageKey:string; checksum?:string; metadata?:Record<string,unknown>; createdAt:Date; updatedAt:Date };
type Relationship = { _id:string; companyId:string; sourceType:string; sourceId:string; relation:string; targetType:string; targetId:string; metadata?:Record<string,unknown>; createdAt:Date; updatedAt:Date };
type Audit = { _id:string; companyId:string; actorUserId:string; action:string; resource:string; resourceId:string; metadata?:Record<string,unknown>; createdAt:Date };

const id=z.string().uuid(); const code=z.string().trim().min(1).max(80).regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/); const name=z.string().trim().min(1).max(160);
const baseSchema=z.object({code,name,description:z.string().trim().max(2000).optional(),active:z.boolean().default(true)});
const categorySchema=baseSchema.extend({parentId:id.optional()});
const brandSchema=baseSchema;
const contactSchema=z.object({partyId:id,name:z.string().trim().min(1).max(160),role:z.string().trim().max(80).optional(),email:z.string().email().max(320).optional(),phone:z.string().trim().max(40).optional(),mobile:z.string().trim().max(40).optional(),active:z.boolean().default(true)});
const locationSchema=baseSchema.extend({warehouseId:id, parentId:id.optional(), kind:z.enum(['zone','aisle','rack','shelf','bin']), capacity:z.number().finite().nonnegative().max(1e12).optional()});
const classificationSchema=baseSchema.extend({type:z.string().trim().min(1).max(80),parentId:id.optional()});
const attachmentSchema=z.object({entityType:z.string().trim().min(1).max(80),entityId:id,fileName:z.string().trim().min(1).max(255),mimeType:z.string().trim().min(1).max(160),size:z.number().int().nonnegative().max(50_000_000),storageKey:z.string().trim().min(1).max(500),checksum:z.string().trim().max(128).optional(),metadata:z.record(z.unknown()).optional()});
const relationshipSchema=z.object({sourceType:z.string().trim().min(1).max(80),sourceId:id,relation:z.string().trim().min(1).max(80),targetType:z.string().trim().min(1).max(80),targetId:id,metadata:z.record(z.unknown()).optional()});
const update=(schema:z.ZodObject<any>)=>schema.partial().refine(v=>Object.keys(v).length>0,'At least one field must be supplied');
function actor(res:{locals:{user?:unknown}}):{id:string;companyId:string;role:Role}{return res.locals.user as {id:string;companyId:string;role:Role}}
function can(res:any,permission:'master-data:read'|'master-data:write'){return hasPermission(actor(res).role,permission)}
function publicDoc<T extends {_id:string;createdAt:Date;updatedAt:Date}>(d:T){const {_id,...rest}=d;return {id:_id,...rest}}
async function audit(db:Db,a:{id:string;companyId:string},action:string,resource:string,resourceId:string,metadata?:Record<string,unknown>){await db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action,resource,resourceId,metadata,createdAt:new Date()})}

export async function ensureF2Collections(db:Db):Promise<void>{
 const defs:Record<string,Array<{key:Record<string,1|-1>;options?:Record<string,unknown>}>>={
  product_categories:[{key:{companyId:1,code:1},options:{unique:true,name:'product_categories_company_code_unique'}},{key:{companyId:1,parentId:1}}],
  product_brands:[{key:{companyId:1,code:1},options:{unique:true,name:'product_brands_company_code_unique'}},{key:{companyId:1,active:1,name:1}}],
  party_contacts:[{key:{companyId:1,partyId:1,name:1},options:{unique:true,name:'party_contacts_party_name_unique'}},{key:{companyId:1,partyId:1,active:1}}],
  warehouse_locations:[{key:{companyId:1,warehouseId:1,code:1},options:{unique:true,name:'warehouse_locations_warehouse_code_unique'}},{key:{companyId:1,warehouseId:1,parentId:1}}],
  classifications:[{key:{companyId:1,type:1,code:1},options:{unique:true,name:'classifications_type_code_unique'}},{key:{companyId:1,type:1,active:1}}],
  master_attachments:[{key:{companyId:1,entityType:1,entityId:1,createdAt:-1}}],
  master_relationships:[{key:{companyId:1,sourceType:1,sourceId:1,relation:1,targetType:1,targetId:1},options:{unique:true,name:'master_relationship_unique'}},{key:{companyId:1,targetType:1,targetId:1}}]
 };
 const existing=new Set((await db.listCollections({}, {nameOnly:true}).toArray()).map(x=>x.name));
 for(const [n,indexes] of Object.entries(defs)){if(!existing.has(n))await db.createCollection(n);for(const i of indexes){try{await db.collection(n).createIndex(i.key,i.options)}catch(e){if(!String(e).includes('already exists'))throw e}}}
}

export function f2Router(db:Db):Router{
 const r=Router();r.use(requireAuth);
 const cats=tenantCollection<Category>(db,'product_categories'),brands=tenantCollection<Brand>(db,'product_brands'),contacts=tenantCollection<Contact>(db,'party_contacts'),locations=tenantCollection<Location>(db,'warehouse_locations'),classes=tenantCollection<Classification>(db,'classifications'),attachments=tenantCollection<Attachment>(db,'master_attachments'),rels=tenantCollection<Relationship>(db,'master_relationships');
 const products=tenantCollection<any>(db,'products'),parties=tenantCollection<any>(db,'parties'),warehouses=tenantCollection<any>(db,'warehouses');
 const list=async(res:any,c:any,companyId:string,q:any,filter:any={},sort:any={createdAt:-1})=>{const p=parsePagination(q);const [items,total]=await Promise.all([c.find(companyId,filter).sort(sort).skip(p.offset).limit(p.limit).toArray(),c.find(companyId,filter).count()]);paginated(res,items.map(publicDoc),total,p)};
 const crud=(path:string,c:any,schema:any,resource:string)=>{
  r.get(path,async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');await list(res,c,actor(res).companyId,req.query)}catch(e){next(e)}});
  r.get(`${path}/:id`,async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const d=await c.findOne(actor(res).companyId,{_id:req.params.id});if(!d)return fail(res,404,'NOT_FOUND',`${resource} not found`);ok(res,{[resource]:publicDoc(d)})}catch(e){next(e)}});
  r.post(path,async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),input=schema.parse(req.body),now=new Date(),d={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};await c.insertOne(a.companyId,d);await audit(db,a,`master-data.${resource}.create`,resource,d._id);created(res,{[resource]:publicDoc(d)})}catch(e){next(e)}});
  r.patch(`${path}/:id`,async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),input=update(schema).parse(req.body),old=await c.findOne(a.companyId,{_id:req.params.id});if(!old)return fail(res,404,'NOT_FOUND',`${resource} not found`);await c.updateOne(a.companyId,{_id:req.params.id},{$set:{...input,updatedAt:new Date()}});const d=await c.findOne(a.companyId,{_id:req.params.id});await audit(db,a,`master-data.${resource}.update`,resource,req.params.id,{changed:Object.keys(input)});ok(res,{[resource]:publicDoc(d)})}catch(e){next(e)}});
  r.delete(`${path}/:id`,async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),x=await c.updateOne(a.companyId,{_id:req.params.id,active:true},{$set:{active:false,updatedAt:new Date()}});if(!x.matchedCount)return fail(res,404,'NOT_FOUND',`${resource} not found`);await audit(db,a,`master-data.${resource}.deactivate`,resource,req.params.id);noContent(res)}catch(e){next(e)}});
 };
 crud('/categories',cats,categorySchema,'category');crud('/brands',brands,brandSchema,'brand');
 r.get('/contacts',async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const a=actor(res);await list(res,contacts,a.companyId,req.query,req.query.partyId?{partyId:req.query.partyId}:{} ,{name:1})}catch(e){next(e)}});
 r.post('/contacts',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),input=contactSchema.parse(req.body),party=await parties.findOne(a.companyId,{_id:input.partyId,active:true});if(!party)return fail(res,404,'NOT_FOUND','Party not found');const now=new Date(),d={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};await contacts.insertOne(a.companyId,d);await audit(db,a,'master-data.contact.create','contact',d._id);created(res,{contact:publicDoc(d)})}catch(e){next(e)}});
 r.patch('/contacts/:id',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),input=contactSchema.partial().refine(v=>Object.keys(v).length>0).parse(req.body),old=await contacts.findOne(a.companyId,{_id:req.params.id});if(!old)return fail(res,404,'NOT_FOUND','Contact not found');if(input.partyId&&!(await parties.findOne(a.companyId,{_id:input.partyId,active:true})))return fail(res,404,'NOT_FOUND','Party not found');await contacts.updateOne(a.companyId,{_id:req.params.id},{$set:{...input,updatedAt:new Date()}});ok(res,{contact:publicDoc(await contacts.findOne(a.companyId,{_id:req.params.id}))});await audit(db,a,'master-data.contact.update','contact',req.params.id)}catch(e){next(e)}});
 r.delete('/contacts/:id',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),x=await contacts.updateOne(a.companyId,{_id:req.params.id,active:true},{$set:{active:false,updatedAt:new Date()}});if(!x.matchedCount)return fail(res,404,'NOT_FOUND','Contact not found');await audit(db,a,'master-data.contact.deactivate','contact',req.params.id);noContent(res)}catch(e){next(e)}});
 crud('/warehouse-locations',locations,locationSchema,'location');
 crud('/classifications',classes,classificationSchema,'classification');
 r.post('/attachments',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),input=attachmentSchema.parse(req.body),now=new Date(),d={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};await attachments.insertOne(a.companyId,d);await audit(db,a,'master-data.attachment.create','attachment',d._id);created(res,{attachment:publicDoc(d)})}catch(e){next(e)}});
 r.get('/attachments',async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const a=actor(res);await list(res,attachments,a.companyId,req.query,{entityType:req.query.entityType,entityId:req.query.entityId})}catch(e){next(e)}});
 r.delete('/attachments/:id',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),x=await attachments.deleteOne(a.companyId,{_id:req.params.id});if(!x.deletedCount)return fail(res,404,'NOT_FOUND','Attachment not found');await audit(db,a,'master-data.attachment.delete','attachment',req.params.id);noContent(res)}catch(e){next(e)}});
 r.post('/relationships',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),input=relationshipSchema.parse(req.body),now=new Date(),d={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};await rels.insertOne(a.companyId,d);await audit(db,a,'master-data.relationship.create','relationship',d._id);created(res,{relationship:publicDoc(d)})}catch(e){next(e)}});
 r.get('/relationships',async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const a=actor(res);const filter:any={};for(const k of ['sourceType','sourceId','relation','targetType','targetId'])if(typeof req.query[k]==='string')filter[k]=req.query[k];await list(res,rels,a.companyId,req.query,filter)}catch(e){next(e)}});
 r.delete('/relationships/:id',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),x=await rels.deleteOne(a.companyId,{_id:req.params.id});if(!x.deletedCount)return fail(res,404,'NOT_FOUND','Relationship not found');await audit(db,a,'master-data.relationship.delete','relationship',req.params.id);noContent(res)}catch(e){next(e)}});
 r.get('/search',async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const a=actor(res),q=String(req.query.q??'').trim();if(q.length<2)return fail(res,400,'VALIDATION_ERROR','q must contain at least 2 characters');const re={$regex:q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'};const [p,b,pa,w,u]=await Promise.all([products.find(a.companyId,{$or:[{sku:re},{name:re}]}).limit(10).toArray(),brands.find(a.companyId,{$or:[{code:re},{name:re}]}).limit(10).toArray(),parties.find(a.companyId,{$or:[{code:re},{name:re},{email:re}]}).limit(10).toArray(),warehouses.find(a.companyId,{$or:[{code:re},{name:re}]}).limit(10).toArray(),cats.find(a.companyId,{$or:[{code:re},{name:re}]}).limit(10).toArray()]);ok(res,{query:q,results:{products:p.map(publicDoc),brands:b.map(publicDoc),parties:pa.map(publicDoc),warehouses:w.map(publicDoc),categories:u.map(publicDoc)}})}catch(e){next(e)}});
 r.get('/integrity',async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const a=actor(res);const [partyDocs,addressDocs,catDocs,locDocs,relDocs]=await Promise.all([parties.find(a.companyId,{}).toArray(),db.collection<any>('addresses').find({companyId:a.companyId}).toArray(),cats.find(a.companyId,{}).toArray(),locations.find(a.companyId,{}).toArray(),rels.find(a.companyId,{}).toArray()]);const partyIds=new Set(partyDocs.map(x=>x._id));const warehouseIds=new Set((await warehouses.find(a.companyId,{}).toArray()).map(x=>x._id));const catIds=new Set(catDocs.map(x=>x._id));const issues:any[]=[];for(const x of addressDocs)if(!partyIds.has(x.partyId))issues.push({type:'orphan_address',id:x._id,partyId:x.partyId});for(const x of locDocs)if(!warehouseIds.has(x.warehouseId)|| (x.parentId&&!locDocs.some(y=>y._id===x.parentId)))issues.push({type:'orphan_location',id:x._id});for(const x of catDocs)if(x.parentId&&!catIds.has(x.parentId))issues.push({type:'orphan_category_parent',id:x._id});const entitySets:any={party:partyIds,category:catIds};for(const x of relDocs){const set=entitySets[x.sourceType];if(set&&!set.has(x.sourceId))issues.push({type:'orphan_relationship_source',id:x._id});}ok(res,{healthy:issues.length===0,issueCount:issues.length,issues})}catch(e){next(e)}});
 r.get('/export/:entity',async(req,res,next)=>{try{if(!can(res,'master-data:read'))return fail(res,403,'FORBIDDEN');const a=actor(res),map:any={categories:cats,brands,contacts,locations,classes:classes,attachments,relationships:rels};const c=map[req.params.entity];if(!c)return fail(res,404,'NOT_FOUND','Unsupported export entity');const docs=await c.find(a.companyId,{}).sort({createdAt:1}).toArray();res.setHeader('Content-Type','application/json');res.setHeader('Content-Disposition',`attachment; filename="kz-erp-${req.params.entity}.json"`);res.send(JSON.stringify(docs))}catch(e){next(e)}});
 r.post('/import/:entity',async(req,res,next)=>{try{if(!can(res,'master-data:write'))return fail(res,403,'FORBIDDEN');const a=actor(res),map:any={categories:[cats,categorySchema,'category'],brands:[brands,brandSchema,'brand'],contacts:[contacts,contactSchema,'contact'],locations:[locations,locationSchema,'location'],classifications:[classes,classificationSchema,'classification']};const item=map[req.params.entity];if(!item)return fail(res,404,'NOT_FOUND','Unsupported import entity');if(!Array.isArray(req.body))return fail(res,400,'VALIDATION_ERROR','Import body must be an array');if(req.body.length>1000)return fail(res,413,'PAYLOAD_TOO_LARGE','Maximum 1000 records per import');const [c,s,resource]=item;let inserted=0,failed=0;const errors:any[]=[];for(let i=0;i<req.body.length;i++){try{const input=s.parse(req.body[i]),now=new Date(),d={_id:randomUUID(),companyId:a.companyId,...input,createdAt:now,updatedAt:now};await c.insertOne(a.companyId,d);inserted++}catch(e){failed++;errors.push({index:i,error:e instanceof Error?e.message:String(e)})}}await audit(db,a,`master-data.${req.params.entity}.import`,resource,randomUUID(),{inserted,failed});ok(res,{inserted,failed,errors})}catch(e){next(e)}});
 return r;
}
