import { randomUUID } from 'node:crypto';
import { Decimal128 } from 'mongodb';
import type { Db } from 'mongodb';
import { Router } from 'express';
import { z } from 'zod';
import { created, fail, noContent, ok, paginated, parsePagination } from '../../core/api.js';
import { tenantCollection } from '../../core/db.js';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';
import type { Product, Customer, Supplier, Warehouse } from '../../core/models.js';
import type { MasterAddress, MasterParty, MasterUnit, PriceList, ProductPrice } from './types.js';

const id = z.string().uuid();
const productSchema = z.object({ sku: z.string().trim().min(1).max(80), name: z.string().trim().min(1).max(160), description: z.string().trim().max(2000).optional(), unit: z.string().trim().min(1).max(20), price: z.number().finite().min(0).max(1_000_000_000), active: z.boolean().default(true) });
const partySchema = z.object({ code: z.string().trim().min(1).max(80), kind: z.enum(['person', 'company']), roles: z.array(z.enum(['customer', 'supplier', 'contact', 'carrier', 'other'])).min(1).max(5), name: z.string().trim().min(1).max(160), legalName: z.string().trim().max(200).optional(), document: z.string().trim().max(40).optional(), email: z.string().email().max(320).optional(), phone: z.string().trim().max(40).optional(), active: z.boolean().default(true) });
const addressSchema = z.object({ code: z.string().trim().min(1).max(80), type: z.enum(['billing', 'shipping', 'commercial', 'residential', 'other']), label: z.string().trim().max(120).optional(), recipientName: z.string().trim().max(160).optional(), postalCode: z.string().trim().min(3).max(20), street: z.string().trim().min(1).max(160), number: z.string().trim().min(1).max(30), complement: z.string().trim().max(120).optional(), district: z.string().trim().min(1).max(120), city: z.string().trim().min(1).max(120), state: z.string().trim().min(1).max(120), country: z.string().trim().min(2).max(80).default('BR'), active: z.boolean().default(true) });
const unitSchema = z.object({ code: z.string().trim().regex(/^[A-Za-z0-9_-]+$/).max(20), name: z.string().trim().min(1).max(80), symbol: z.string().trim().min(1).max(12), kind: z.enum(['unit', 'weight', 'volume', 'length', 'area', 'time', 'other']), decimalPlaces: z.number().int().min(0).max(6).default(0), active: z.boolean().default(true) });
const priceListSchema = z.object({ code: z.string().trim().min(1).max(40), name: z.string().trim().min(1).max(120), currency: z.string().trim().regex(/^[A-Z]{3}$/), validFrom: z.coerce.date().optional(), validUntil: z.coerce.date().optional(), active: z.boolean().default(true) }).refine(v => !v.validUntil || !v.validFrom || v.validUntil >= v.validFrom, { message: 'validUntil must be on or after validFrom', path: ['validUntil'] });
const priceSchema = z.object({ productId: id, amount: z.string().trim().regex(/^\d+(?:\.\d{1,6})?$/).refine(v => Number(v) <= 1_000_000_000, 'amount is too large'), minQuantity: z.number().int().positive().max(1_000_000).default(1), active: z.boolean().default(true) });

function actor(res: Parameters<typeof requireAuth>[1]): { id: string; companyId: string; role: Role } { return res.locals.user as { id: string; companyId: string; role: Role }; }
function canRead(res: Parameters<typeof requireAuth>[1]): boolean { return hasPermission(actor(res).role, 'master-data:read'); }
function canWrite(res: Parameters<typeof requireAuth>[1]): boolean { return hasPermission(actor(res).role, 'master-data:write'); }
function auditEntry(db: Db, companyId: string, actorUserId: string, action: string, resource: string, resourceId: string, metadata?: Record<string, unknown>) {
  return db.collection('audit_logs').insertOne({ _id: randomUUID(), companyId, actorUserId, action, resource, resourceId, metadata, createdAt: new Date() });
}

export function masterDataRouter(db: Db): Router {
  const router = Router();
  router.use(requireAuth);
  const products = tenantCollection<Product>(db, 'products');
  const customers = tenantCollection<Customer>(db, 'customers');
  const suppliers = tenantCollection<Supplier>(db, 'suppliers');
  const warehouses = tenantCollection<Warehouse>(db, 'warehouses');
  const parties = tenantCollection<MasterParty>(db, 'parties');
  const addresses = tenantCollection<MasterAddress>(db, 'addresses');
  const units = tenantCollection<MasterUnit>(db, 'units');
  const priceLists = tenantCollection<PriceList>(db, 'price_lists');
  const prices = tenantCollection<ProductPrice>(db, 'prices');

  const list = async <T extends { companyId: string }>(res: Parameters<typeof ok>[0], collection: ReturnType<typeof tenantCollection<T>>, companyId: string, query: Parameters<typeof parsePagination>[0], sort: Record<string, 1 | -1> = { createdAt: -1 }) => {
    const p = parsePagination(query);
    const [items, total] = await Promise.all([collection.find(companyId).sort(sort).skip(p.offset).limit(p.limit).toArray(), collection.find(companyId).count()]);
    paginated(res, items, total, p);
  };

  router.get('/products', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } await list(res, products, actor(res).companyId, req.query); } catch (e) { next(e); } });
  router.post('/products', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = productSchema.parse(req.body); const now = new Date(); const doc: Product = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await products.insertOne(a.companyId, doc); await auditEntry(db, a.companyId, a.id, 'master-data.product.create', 'product', doc._id!); created(res, { product: doc }); } catch (e) { next(e); } });
  router.patch('/products/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = productSchema.partial().refine(v => Object.keys(v).length > 0).parse(req.body); const existing = await products.findOne(a.companyId, { _id: req.params.id }); if (!existing) { fail(res, 404, 'NOT_FOUND', 'Product not found'); return; } await products.updateOne(a.companyId, { _id: req.params.id }, { $set: { ...input, updatedAt: new Date() } }); const updated = await products.findOne(a.companyId, { _id: req.params.id }); await auditEntry(db, a.companyId, a.id, 'master-data.product.update', 'product', req.params.id); ok(res, { product: updated }); } catch (e) { next(e); } });
  router.delete('/products/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await products.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Product not found'); return; } await auditEntry(db, a.companyId, a.id, 'master-data.product.deactivate', 'product', req.params.id); noContent(res); } catch (e) { next(e); } });

  router.get('/parties', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); await list(res, parties, a.companyId, req.query, { name: 1 }); } catch (e) { next(e); } });
  router.get('/parties/:id', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const party = await parties.findOne(a.companyId, { _id: req.params.id }); if (!party) { fail(res, 404, 'NOT_FOUND', 'Party not found'); return; } ok(res, { party }); } catch (e) { next(e); } });
  router.post('/parties', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = partySchema.parse(req.body); const now = new Date(); const party: MasterParty = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await parties.insertOne(a.companyId, party); await auditEntry(db, a.companyId, a.id, 'master-data.party.create', 'party', party._id!); created(res, { party }); } catch (e) { next(e); } });
  router.patch('/parties/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = partySchema.partial().refine(v => Object.keys(v).length > 0).parse(req.body); const existing = await parties.findOne(a.companyId, { _id: req.params.id }); if (!existing) { fail(res, 404, 'NOT_FOUND', 'Party not found'); return; } await parties.updateOne(a.companyId, { _id: req.params.id }, { $set: { ...input, updatedAt: new Date() } }); const updated = await parties.findOne(a.companyId, { _id: req.params.id }); await auditEntry(db, a.companyId, a.id, 'master-data.party.update', 'party', req.params.id); ok(res, { party: updated }); } catch (e) { next(e); } });
  router.delete('/parties/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await parties.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Party not found'); return; } await addresses.updateOne(a.companyId, { partyId: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); await auditEntry(db, a.companyId, a.id, 'master-data.party.deactivate', 'party', req.params.id); noContent(res); } catch (e) { next(e); } });

  router.get('/parties/:partyId/addresses', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const party = await parties.findOne(a.companyId, { _id: req.params.partyId }); if (!party) { fail(res, 404, 'NOT_FOUND', 'Party not found'); return; } await list(res, addresses, a.companyId, req.query, { createdAt: -1 }); } catch (e) { next(e); } });
  router.post('/parties/:partyId/addresses', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const party = await parties.findOne(a.companyId, { _id: req.params.partyId, active: true }); if (!party) { fail(res, 404, 'NOT_FOUND', 'Party not found'); return; } const input = addressSchema.parse(req.body); const now = new Date(); const address: MasterAddress = { _id: randomUUID(), companyId: a.companyId, partyId: req.params.partyId, ...input, createdAt: now, updatedAt: now }; await addresses.insertOne(a.companyId, address); await auditEntry(db, a.companyId, a.id, 'master-data.address.create', 'address', address._id!); created(res, { address }); } catch (e) { next(e); } });
  router.patch('/addresses/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = addressSchema.partial().refine(v => Object.keys(v).length > 0).parse(req.body); const existing = await addresses.findOne(a.companyId, { _id: req.params.id }); if (!existing) { fail(res, 404, 'NOT_FOUND', 'Address not found'); return; } await addresses.updateOne(a.companyId, { _id: req.params.id }, { $set: { ...input, updatedAt: new Date() } }); const updated = await addresses.findOne(a.companyId, { _id: req.params.id }); await auditEntry(db, a.companyId, a.id, 'master-data.address.update', 'address', req.params.id); ok(res, { address: updated }); } catch (e) { next(e); } });
  router.delete('/addresses/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await addresses.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Address not found'); return; } await auditEntry(db, a.companyId, a.id, 'master-data.address.deactivate', 'address', req.params.id); noContent(res); } catch (e) { next(e); } });

  router.get('/units', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } await list(res, units, actor(res).companyId, req.query, { code: 1 }); } catch (e) { next(e); } });
  router.post('/units', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = unitSchema.parse(req.body); const now = new Date(); const unit: MasterUnit = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await units.insertOne(a.companyId, unit); await auditEntry(db, a.companyId, a.id, 'master-data.unit.create', 'unit', unit._id!); created(res, { unit }); } catch (e) { next(e); } });
  router.patch('/units/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = unitSchema.partial().refine(v => Object.keys(v).length > 0).parse(req.body); const existing = await units.findOne(a.companyId, { _id: req.params.id }); if (!existing) { fail(res, 404, 'NOT_FOUND', 'Unit not found'); return; } await units.updateOne(a.companyId, { _id: req.params.id }, { $set: { ...input, updatedAt: new Date() } }); const updated = await units.findOne(a.companyId, { _id: req.params.id }); await auditEntry(db, a.companyId, a.id, 'master-data.unit.update', 'unit', req.params.id); ok(res, { unit: updated }); } catch (e) { next(e); } });
  router.delete('/units/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await units.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Unit not found'); return; } await auditEntry(db, a.companyId, a.id, 'master-data.unit.deactivate', 'unit', req.params.id); noContent(res); } catch (e) { next(e); } });

  router.get('/price-lists', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } await list(res, priceLists, actor(res).companyId, req.query, { name: 1 }); } catch (e) { next(e); } });
  router.post('/price-lists', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = priceListSchema.parse(req.body); const now = new Date(); const listDoc: PriceList = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await priceLists.insertOne(a.companyId, listDoc); await auditEntry(db, a.companyId, a.id, 'master-data.price-list.create', 'price_list', listDoc._id!); created(res, { priceList: listDoc }); } catch (e) { next(e); } });
  router.patch('/price-lists/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = priceListSchema.partial().refine(v => Object.keys(v).length > 0).parse(req.body); const existing = await priceLists.findOne(a.companyId, { _id: req.params.id }); if (!existing) { fail(res, 404, 'NOT_FOUND', 'Price list not found'); return; } await priceLists.updateOne(a.companyId, { _id: req.params.id }, { $set: { ...input, updatedAt: new Date() } }); const updated = await priceLists.findOne(a.companyId, { _id: req.params.id }); await auditEntry(db, a.companyId, a.id, 'master-data.price-list.update', 'price_list', req.params.id); ok(res, { priceList: updated }); } catch (e) { next(e); } });
  router.delete('/price-lists/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await priceLists.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Price list not found'); return; } await prices.updateOne(a.companyId, { priceListId: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); await auditEntry(db, a.companyId, a.id, 'master-data.price-list.deactivate', 'price_list', req.params.id); noContent(res); } catch (e) { next(e); } });

  router.get('/price-lists/:priceListId/prices', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const listDoc = await priceLists.findOne(a.companyId, { _id: req.params.priceListId }); if (!listDoc) { fail(res, 404, 'NOT_FOUND', 'Price list not found'); return; } await list(res, prices, a.companyId, req.query, { createdAt: -1 }); } catch (e) { next(e); } });
  router.post('/price-lists/:priceListId/prices', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const listDoc = await priceLists.findOne(a.companyId, { _id: req.params.priceListId, active: true }); if (!listDoc) { fail(res, 404, 'NOT_FOUND', 'Price list not found'); return; } const input = priceSchema.parse(req.body); const product = await products.findOne(a.companyId, { _id: input.productId, active: true }); if (!product) { fail(res, 404, 'NOT_FOUND', 'Product not found'); return; } const now = new Date(); const price: ProductPrice = { _id: randomUUID(), companyId: a.companyId, priceListId: req.params.priceListId, productId: input.productId, amount: Decimal128.fromString(input.amount), minQuantity: input.minQuantity, active: input.active, createdAt: now, updatedAt: now }; await prices.insertOne(a.companyId, price); await auditEntry(db, a.companyId, a.id, 'master-data.price.create', 'price', price._id!); created(res, { price: { ...price, amount: price.amount.toString() } }); } catch (e) { next(e); } });
  router.patch('/prices/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = priceSchema.partial().omit({ productId: true }).parse(req.body); const existing = await prices.findOne(a.companyId, { _id: req.params.id }); if (!existing) { fail(res, 404, 'NOT_FOUND', 'Price not found'); return; } const set: Record<string, unknown> = { updatedAt: new Date() }; if (input.amount !== undefined) set.amount = Decimal128.fromString(input.amount); if (input.minQuantity !== undefined) set.minQuantity = input.minQuantity; if (input.active !== undefined) set.active = input.active; await prices.updateOne(a.companyId, { _id: req.params.id }, { $set: set }); const updated = await prices.findOne(a.companyId, { _id: req.params.id }); await auditEntry(db, a.companyId, a.id, 'master-data.price.update', 'price', req.params.id); ok(res, { price: updated ? { ...updated, amount: updated.amount.toString() } : null }); } catch (e) { next(e); } });
  router.delete('/prices/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await prices.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Price not found'); return; } await auditEntry(db, a.companyId, a.id, 'master-data.price.deactivate', 'price', req.params.id); noContent(res); } catch (e) { next(e); } });

  // Compatibility resources used by the existing sales screen. They remain tenant-isolated while F2 introduces the unified Party model.
  router.get('/customers', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } await list(res, customers, actor(res).companyId, req.query); } catch (e) { next(e); } });
  router.post('/customers', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = z.object({ code: z.string().trim().min(1).max(80), name: z.string().trim().min(1).max(160), document: z.string().trim().max(40).optional(), email: z.string().email().max(320).optional(), phone: z.string().trim().max(40).optional(), active: z.boolean().default(true) }).parse(req.body); const now = new Date(); const doc: Customer = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await customers.insertOne(a.companyId, doc); await auditEntry(db, a.companyId, a.id, 'master-data.customer.create', 'customer', doc._id!); created(res, { customer: doc }); } catch (e) { next(e); } });
  router.delete('/customers/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await customers.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Customer not found'); return; } noContent(res); } catch (e) { next(e); } });
  router.get('/suppliers', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } await list(res, suppliers, actor(res).companyId, req.query); } catch (e) { next(e); } });
  router.post('/suppliers', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = z.object({ code: z.string().trim().min(1).max(80), name: z.string().trim().min(1).max(160), document: z.string().trim().max(40).optional(), email: z.string().email().max(320).optional(), phone: z.string().trim().max(40).optional(), active: z.boolean().default(true) }).parse(req.body); const now = new Date(); const doc: Supplier = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await suppliers.insertOne(a.companyId, doc); await auditEntry(db, a.companyId, a.id, 'master-data.supplier.create', 'supplier', doc._id!); created(res, { supplier: doc }); } catch (e) { next(e); } });
  router.delete('/suppliers/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await suppliers.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Supplier not found'); return; } noContent(res); } catch (e) { next(e); } });
  router.get('/warehouses', async (req, res, next) => { try { if (!canRead(res)) { fail(res, 403, 'FORBIDDEN'); return; } await list(res, warehouses, actor(res).companyId, req.query); } catch (e) { next(e); } });
  router.post('/warehouses', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const input = z.object({ code: z.string().trim().min(1).max(80), name: z.string().trim().min(1).max(160), active: z.boolean().default(true) }).parse(req.body); const now = new Date(); const doc: Warehouse = { _id: randomUUID(), companyId: a.companyId, ...input, createdAt: now, updatedAt: now }; await warehouses.insertOne(a.companyId, doc); await auditEntry(db, a.companyId, a.id, 'master-data.warehouse.create', 'warehouse', doc._id!); created(res, { warehouse: doc }); } catch (e) { next(e); } });
  router.delete('/warehouses/:id', async (req, res, next) => { try { if (!canWrite(res)) { fail(res, 403, 'FORBIDDEN'); return; } const a = actor(res); const result = await warehouses.updateOne(a.companyId, { _id: req.params.id, active: true }, { $set: { active: false, updatedAt: new Date() } }); if (!result.matchedCount) { fail(res, 404, 'NOT_FOUND', 'Warehouse not found'); return; } noContent(res); } catch (e) { next(e); } });

  return router;
}
