import { createHash, randomUUID } from 'node:crypto';
import { Decimal128, MongoServerError } from 'mongodb';
import type { Db, Filter } from 'mongodb';
import { Router } from 'express';
import { z } from 'zod';
import { created, fail, ok, paginated, parsePagination } from '../../core/api.js';
import { currentMongoSession, tenantCollection, withMongoTransaction } from '../../core/db.js';
import { requireAuth } from '../../core/auth.js';
import { hasPermission, type Role } from '../../core/types.js';
import type { Product, Supplier, Warehouse, StockBalance, StockMovement } from '../../core/models.js';
import type { PurchaseRequest, PurchaseQuote, PurchaseQuoteLine, PurchaseOrder, PurchaseReceipt, ScmOutboxEvent } from './types.js';

const id=z.string().uuid(), idem=z.string().uuid();
const quantity=z.string().trim().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/,'quantity must be a decimal string with up to 6 decimal places').refine(v=>v!=='0','quantity must be greater than zero');
const money=z.string().trim().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/,'money must be a decimal string with up to 2 decimal places');
const uniqueLines=<T extends {productId:string}>(schema:z.ZodArray<z.ZodType<T>>)=>schema.superRefine((lines,ctx)=>{if(new Set(lines.map(x=>x.productId)).size!==lines.length)ctx.addIssue({code:'custom',message:'duplicate productId in lines'});});
const requestSchema=z.object({number:z.string().trim().min(1).max(80),lines:uniqueLines(z.array(z.object({productId:id,quantity}))),notes:z.string().trim().max(1000).optional()});
const quoteSchema=z.object({number:z.string().trim().min(1).max(80),requestId:id,supplierId:id,lines:uniqueLines(z.array(z.object({productId:id,quantity,unitPrice:money})))});
const orderSchema=z.object({number:z.string().trim().min(1).max(80),supplierId:id,quoteId:id.optional(),lines:uniqueLines(z.array(z.object({productId:id,quantity,unitPrice:money})))});
const receiptSchema=z.object({number:z.string().trim().min(1).max(80),purchaseOrderId:id,warehouseId:id,lines:uniqueLines(z.array(z.object({productId:id,quantity})))});
type Actor={id:string;companyId:string;role:Role};
type Audit={_id:string;companyId:string;actorUserId:string;action:string;resource:string;resourceId:string;metadata?:Record<string,unknown>;createdAt:Date};
function actor(res:Parameters<typeof requireAuth>[1]):Actor{return res.locals.user as Actor;}
function decimal(v:string){return Decimal128.fromString(v);}
function hash(v:unknown){return createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function key(req:Parameters<typeof requireAuth>[0]){const raw=req.get('Idempotency-Key');return raw?idem.parse(raw):undefined;}
function qtyScaled(v:string){const[w='0',f='']=v.split('.');return BigInt(w)*1_000_000n+BigInt(f.padEnd(6,'0'));}
function moneyCents(v:string){const[w='0',f='']=v.split('.');return BigInt(w)*100n+BigInt(f.padEnd(2,'0'));}
function moneyFromCents(v:bigint){const whole=v/100n;const fraction=(v%100n).toString().padStart(2,'0');return `${whole}${fraction==='00'?'':`.${fraction}`}`;}
function lineTotal(q:string,p:string){const raw=qtyScaled(q)*moneyCents(p);const rounded=(raw+500_000n)/1_000_000n;return decimal(moneyFromCents(rounded));}
function actorCan(res:Parameters<typeof requireAuth>[1],p:string){return hasPermission(actor(res).role,p);}
function serializeRequest(v:PurchaseRequest){return{id:v._id,number:v.number,status:v.status,lines:v.lines.map(l=>({productId:l.productId,description:l.description,quantity:l.quantity.toString()})),notes:v.notes,createdAt:v.createdAt,updatedAt:v.updatedAt};}
function serializeQuote(v:PurchaseQuote){return{id:v._id,number:v.number,requestId:v.requestId,supplierId:v.supplierId,status:v.status,lines:v.lines.map(l=>({productId:l.productId,description:l.description,quantity:l.quantity.toString(),unitPrice:l.unitPrice.toString(),total:l.total.toString()})),subtotal:v.subtotal.toString(),createdAt:v.createdAt,updatedAt:v.updatedAt};}
function serializeOrder(v:PurchaseOrder){return{id:v._id,number:v.number,supplierId:v.supplierId,quoteId:v.quoteId,status:v.status,lines:v.lines.map(l=>({productId:l.productId,description:l.description,quantity:l.quantity.toString(),unitPrice:l.unitPrice.toString(),total:l.total.toString()})),subtotal:v.subtotal.toString(),receivedQuantities:Object.fromEntries(Object.entries(v.receivedQuantities??{}).map(([p,q])=>[p,q.toString()])),createdAt:v.createdAt,updatedAt:v.updatedAt};}
function serializeReceipt(v:PurchaseReceipt){return{id:v._id,number:v.number,purchaseOrderId:v.purchaseOrderId,warehouseId:v.warehouseId,lines:v.lines.map(l=>({productId:l.productId,quantity:l.quantity.toString()})),receivedAt:v.receivedAt,createdAt:v.createdAt,updatedAt:v.updatedAt};}
function q(v:Decimal128){return qtyScaled(v.toString());}
function scaledString(v:bigint){const whole=v/1_000_000n;const fraction=(v%1_000_000n).toString().padStart(6,'0').replace(/0+$/,'');return `${whole}${fraction?`.${fraction}`:''}`;}

export function scmRouter(db:Db):Router{
 const router=Router();router.use(requireAuth);
 const requests=tenantCollection<PurchaseRequest>(db,'scm_purchase_requests'),quotes=tenantCollection<PurchaseQuote>(db,'scm_purchase_quotes'),orders=tenantCollection<PurchaseOrder>(db,'scm_purchase_orders'),receipts=tenantCollection<PurchaseReceipt>(db,'scm_purchase_receipts');
 const products=tenantCollection<Product>(db,'products'),suppliers=tenantCollection<Supplier>(db,'suppliers'),warehouses=tenantCollection<Warehouse>(db,'warehouses'),balances=tenantCollection<StockBalance>(db,'stock_balances'),movements=tenantCollection<StockMovement>(db,'stock_movements');
 const audit=(a:Actor,action:string,resource:string,resourceId:string,metadata?:Record<string,unknown>)=>db.collection<Audit>('audit_logs').insertOne({_id:randomUUID(),companyId:a.companyId,actorUserId:a.id,action,resource,resourceId,metadata,createdAt:new Date()},{session:currentMongoSession()});
 const emit=(a:Actor,type:string,aggregateType:string,aggregateId:string,payload:Record<string,unknown>)=>{const now=new Date();return db.collection<ScmOutboxEvent>('scm_outbox_events').insertOne({_id:randomUUID(),companyId:a.companyId,type,aggregateType,aggregateId,payload,status:'pending',attempts:0,availableAt:now,createdAt:now,updatedAt:now},{session:currentMongoSession()});};
 async function productsFor(c:string,input:Array<{productId:string;quantity:string}>){const ids=[...new Set(input.map(x=>x.productId))];const found=await products.find(c,{_id:{$in:ids},active:true}).toArray();if(found.length!==ids.length)throw new Error('PRODUCT_NOT_FOUND');return input.map(x=>({productId:x.productId,description:found.find(p=>p._id===x.productId)!.name,quantity:decimal(x.quantity)}));}
 async function priced(c:string,input:Array<{productId:string;quantity:string;unitPrice:string}>){const ids=[...new Set(input.map(x=>x.productId))];const found=await products.find(c,{_id:{$in:ids},active:true}).toArray();if(found.length!==ids.length)throw new Error('PRODUCT_NOT_FOUND');const lines:PurchaseQuoteLine[]=input.map(x=>({productId:x.productId,description:found.find(p=>p._id===x.productId)!.name,quantity:decimal(x.quantity),unitPrice:decimal(x.unitPrice),total:lineTotal(x.quantity,x.unitPrice)}));return{lines,subtotal:decimal(moneyFromCents(lines.reduce((s,l)=>s+moneyCents(l.total.toString()),0n)))};}
 router.get('/requests',async(req,res,next)=>{try{if(!actorCan(res,'scm:read')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),p=parsePagination(req.query),f:Filter<PurchaseRequest>={};if(typeof req.query.status==='string')f.status=z.enum(['draft','submitted','approved','rejected','cancelled']).parse(req.query.status);const[items,count]=await Promise.all([requests.find(a.companyId,f).sort({createdAt:-1}).skip(p.offset).limit(p.limit).toArray(),requests.find(a.companyId,f).count()]);paginated(res,items.map(serializeRequest),count,p);}catch(e){next(e);}});
 router.get('/quotes',async(req,res,next)=>{try{if(!actorCan(res,'scm:read')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),p=parsePagination(req.query),f:Filter<PurchaseQuote>={};if(typeof req.query.requestId==='string')f.requestId=id.parse(req.query.requestId);if(typeof req.query.supplierId==='string')f.supplierId=id.parse(req.query.supplierId);if(typeof req.query.status==='string')f.status=z.enum(['draft','submitted','accepted','rejected','cancelled']).parse(req.query.status);const[items,count]=await Promise.all([quotes.find(a.companyId,f).sort({createdAt:-1}).skip(p.offset).limit(p.limit).toArray(),quotes.find(a.companyId,f).count()]);paginated(res,items.map(serializeQuote),count,p);}catch(e){next(e);}});
 router.get('/orders',async(req,res,next)=>{try{if(!actorCan(res,'scm:read')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),p=parsePagination(req.query),f:Filter<PurchaseOrder>={};if(typeof req.query.supplierId==='string')f.supplierId=id.parse(req.query.supplierId);if(typeof req.query.status==='string')f.status=z.enum(['draft','approved','ordered','partially_received','received','cancelled']).parse(req.query.status);const[items,count]=await Promise.all([orders.find(a.companyId,f).sort({createdAt:-1}).skip(p.offset).limit(p.limit).toArray(),orders.find(a.companyId,f).count()]);paginated(res,items.map(serializeOrder),count,p);}catch(e){next(e);}});
 router.get('/receipts',async(req,res,next)=>{try{if(!actorCan(res,'scm:read')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),p=parsePagination(req.query),f:Filter<PurchaseReceipt>={};if(typeof req.query.purchaseOrderId==='string')f.purchaseOrderId=id.parse(req.query.purchaseOrderId);if(typeof req.query.warehouseId==='string')f.warehouseId=id.parse(req.query.warehouseId);const[items,count]=await Promise.all([receipts.find(a.companyId,f).sort({createdAt:-1}).skip(p.offset).limit(p.limit).toArray(),receipts.find(a.companyId,f).count()]);paginated(res,items.map(serializeReceipt),count,p);}catch(e){next(e);}});
 router.post('/requests',async(req,res,next)=>{let k:string|undefined,h:string|undefined;try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=requestSchema.parse(req.body);k=key(req);h=hash(input);if(k){const prior=await requests.findOne(a.companyId,{idempotencyKey:k});if(prior){if(prior.operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{request:serializeRequest(prior)});return;}}const value=await withMongoTransaction(db,async()=>{const lines=await productsFor(a.companyId,input.lines),now=new Date();const value:PurchaseRequest={_id:randomUUID(),companyId:a.companyId,number:input.number,status:'draft',lines,notes:input.notes,idempotencyKey:k,operationHash:h,createdAt:now,updatedAt:now};await requests.insertOne(a.companyId,value);await audit(a,'scm.purchase_request.create','purchase_request',value._id);await emit(a,'purchase.request.created','purchase_request',value._id,{number:value.number});return value;});created(res,{request:serializeRequest(value)});}catch(e){if(e instanceof Error&&e.message==='PRODUCT_NOT_FOUND'){fail(res,404,'NOT_FOUND','Product not found');return;}if(e instanceof MongoServerError&&e.code===11000&&k&&h){const prior=await requests.findOne(actor(res).companyId,{idempotencyKey:k});if(prior&&prior.operationHash===h){created(res,{request:serializeRequest(prior)});return;}}next(e);}});
 async function requestTransition(req:Parameters<typeof requireAuth>[0],res:Parameters<typeof requireAuth>[1],next:Parameters<typeof requireAuth>[2],action:'submit'|'approve'|'reject'|'cancel'){try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),rid=id.parse(req.params.id);await withMongoTransaction(db,async()=>{const current=await requests.findOne(a.companyId,{_id:rid});if(!current)throw new Error('REQUEST_NOT_FOUND');const allowed:Record<string,PurchaseRequest['status'][]>= {submit:['draft'],approve:['submitted'],reject:['submitted'],cancel:['draft','submitted']};if(!allowed[action].includes(current.status))throw new Error('INVALID_TRANSITION');const status=action==='submit'?'submitted':action==='approve'?'approved':action==='reject'?'rejected':'cancelled';await requests.updateOne(a.companyId,{_id:rid,status:current.status},{$set:{status,updatedAt:new Date()}});await audit(a,`scm.purchase_request.${action}`,'purchase_request',rid);await emit(a,`purchase.request.${status}`,'purchase_request',rid,{status});});ok(res,{status:'ok'});}catch(e){if(e instanceof Error&&e.message==='REQUEST_NOT_FOUND'){fail(res,404,'NOT_FOUND','Purchase request not found');return;}if(e instanceof Error&&e.message==='INVALID_TRANSITION'){fail(res,409,'CONFLICT','Invalid purchase request state transition');return;}next(e);}}
 router.post('/requests/:id/submit',(req,res,next)=>void requestTransition(req,res,next,'submit'));router.post('/requests/:id/approve',(req,res,next)=>void requestTransition(req,res,next,'approve'));router.post('/requests/:id/reject',(req,res,next)=>void requestTransition(req,res,next,'reject'));router.post('/requests/:id/cancel',(req,res,next)=>void requestTransition(req,res,next,'cancel'));
 router.post('/quotes',async(req,res,next)=>{let k:string|undefined,h:string|undefined;try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=quoteSchema.parse(req.body);k=key(req);h=hash(input);if(k){const prior=await quotes.findOne(a.companyId,{idempotencyKey:k});if(prior){if(prior.operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{quote:serializeQuote(prior)});return;}}const value=await withMongoTransaction(db,async()=>{const request=await requests.findOne(a.companyId,{_id:input.requestId});if(!request)throw new Error('REQUEST_NOT_FOUND');if(!['submitted','approved'].includes(request.status))throw new Error('REQUEST_NOT_QUOTABLE');if(!(await suppliers.findOne(a.companyId,{_id:input.supplierId,active:true})))throw new Error('SUPPLIER_NOT_FOUND');const built=await priced(a.companyId,input.lines),now=new Date();const value:PurchaseQuote={_id:randomUUID(),companyId:a.companyId,number:input.number,requestId:input.requestId,supplierId:input.supplierId,status:'draft',lines:built.lines,subtotal:built.subtotal,idempotencyKey:k,operationHash:h,createdAt:now,updatedAt:now};await quotes.insertOne(a.companyId,value);await audit(a,'scm.purchase_quote.create','purchase_quote',value._id);await emit(a,'purchase.quote.created','purchase_quote',value._id,{requestId:value.requestId,supplierId:value.supplierId});return value;});created(res,{quote:serializeQuote(value)});}catch(e){if(e instanceof Error){if(e.message==='REQUEST_NOT_FOUND'){fail(res,404,'NOT_FOUND','Purchase request not found');return;}if(e.message==='REQUEST_NOT_QUOTABLE'){fail(res,409,'CONFLICT','Purchase request is not ready for quotation');return;}if(e.message==='SUPPLIER_NOT_FOUND'||e.message==='PRODUCT_NOT_FOUND'){fail(res,404,'NOT_FOUND',e.message==='SUPPLIER_NOT_FOUND'?'Supplier not found':'Product not found');return;}}if(e instanceof MongoServerError&&e.code===11000&&k&&h){const prior=await quotes.findOne(actor(res).companyId,{idempotencyKey:k});if(prior&&prior.operationHash===h){created(res,{quote:serializeQuote(prior)});return;}}next(e);}});
 router.post('/quotes/:id/submit',async(req,res,next)=>{try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),qid=id.parse(req.params.id);await withMongoTransaction(db,async()=>{const q=await quotes.findOne(a.companyId,{_id:qid,status:'draft'});if(!q)throw new Error('QUOTE_NOT_DRAFT');await quotes.updateOne(a.companyId,{_id:qid,status:'draft'},{$set:{status:'submitted',updatedAt:new Date()}});await audit(a,'scm.purchase_quote.submit','purchase_quote',qid);await emit(a,'purchase.quote.submitted','purchase_quote',qid,{number:q.number});});ok(res,{status:'submitted'});}catch(e){if(e instanceof Error&&e.message==='QUOTE_NOT_DRAFT'){fail(res,409,'CONFLICT','Only draft quotes can be submitted');return;}next(e);}});
 router.post('/quotes/:id/accept',async(req,res,next)=>{try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),qid=id.parse(req.params.id);await withMongoTransaction(db,async()=>{const q=await quotes.findOne(a.companyId,{_id:qid,status:'submitted'});if(!q)throw new Error('QUOTE_NOT_SUBMITTED');await quotes.updateOne(a.companyId,{_id:qid,status:'submitted'},{$set:{status:'accepted',updatedAt:new Date()}});await audit(a,'scm.purchase_quote.accept','purchase_quote',qid);await emit(a,'purchase.quote.accepted','purchase_quote',qid,{number:q.number});});ok(res,{status:'accepted'});}catch(e){if(e instanceof Error&&e.message==='QUOTE_NOT_SUBMITTED'){fail(res,409,'CONFLICT','Only submitted quotes can be accepted');return;}next(e);}});
 router.post('/quotes/:id/reject',async(req,res,next)=>{try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),qid=id.parse(req.params.id);await withMongoTransaction(db,async()=>{const q=await quotes.findOne(a.companyId,{_id:qid,status:'submitted'});if(!q)throw new Error('QUOTE_NOT_SUBMITTED');await quotes.updateOne(a.companyId,{_id:qid,status:'submitted'},{$set:{status:'rejected',updatedAt:new Date()}});await audit(a,'scm.purchase_quote.reject','purchase_quote',qid);await emit(a,'purchase.quote.rejected','purchase_quote',qid,{number:q.number});});ok(res,{status:'rejected'});}catch(e){if(e instanceof Error&&e.message==='QUOTE_NOT_SUBMITTED'){fail(res,409,'CONFLICT','Only submitted quotes can be rejected');return;}next(e);}});
 router.post('/orders',async(req,res,next)=>{let k:string|undefined,h:string|undefined;try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=orderSchema.parse(req.body);k=key(req);h=hash(input);if(k){const prior=await orders.findOne(a.companyId,{idempotencyKey:k});if(prior){if(prior.operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{order:serializeOrder(prior)});return;}}const value=await withMongoTransaction(db,async()=>{if(!(await suppliers.findOne(a.companyId,{_id:input.supplierId,active:true})))throw new Error('SUPPLIER_NOT_FOUND');if(input.quoteId){const quote=await quotes.findOne(a.companyId,{_id:input.quoteId,status:'accepted'});if(!quote||quote.supplierId!==input.supplierId)throw new Error('QUOTE_NOT_ACCEPTED');}const built=await priced(a.companyId,input.lines),now=new Date();const value:PurchaseOrder={_id:randomUUID(),companyId:a.companyId,number:input.number,supplierId:input.supplierId,quoteId:input.quoteId,status:'draft',lines:built.lines,subtotal:built.subtotal,receivedQuantities:{},idempotencyKey:k,operationHash:h,createdAt:now,updatedAt:now};await orders.insertOne(a.companyId,value);await audit(a,'scm.purchase_order.create','purchase_order',value._id);await emit(a,'purchase.created','purchase_order',value._id,{number:value.number,supplierId:value.supplierId});return value;});created(res,{order:serializeOrder(value)});}catch(e){if(e instanceof Error){if(e.message==='SUPPLIER_NOT_FOUND'||e.message==='PRODUCT_NOT_FOUND'){fail(res,404,'NOT_FOUND',e.message==='SUPPLIER_NOT_FOUND'?'Supplier not found':'Product not found');return;}if(e.message==='QUOTE_NOT_ACCEPTED'){fail(res,409,'CONFLICT','Only an accepted quote for the same supplier can be used');return;}}if(e instanceof MongoServerError&&e.code===11000&&k&&h){const prior=await orders.findOne(actor(res).companyId,{idempotencyKey:k});if(prior&&prior.operationHash===h){created(res,{order:serializeOrder(prior)});return;}}next(e);}});
 async function orderTransition(req:Parameters<typeof requireAuth>[0],res:Parameters<typeof requireAuth>[1],next:Parameters<typeof requireAuth>[2],from:PurchaseOrder['status'],to:PurchaseOrder['status']){try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),oid=id.parse(req.params.id);await withMongoTransaction(db,async()=>{const current=await orders.findOne(a.companyId,{_id:oid,status:from});if(!current)throw new Error('ORDER_TRANSITION_INVALID');await orders.updateOne(a.companyId,{_id:oid,status:from},{$set:{status:to,updatedAt:new Date()}});await audit(a,`scm.purchase_order.${to}`,'purchase_order',oid);await emit(a,`purchase.order.${to}`,'purchase_order',oid,{status:to});});ok(res,{status:to});}catch(e){if(e instanceof Error&&e.message==='ORDER_TRANSITION_INVALID'){fail(res,409,'CONFLICT','Invalid purchase order state transition');return;}next(e);}}
 router.post('/orders/:id/approve',(req,res,next)=>void orderTransition(req,res,next,'draft','approved'));router.post('/orders/:id/order',(req,res,next)=>void orderTransition(req,res,next,'approved','ordered'));router.post('/orders/:id/cancel',(req,res,next)=>void orderTransition(req,res,next,'draft','cancelled'));
 router.post('/receipts',async(req,res,next)=>{let k:string|undefined,h:string|undefined;try{if(!actorCan(res,'scm:write')){fail(res,403,'FORBIDDEN');return;}const a=actor(res),input=receiptSchema.parse(req.body);k=key(req);h=hash(input);if(k){const prior=await receipts.findOne(a.companyId,{idempotencyKey:k});if(prior){if(prior.operationHash!==h){fail(res,409,'CONFLICT','Idempotency-Key was already used for a different operation');return;}created(res,{receipt:serializeReceipt(prior)});return;}}const value=await withMongoTransaction(db,async()=>{const order=await orders.findOne(a.companyId,{_id:input.purchaseOrderId});if(!order)throw new Error('ORDER_NOT_FOUND');if(!['ordered','partially_received'].includes(order.status))throw new Error('ORDER_NOT_RECEIVABLE');if(!(await warehouses.findOne(a.companyId,{_id:input.warehouseId,active:true})))throw new Error('WAREHOUSE_NOT_FOUND');const allowed=new Map(order.lines.map(l=>[l.productId,q(l.quantity)]));const previous=order.receivedQuantities??{};const next={...previous};const incoming=await productsFor(a.companyId,input.lines);for(const line of incoming){const max=allowed.get(line.productId);if(max===undefined)throw new Error('PRODUCT_NOT_IN_ORDER');const current=q(previous[line.productId]??decimal('0'));const amount=q(line.quantity);if(current+amount>max)throw new Error('RECEIPT_EXCEEDS_ORDER');next[line.productId]=decimal(scaledString(current+amount));}
for(const line of incoming){const existing=await balances.findOne(a.companyId,{warehouseId:input.warehouseId,productId:line.productId});const now=new Date();if(existing)await balances.updateOne(a.companyId,{warehouseId:input.warehouseId,productId:line.productId},{$inc:{quantity:line.quantity},$set:{updatedAt:now}});else await balances.insertOne(a.companyId,{_id:randomUUID(),companyId:a.companyId,warehouseId:input.warehouseId,productId:line.productId,quantity:line.quantity,reservedQuantity:decimal('0'),minimumQuantity:decimal('0'),createdAt:now,updatedAt:now});const movement:StockMovement={_id:randomUUID(),companyId:a.companyId,type:'receipt',productId:line.productId,warehouseId:input.warehouseId,quantity:line.quantity,direction:'increase',reason:'SCM purchase receipt',reference:input.number,actorUserId:a.id,createdAt:now};await movements.insertOne(a.companyId,movement);}
const fully=order.lines.every(line=>q(next[line.productId]??decimal('0'))>=q(line.quantity));const status=fully?'received':'partially_received';const r=await orders.updateOne(a.companyId,{_id:order._id,status:order.status},{$set:{receivedQuantities:next,status,updatedAt:new Date()}});if(!r.matchedCount)throw new Error('ORDER_CHANGED');const now=new Date();const receipt:PurchaseReceipt={_id:randomUUID(),companyId:a.companyId,number:input.number,purchaseOrderId:order._id,warehouseId:input.warehouseId,lines:incoming.map(x=>({productId:x.productId,quantity:x.quantity})),receivedAt:now,idempotencyKey:k,operationHash:h,actorUserId:a.id,createdAt:now,updatedAt:now};await receipts.insertOne(a.companyId,receipt);await audit(a,'scm.purchase_receipt.create','purchase_receipt',receipt._id,{purchaseOrderId:order._id,warehouseId:input.warehouseId,status});await emit(a,'purchase.received','purchase_receipt',receipt._id,{purchaseOrderId:order._id,warehouseId:input.warehouseId,status});return receipt;});created(res,{receipt:serializeReceipt(value)});}catch(e){if(e instanceof Error){const map:Record<string,[number,'NOT_FOUND'|'CONFLICT'|'VALIDATION_ERROR',string]>={ORDER_NOT_FOUND:[404,'NOT_FOUND','Purchase order not found'],ORDER_NOT_RECEIVABLE:[409,'CONFLICT','Purchase order is not ready for receiving'],WAREHOUSE_NOT_FOUND:[404,'NOT_FOUND','Warehouse not found'],PRODUCT_NOT_IN_ORDER:[400,'VALIDATION_ERROR','Receipt contains a product not present in the order'],RECEIPT_EXCEEDS_ORDER:[409,'CONFLICT','Receipt quantity exceeds the remaining ordered quantity'],ORDER_CHANGED:[409,'CONFLICT','Purchase order changed concurrently']};const item=map[e.message];if(item){fail(res,item[0],item[1],item[2]);return;}if(e.message==='PRODUCT_NOT_FOUND'){fail(res,404,'NOT_FOUND','Product not found');return;}}if(e instanceof MongoServerError&&e.code===11000&&k&&h){const prior=await receipts.findOne(actor(res).companyId,{idempotencyKey:k});if(prior&&prior.operationHash===h){created(res,{receipt:serializeReceipt(prior)});return;}}next(e);}});
 return router;
}
