import { AsyncLocalStorage } from 'node:async_hooks';
import type { ClientSession, Db, Document, Filter, OptionalUnlessRequiredId, UpdateFilter } from 'mongodb';
import type { ModuleCollectionMap } from './models.js';

const transactionContext = new AsyncLocalStorage<ClientSession>();

export function currentMongoSession(): ClientSession | undefined { return transactionContext.getStore(); }

export async function withMongoTransaction<T>(db: Db, work: () => Promise<T>): Promise<T> {
  const session = db.client.startSession();
  try { return await session.withTransaction(() => transactionContext.run(session, work)); }
  finally { await session.endSession(); }
}

export function tenantFilter<T extends Document>(companyId: string, filter: Filter<T> = {}): Filter<T> { if (!companyId.trim()) throw new Error('TENANT_ID_REQUIRED'); return { ...filter, companyId } as Filter<T>; }
function assertTenantImmutable(update: Document): void { const visit = (value: unknown): void => { if (!value || typeof value !== 'object') return; if (Array.isArray(value)) { for (const item of value) visit(item); return; } for (const [key, child] of Object.entries(value)) { if (key === 'companyId') throw new Error('TENANT_ID_IMMUTABLE'); visit(child); } }; visit(update); }
export function tenantCollection<T extends Document & { companyId: string }>(db: Db, name: string) {
  const collection = db.collection<T>(name);
  return {
    findOne: (companyId: string, filter: Filter<T> = {}) => collection.findOne(tenantFilter(companyId, filter), { session: currentMongoSession() }),
    find: (companyId: string, filter: Filter<T> = {}) => collection.find(tenantFilter(companyId, filter), { session: currentMongoSession() }),
    insertOne: (companyId: string, document: Omit<T, 'companyId'>) => collection.insertOne({ ...document, companyId } as OptionalUnlessRequiredId<T>, { session: currentMongoSession() }),
    updateOne: (companyId: string, filter: Filter<T>, update: UpdateFilter<T>) => { assertTenantImmutable(update); return collection.updateOne(tenantFilter(companyId, filter), update, { session: currentMongoSession() }); },
    updateMany: (companyId: string, filter: Filter<T>, update: UpdateFilter<T>) => { assertTenantImmutable(update); return collection.updateMany(tenantFilter(companyId, filter), update, { session: currentMongoSession() }); },
    deleteOne: (companyId: string, filter: Filter<T>) => collection.deleteOne(tenantFilter(companyId, filter), { session: currentMongoSession() })
  };
}
export async function ensureCoreCollections(db: Db): Promise<void> { const existing = new Set((await db.listCollections({}, { nameOnly: true }).toArray()).map(x => x.name)); for (const name of ['companies', 'users', 'audit_logs', 'auth_sessions', 'system']) if (!existing.has(name)) await db.createCollection(name); await db.collection('companies').createIndex({ slug: 1 }, { unique: true, name: 'companies_slug_unique' }); await db.collection('users').createIndex({ companyId: 1, email: 1 }, { unique: true, name: 'users_company_email_unique' }); await db.collection('users').createIndex({ companyId: 1, active: 1, role: 1 }, { name: 'users_company_active_role' }); await db.collection('users').createIndex({ companyId: 1, createdAt: -1 }, { name: 'users_company_created' }); await db.collection('audit_logs').createIndex({ companyId: 1, createdAt: -1 }, { name: 'audit_company_created' }); await db.collection('audit_logs').createIndex({ companyId: 1, action: 1, createdAt: -1 }, { name: 'audit_company_action_created' }); await db.collection('auth_sessions').createIndex({ tokenHash: 1 }, { unique: true, name: 'auth_sessions_token_unique' }); await db.collection('auth_sessions').createIndex({ companyId: 1, userId: 1, expiresAt: 1 }, { name: 'auth_sessions_user_expiry' }); await db.collection('auth_sessions').createIndex({ companyId: 1, userId: 1, accessJti: 1 }, { unique: true, sparse: true, name: 'auth_sessions_access_jti_unique' }); await db.collection('auth_sessions').createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0, name: 'auth_sessions_ttl' }); }
export async function ensureModuleCollections(db: Db): Promise<void> { const definitions: Partial<Record<keyof ModuleCollectionMap, { indexes: Array<{ key: Document; options?: Parameters<ReturnType<Db['collection']>['createIndex']>[1] }> }>> = { products: { indexes: [{ key: { companyId: 1, sku: 1 }, options: { unique: true, name: 'products_company_sku_unique' } }, { key: { companyId: 1, active: 1 } }] }, customers: { indexes: [{ key: { companyId: 1, code: 1 }, options: { unique: true, name: 'customers_company_code_unique' } }, { key: { companyId: 1, active: 1 } }] }, suppliers: { indexes: [{ key: { companyId: 1, code: 1 }, options: { unique: true, name: 'suppliers_company_code_unique' } }, { key: { companyId: 1, active: 1 } }] }, warehouses: { indexes: [{ key: { companyId: 1, code: 1 }, options: { unique: true, name: 'warehouses_company_code_unique' } }, { key: { companyId: 1, active: 1 } }] }, sales_orders: { indexes: [{ key: { companyId: 1, number: 1 }, options: { unique: true, name: 'sales_orders_company_number_unique' } }, { key: { companyId: 1, idempotencyKey: 1 }, options: { unique: true, sparse: true, name: 'sales_orders_company_idempotency_unique' } }, { key: { companyId: 1, status: 1, createdAt: -1 } }, { key: { companyId: 1, customerId: 1, createdAt: -1 } }] }, financial_entries: { indexes: [{ key: { companyId: 1, type: 1, status: 1, dueDate: 1 } }, { key: { companyId: 1, status: 1, dueDate: 1 } }, { key: { companyId: 1, idempotencyKey: 1 }, options: { unique: true, sparse: true, name: 'financial_entries_company_idempotency_unique' } }, { key: { companyId: 1, reference: 1 } }] }, fiscal_documents: { indexes: [{ key: { companyId: 1, number: 1, series: 1 }, options: { unique: true, name: 'fiscal_company_number_series_unique' } }, { key: { companyId: 1, status: 1, issuedAt: -1 } }, { key: { companyId: 1, accessKey: 1 }, options: { sparse: true, unique: true, name: 'fiscal_access_key_unique' } }] }, people: { indexes: [{ key: { companyId: 1, code: 1 }, options: { unique: true, name: 'people_company_code_unique' } }, { key: { companyId: 1, active: 1 } }] } }; const existing = new Set((await db.listCollections({}, { nameOnly: true }).toArray()).map(x => x.name)); for (const [name, definition] of Object.entries(definitions)) { if (!existing.has(name)) await db.createCollection(name); const collection = db.collection(name); for (const index of definition!.indexes) await collection.createIndex(index.key, index.options); } }
export type CoreCompany = { _id?: string; name: string; slug: string; active: boolean; createdAt: Date; updatedAt: Date };
export type CoreUser = { _id?: string; companyId: string; email: string; name: string; passwordHash: string; role: 'owner' | 'admin' | 'manager' | 'user' | 'viewer'; active: boolean; createdAt: Date; updatedAt: Date };
export type AuditLog = { _id?: string; companyId: string; actorUserId: string; action: string; resource: string; resourceId?: string; metadata?: Record<string, unknown>; createdAt: Date };
export type AuthSession = { _id?: string; companyId: string; userId: string; tokenHash: string; accessJti: string; createdAt: Date; expiresAt: Date };
