import React from 'react';
import { createRoot } from 'react-dom/client';
import { getCurrentWindow } from '@tauri-apps/api/window';
import './styles.css';
import { F1Admin } from './F1Admin';
import { F2MasterData } from './F2MasterData';
import { StockPage } from './StockPage';
import { SalesPage } from './SalesPage';
import { FinancePage } from './FinancePage';

type Session={accessToken:string;refreshToken:string;expiresIn?:number;user?:{id?:string;name?:string;email?:string;role?:string};companyId?:string};
type Me={user:{id:string;email:string;name:string;role:string};companyId:string};
type Company={name:string;slug:string;active?:boolean};
type View='overview'|'admin'|'cadastros'|'estoque'|'vendas'|'financeiro'|'fiscal'|'relatorios';
const API=(import.meta.env.VITE_API_URL??'https://kz-erp.onrender.com').replace(/\/$/,'');
function readSession():Session|null{try{const r=localStorage.getItem('kz-erp-session');return r?JSON.parse(r):null}catch{return null}}
function saveSession(s:Session){localStorage.setItem('kz-erp-session',JSON.stringify(s))}
function clearSession(){localStorage.removeItem('kz-erp-session')}
function isBinaryBody(body:BodyInit|undefined){return body instanceof Blob || body instanceof ArrayBuffer || (typeof ArrayBuffer!=='undefined' && ArrayBuffer.isView(body))}
async function raw(path:string,options:RequestInit={},token?:string){const h=new Headers(options.headers);h.set('Accept','application/json');if(options.body!==undefined&&!isBinaryBody(options.body as BodyInit))h.set('Content-Type','application/json');if(token)h.set('Authorization',`Bearer ${token}`);return fetch(`${API}${path}`,{...options,headers:h})}
async function parse<T>(r:Response):Promise<T>{const b=await r.json().catch(()=>null) as any;if(!r.ok)throw new Error(b?.error?.message??b?.error?.code??`HTTP ${r.status}`);return (b?.data??b) as T}
async function publicApi<T>(path:string,options:RequestInit={}):Promise<T>{return parse<T>(await raw(path,options))}
async function sessionApi<T>(path:string,s:Session,options:RequestInit={},setSession?:(s:Session)=>void):Promise<T>{let r=await raw(path,options,s.accessToken);if(r.status!==401||!s.refreshToken)return parse<T>(r);try{const n=await publicApi<{accessToken:string;refreshToken:string;expiresIn:number}>('/api/v1/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken:s.refreshToken})});const next={...s,...n};saveSession(next);setSession?.(next);return parse<T>(await raw(path,options,next.accessToken))}catch{clearSession();throw new Error('Sessão expirada. Entre novamente.')}}
function Titlebar({status}:{status:string}){const w=getCurrentWindow();return <div className="titlebar" data-tauri-drag-region onDoubleClick={()=>void w.toggleMaximize()}><div className="titlebar-brand"><span className="brand-mark mini">KZ</span><strong>KORCZAK ERP</strong><span className="titlebar-status">{status}</span></div><div className="window-controls"><button onClick={()=>void w.minimize()} aria-label="Minimizar">−</button><button onClick={()=>void w.toggleMaximize()} aria-label="Maximizar">□</button><button className="close-window" onClick={()=>void w.close()} aria-label="Fechar">×</button></div></div>}
function Login({onClose,onSuccess}:{onClose:()=>void;onSuccess:(s:Session)=>void}){const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');const[slug,setSlug]=React.useState('');const[error,setError]=React.useState('');const[busy,setBusy]=React.useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await publicApi<{accessToken:string;refreshToken:string;expiresIn:number}>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password,...(slug?{companySlug:slug}:{})})});onSuccess({...d,user:{email}})}catch(e){setError(e instanceof Error?e.message:'Falha no login')}finally{setBusy(false)}}return <div className="modal-backdrop"><div className="login-card"><button className="close" onClick={onClose}>×</button><div className="login-mark">KZ</div><p className="eyebrow">KORCZAK ERP</p><h2>Entrar</h2><p className="login-subtitle">Autenticação real do tenant.</p><form onSubmit={submit}><label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Empresa <span>opcional</span><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="minha-empresa"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form></div></div>}
function Auth({login}:{login:()=>void}){return <section className="state-box auth-required"><strong>Autenticação necessária.</strong><span>Entre para acessar dados reais.</span><button className="primary small" onClick={login}>Entrar</button></section>}
function App(){const[view,setView]=React.useState<View>('overview');const[session,setSession]=React.useState<Session|null>(readSession);const[me,setMe]=React.useState<Me|null>(null);const[company,setCompany]=React.useState<Company|null>(null);const[online,setOnline]=React.useState(false);const[error,setError]=React.useState('');const[toast,setToast]=React.useState('');const[login,setLogin]=React.useState(false);
 const health=React.useCallback(async()=>{try{await publicApi('/health');setOnline(true);setError('')}catch(e){setOnline(false);setError(e instanceof Error?e.message:'API indisponível')}},[]);
 const hydrate=React.useCallback(async(s:Session)=>{try{const[a,c]=await Promise.all([sessionApi<Me>('/api/v1/core/me',s,{},setSession),sessionApi<{company:Company}>('/api/v1/core/company',s,{},setSession)]);setMe(a);setCompany(c.company)}catch(e){clearSession();setSession(null);setMe(null);setCompany(null);setToast(e instanceof Error?e.message:'Sessão inválida')}} ,[]);
 React.useEffect(()=>{void health();const t=window.setInterval(()=>void health(),30000);return()=>window.clearInterval(t)},[health]);React.useEffect(()=>{if(session)void hydrate(session)},[session,hydrate]);
 const adminApi=React.useCallback((path:string,options:RequestInit={})=>session?sessionApi<any>(path,session,options,setSession):Promise.reject(new Error('Autenticação necessária')),[session]);
 const logout=()=>{const s=session;clearSession();setSession(null);setMe(null);setCompany(null);if(s)void publicApi('/api/v1/auth/logout',{method:'POST',body:JSON.stringify({refreshToken:s.refreshToken})}).catch(()=>{});setToast('Sessão encerrada.')};
 const labels:{id:View;label:string;icon:string}[]=[{id:'overview',label:'Visão geral',icon:'⌂'},{id:'admin',label:'Administração',icon:'⚙'},{id:'cadastros',label:'Cadastros',icon:'▦'},{id:'estoque',label:'Estoque',icon:'⇄'},{id:'vendas',label:'Vendas',icon:'◇'},{id:'financeiro',label:'Financeiro',icon:'◈'},{id:'fiscal',label:'Fiscal',icon:'◇'},{id:'relatorios',label:'Relatórios',icon:'▤'}];const title=labels.find(x=>x.id===view)?.label??'KORCZAK ERP';
 return <div className="app-root"><Titlebar status={online?'API online':'API offline'}/><div className="shell"><aside><div className="brand"><div className="brand-mark">KZ</div><div><strong>KORCZAK</strong><small>ERP</small></div></div><div className="workspace"><span className={`workspace-dot ${online?'online':''}`}/>{company?.name??(session?'Carregando empresa…':'Não autenticado')}</div><nav>{labels.map(x=><button key={x.id} className={view===x.id?'active':''} onClick={()=>setView(x.id)}><span>{x.icon}</span>{x.label}</button>)}</nav><div className="side-status"><span className={`dot ${online?'online':''}`}/>{online?'API online':'API offline'}<br/><small>F1 Core integrado</small></div></aside><main><header><div><p className="eyebrow">KORCZAK TECHNOLOGIES / KORCZAK ERP</p><h1>{title}</h1></div><div className="header-actions">{session?<button className="user-button" onClick={logout}>{me?.user.name??session.user?.email} <span>↪</span></button>:<button className="primary small" onClick={()=>setLogin(true)}>Entrar</button>}</div></header>{!online&&<div className="banner-error"><strong>API indisponível</strong><span>{error}</span><button onClick={()=>void health()}>Tentar novamente</button></div>}{view==='overview'&&<section className="hero"><div className="hero-copy"><span className="tag">F1 • CORE</span><h2>Administração centralizada.<br/><em>Dados reais, estado real.</em></h2><p>O Core administrativo está conectado ao backend oficial com isolamento por tenant, RBAC/ABAC e auditoria.</p><button className="primary" onClick={()=>session?setView('admin'):setLogin(true)}>{session?'Abrir administração':'Acessar ERP'} →</button></div><div className="orb"><div>KZ</div><span>{online?'ONLINE':'OFFLINE'}</span></div></section>}{view==='admin'&&(session?<F1Admin session={session} me={me} api={adminApi} onToast={setToast}/>:<Auth login={()=>setLogin(true)}/>)}{view==='cadastros'&&(session?<F2MasterData session={session} onToast={setToast}/>:<Auth login={()=>setLogin(true)}/>)}{view==='estoque'&&(session?<StockPage session={session} onToast={setToast} onSession={setSession}/>:<Auth login={()=>setLogin(true)}/>)}{view==='vendas'&&(session?<SalesPage session={session} onToast={setToast}/>:<Auth login={()=>setLogin(true)}/>)}{view==='financeiro'&&(session?<FinancePage session={session} onToast={setToast} onSession={setSession}/>:<Auth login={()=>setLogin(true)}/>)}{(view==='fiscal'||view==='relatorios')&&<section className="prepared"><span className="tag">MÓDULO PREPARADO</span><h2>{title}</h2><p>Área reservada para a fase correspondente. Nenhuma operação fictícia é apresentada.</p></section>}</main></div>{login&&<Login onClose={()=>setLogin(false)} onSuccess={s=>{saveSession(s);setSession(s);setLogin(false);setToast('Login realizado.')}}/>}{toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}</div>}
export function mount(){createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)}
