import React from 'react';

type Session={accessToken:string;refreshToken:string;expiresIn?:number;user?:{id?:string;name?:string;email?:string;role?:string};companyId?:string};
type ApiCall=(path:string,options?:RequestInit)=>Promise<any>;
type User={id:string;email:string;name:string;role:string;active:boolean;createdAt:string;updatedAt:string};
type Branch={id:string;companyId:string;code:string;name:string;legalName?:string;document?:string;active:boolean;createdAt:string;updatedAt:string};
type Audit={_id?:string;companyId:string;actorUserId:string;action:string;resource:string;resourceId?:string;metadata?:Record<string,unknown>;createdAt:string};
type Paged<T>={items:T[];total:number;limit:number;offset:number;hasMore:boolean};

const roles=['admin','manager','user','viewer'];
function errorMessage(e:unknown){return e instanceof Error?e.message:'Operação não concluída.';}
function formatDate(v:string){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));}catch{return v;}}

export function F1Admin({session,me,api,onToast}:{session:Session;me:{user:{id:string;name:string;email:string;role:string};companyId:string}|null;api:ApiCall;onToast:(message:string)=>void;}){
 const [tab,setTab]=React.useState<'empresa'|'filiais'|'usuarios'|'rbac'|'auditoria'>('empresa');
 const [loading,setLoading]=React.useState(false); const [error,setError]=React.useState('');
 const [company,setCompany]=React.useState<any>(null); const [branches,setBranches]=React.useState<Paged<Branch>|null>(null); const [users,setUsers]=React.useState<Paged<User>|null>(null); const [audit,setAudit]=React.useState<Paged<Audit>|null>(null);
 const [showBranch,setShowBranch]=React.useState(false); const [showUser,setShowUser]=React.useState(false); const [editingBranch,setEditingBranch]=React.useState<Branch|null>(null); const [editingUser,setEditingUser]=React.useState<User|null>(null);
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const [c,b,u,a]=await Promise.all([api('/api/v1/core/company'),api('/api/v1/core/branches?limit=50&offset=0'),api('/api/v1/core/users?limit=50&offset=0'),api('/api/v1/core/audit?limit=50&offset=0')]);setCompany(c.company);setBranches(b);setUsers(u);setAudit(a);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[api]);
 React.useEffect(()=>{void load();},[load]);
 async function updateCompany(name:string){try{await api('/api/v1/core/company',{method:'PATCH',body:JSON.stringify({name})});onToast('Empresa atualizada.');await load();}catch(e){setError(errorMessage(e));}}
 async function saveBranch(data:Record<string,unknown>){try{const path=editingBranch?`/api/v1/core/branches/${editingBranch.id}`:'/api/v1/core/branches';await api(path,{method:editingBranch?'PATCH':'POST',body:JSON.stringify(data)});setShowBranch(false);setEditingBranch(null);onToast(editingBranch?'Filial atualizada.':'Filial criada.');await load();}catch(e){setError(errorMessage(e));}}
 async function deactivateBranch(b:Branch){if(!b.active)return;if(!window.confirm(`Desativar a filial ${b.name}?`))return;try{await api(`/api/v1/core/branches/${b.id}`,{method:'DELETE'});onToast('Filial desativada.');await load();}catch(e){setError(errorMessage(e));}}
 async function saveUser(data:Record<string,unknown>){try{const path=editingUser?`/api/v1/core/users/${editingUser.id}`:'/api/v1/core/users';await api(path,{method:editingUser?'PATCH':'POST',body:JSON.stringify(data)});setShowUser(false);setEditingUser(null);onToast(editingUser?'Usuário atualizado.':'Usuário criado.');await load();}catch(e){setError(errorMessage(e));}}
 async function toggleUser(u:User){if(u.id===me?.user.id&&u.active)return;if(u.role==='owner'&&!u.active)return;try{await api(`/api/v1/core/users/${u.id}`,{method:'PATCH',body:JSON.stringify({active:!u.active})});onToast(u.active?'Usuário desativado.':'Usuário ativado.');await load();}catch(e){setError(errorMessage(e));}}
 return <section className="module-page f1-admin"><div className="module-intro"><span className="tag">F1 • CORE ADMIN</span><h2>Administração</h2><p>Empresa, filiais, usuários, permissões e auditoria conectados à API real.</p></div>
  <div className="subnav">{[['empresa','Empresa'],['filiais','Filiais'],['usuarios','Usuários'],['rbac','RBAC / acesso'],['auditoria','Auditoria']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as any)}>{label}</button>)}<button className="secondary" onClick={()=>void load()} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div>
  {error&&<div className="state-box error"><strong>Falha</strong><span>{error}</span><button onClick={()=>setError('')}>Fechar</button></div>}
  {tab==='empresa'&&<CompanyPanel company={company} role={me?.user.role} onSave={updateCompany}/>} 
  {tab==='filiais'&&<BranchesPanel data={branches} onNew={()=>{setEditingBranch(null);setShowBranch(true)}} onEdit={b=>{setEditingBranch(b);setShowBranch(true)}} onDeactivate={deactivateBranch}/>} 
  {tab==='usuarios'&&<UsersPanel data={users} currentUserId={me?.user.id} onNew={()=>{setEditingUser(null);setShowUser(true)}} onEdit={u=>{setEditingUser(u);setShowUser(true)}} onToggle={toggleUser}/>} 
  {tab==='rbac'&&<AccessPanel api={api} role={me?.user.role??'viewer'} onToast={onToast}/>} 
  {tab==='auditoria'&&<AuditPanel data={audit}/>} 
  {showBranch&&<BranchModal initial={editingBranch} onClose={()=>{setShowBranch(false);setEditingBranch(null)}} onSave={saveBranch}/>} 
  {showUser&&<UserModal initial={editingUser} onClose={()=>{setShowUser(false);setEditingUser(null)}} onSave={saveUser}/>} 
 </section>;
}
function CompanyPanel({company,role,onSave}:{company:any;role?:string;onSave:(name:string)=>Promise<void>}){const [name,setName]=React.useState('');React.useEffect(()=>setName(company?.name??''),[company?.name]);const can=role==='owner'||role==='admin';return <div className="f1-grid"><article className="panel"><div className="panel-head"><div><small>ORGANIZAÇÃO</small><h3>Empresa / tenant</h3></div><span>{company?.active?'ATIVA':'INATIVA'}</span></div><div className="form-card-inline"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} disabled={!can}/></label><div className="f1-readonly"><span>Slug</span><strong>{company?.slug??'—'}</strong></div><div className="f1-readonly"><span>Tenant ID</span><strong>{company?.id??'—'}</strong></div><button className="primary" disabled={!can||!name.trim()||name===company?.name} onClick={()=>void onSave(name.trim())}>Salvar empresa</button></div></article><article className="panel"><small>CONTEXTO</small><h3>Segurança F1</h3><div className="status-row"><span className="dot online"/><div><strong>Isolamento por empresa</strong><small>Requests usam o tenant da sessão.</small></div><b>ATIVO</b></div><div className="status-row"><span className="dot online"/><div><strong>RBAC + ABAC</strong><small>Permissões e escopos são avaliados no backend.</small></div><b>ATIVO</b></div><div className="status-row"><span className="dot online"/><div><strong>Auditoria</strong><small>Mutations administrativas geram eventos.</small></div><b>ATIVO</b></div></article></div>}
function BranchesPanel({data,onNew,onEdit,onDeactivate}:{data:Paged<Branch>|null;onNew:()=>void;onEdit:(b:Branch)=>void;onDeactivate:(b:Branch)=>void}){return <div className="data-page"><div className="page-toolbar"><div><span className="tag">ORGANIZAÇÃO</span><h2>Filiais</h2><p>Gerencie as unidades operacionais da empresa.</p></div><button className="primary" onClick={onNew}>+ Nova filial</button></div>{!data?<div className="state-box">Carregando filiais…</div>:data.items.length===0?<div className="state-box">Nenhuma filial cadastrada.</div>:<div className="table-wrap"><table><thead><tr><th>Código</th><th>Nome</th><th>Documento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.items.map(b=><tr key={b.id}><td>{b.code}</td><td><strong>{b.name}</strong><br/><small>{b.legalName??''}</small></td><td>{b.document??'—'}</td><td><span className={`status-pill ${b.active?'active':''}`}>{b.active?'Ativa':'Inativa'}</span></td><td><button className="table-action" onClick={()=>onEdit(b)}>Editar</button>{b.active&&<button className="table-action" onClick={()=>void onDeactivate(b)}>Desativar</button>}</td></tr>)}</tbody></table></div>}</div>}
function UsersPanel({data,currentUserId,onNew,onEdit,onToggle}:{data:Paged<User>|null;currentUserId?:string;onNew:()=>void;onEdit:(u:User)=>void;onToggle:(u:User)=>Promise<void>}){return <div className="data-page"><div className="page-toolbar"><div><span className="tag">SEGURANÇA</span><h2>Usuários</h2><p>Contas, funções e estado de acesso do tenant atual.</p></div><button className="primary" onClick={onNew}>+ Novo usuário</button></div>{!data?<div className="state-box">Carregando usuários…</div>:<div className="table-wrap"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Função</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.items.map(u=><tr key={u.id}><td><strong>{u.name}</strong>{u.id===currentUserId&&<small> · você</small>}</td><td>{u.email}</td><td><span className="status-pill">{u.role}</span></td><td><span className={`status-pill ${u.active?'active':''}`}>{u.active?'Ativo':'Inativo'}</span></td><td><button className="table-action" onClick={()=>onEdit(u)}>Editar</button>{u.role!=='owner'&&!(u.id===currentUserId&&u.active)&&<button className="table-action" onClick={()=>void onToggle(u)}>{u.active?'Desativar':'Ativar'}</button>}</td></tr>)}</tbody></table></div>}</div>}
function AccessPanel({api,role,onToast}:{api:ApiCall;role:string;onToast:(s:string)=>void}){const [permissions,setPermissions]=React.useState<any[]>([]);const [selected,setSelected]=React.useState(role);const [busy,setBusy]=React.useState(false);const load=React.useCallback(async()=>{try{const r=await api(`/api/v1/core/rbac/role-permissions/${selected}`);setPermissions(r.permissions??[]);}catch{setPermissions([]);}},[api,selected]);React.useEffect(()=>{void load()},[load]);async function change(permissionKey:string,effect:'allow'|'deny'){setBusy(true);try{await api('/api/v1/core/rbac/role-permissions',{method:'PUT',body:JSON.stringify({roleKey:selected,permissionKey,effect})});onToast('Permissão atualizada.');await load();}catch(e){onToast(errorMessage(e))}finally{setBusy(false)}}return <div className="data-page"><div className="page-toolbar"><div><span className="tag">CONTROLE DE ACESSO</span><h2>RBAC / acesso</h2><p>Visualize e altere permissões persistidas para cada função.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{['owner',...roles].map(r=><option key={r}>{r}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Permissão</th><th>Efeito</th><th>Ações</th></tr></thead><tbody>{permissions.length===0?<tr><td colSpan={3}>Nenhuma permissão persistida.</td></tr>:permissions.map((p:any)=><tr key={p.permissionKey}><td>{p.permissionKey}</td><td>{p.effect}</td><td><button disabled={busy} className="table-action" onClick={()=>void change(p.permissionKey,'allow')}>Permitir</button><button disabled={busy} className="table-action" onClick={()=>void change(p.permissionKey,'deny')}>Negar</button></td></tr>)}</tbody></table></div></div>}
function AuditPanel({data}:{data:Paged<Audit>|null}){return <div className="data-page"><div className="page-toolbar"><div><span className="tag">COMPLIANCE</span><h2>Auditoria</h2><p>Histórico append-only das ações administrativas do tenant.</p></div></div>{!data?<div className="state-box">Carregando auditoria…</div>:<div className="table-wrap"><table><thead><tr><th>Data</th><th>Ator</th><th>Ação</th><th>Recurso</th><th>ID</th></tr></thead><tbody>{data.items.map((a,i)=><tr key={a._id??i}><td>{formatDate(a.createdAt)}</td><td>{a.actorUserId}</td><td>{a.action}</td><td>{a.resource}</td><td>{a.resourceId??'—'}</td></tr>)}</tbody></table></div>}</div>}
function BranchModal({initial,onClose,onSave}:{initial:Branch|null;onClose:()=>void;onSave:(d:Record<string,unknown>)=>Promise<void>}){const [code,setCode]=React.useState(initial?.code??'');const [name,setName]=React.useState(initial?.name??'');const [legalName,setLegalName]=React.useState(initial?.legalName??'');const [document,setDocument]=React.useState(initial?.document??'');return <Modal title={initial?'Editar filial':'Nova filial'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();void onSave({code,name,legalName:legalName||undefined,document:document||undefined,active:initial?.active??true})}}><label>Código<input required value={code} onChange={e=>setCode(e.target.value)}/></label><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Razão social<input value={legalName} onChange={e=>setLegalName(e.target.value)}/></label><label>Documento<input value={document} onChange={e=>setDocument(e.target.value)}/></label><ModalActions onClose={onClose} submit={initial?'Salvar alterações':'Criar filial'}/></form></Modal>}
function UserModal({initial,onClose,onSave}:{initial:User|null;onClose:()=>void;onSave:(d:Record<string,unknown>)=>Promise<void>}){const [name,setName]=React.useState(initial?.name??'');const [email,setEmail]=React.useState(initial?.email??'');const [password,setPassword]=React.useState('');const [role,setRole]=React.useState(initial?.role??'user');return <Modal title={initial?'Editar usuário':'Novo usuário'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const d:Record<string,unknown>={name};if(!initial){d.email=email;d.password=password;d.role=role}else{if(password)d.password=password;d.role=role}void onSave(d)}}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label>{!initial&&<label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>{initial?'Nova senha (opcional)':'Senha'}<input required={!initial} type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="mínimo 10 caracteres"/></label><label>Função<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><ModalActions onClose={onClose} submit={initial?'Salvar alterações':'Criar usuário'}/></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="form-card"><button className="close" onClick={onClose} aria-label="Fechar">×</button><span className="tag">F1 / CORE</span><h2>{title}</h2>{children}</div></div>}
function ModalActions({onClose,submit}:{onClose:()=>void;submit:string}){return <div className="panel-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button type="submit" className="primary">{submit}</button></div>}
