import React from 'react';
import './F2MasterDataComplete.css';

type Api = <T = unknown>(path: string, options?: RequestInit) => Promise<T>;
type Row = Record<string, unknown> & { _id?: string; id?: string };
type Resource = { key: string; label: string; endpoint: string; title: string; core?: boolean };
const resources: Resource[] = [
  {key:'products',label:'Produtos',endpoint:'products',title:'Produtos'}, {key:'categories',label:'Categorias',endpoint:'categories',title:'Categorias'}, {key:'brands',label:'Marcas',endpoint:'brands',title:'Marcas'}, {key:'units',label:'Unidades',endpoint:'units',title:'Unidades de medida'}, {key:'price_lists',label:'Listas de preços',endpoint:'price-lists',title:'Listas de preços'}, {key:'prices',label:'Preços',endpoint:'prices',title:'Preços'}, {key:'parties',label:'Parceiros',endpoint:'parties',title:'Parceiros'}, {key:'addresses',label:'Endereços',endpoint:'addresses',title:'Endereços'}, {key:'contacts',label:'Contatos',endpoint:'contacts',title:'Pessoas e contatos'}, {key:'warehouses',label:'Armazéns',endpoint:'warehouses',title:'Armazéns'}, {key:'locations',label:'Estrutura física',endpoint:'warehouse-locations',title:'Estrutura física do armazém'}, {key:'classifications',label:'Classificações',endpoint:'classifications',title:'Classificações auxiliares'}, {key:'cost_centers',label:'Centros de custo',endpoint:'../core/cost_centers',title:'Centros de custo',core:true}, {key:'org_units',label:'Estrutura organizacional',endpoint:'../core/org_units',title:'Estrutura organizacional',core:true}, {key:'relationships',label:'Relacionamentos',endpoint:'relationships',title:'Relacionamentos'}, {key:'attachments',label:'Anexos',endpoint:'attachments',title:'Anexos e documentos'}
];
function idOf(row: Row){return String(row.id??row._id??'');}
function display(row: Row){for(const key of ['name','code','sku','fileName','relation','type'])if(row[key]!==undefined&&row[key]!==null)return String(row[key]);return idOf(row);}
function unwrap<T>(value:any):T{return (value?.items??value?.records??value?.data??value) as T;}
export function F2MasterDataComplete({api,onNavigateAdmin,onToast}:{api:Api;onNavigateAdmin:()=>void;onToast:(message:string)=>void}){
 const [resource,setResource]=React.useState(resources[0]); const [rows,setRows]=React.useState<Row[]>([]); const [selected,setSelected]=React.useState<Row|null>(null); const [json,setJson]=React.useState('{}'); const [query,setQuery]=React.useState(''); const [loading,setLoading]=React.useState(false); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState(''); const [tool,setTool]=React.useState<'none'|'search'|'integrity'|'io'>('none'); const [importEntity,setImportEntity]=React.useState('products'); const [importJson,setImportJson]=React.useState('[\n\n]'); const [health,setHealth]=React.useState<unknown>(null);
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const r=await api<any>(`/api/v1/master-data/f2/${resource.endpoint}?limit=100&offset=0`);const v=unwrap<Row[]>(r);setRows(Array.isArray(v)?v:[]);}catch(e){setRows([]);setError(e instanceof Error?e.message:'Falha ao carregar F2.');}finally{setLoading(false);}},[api,resource]);
 React.useEffect(()=>{setSelected(null);setJson('{}');if(tool==='none')void load();},[load,tool]);
 function select(row:Row){setSelected(row);const copy={...row};delete copy._id;setJson(JSON.stringify({...copy,id:idOf(row)},null,2));}
 async function save(){if(resource.core){onNavigateAdmin();return;}setBusy(true);setError('');try{const payload=JSON.parse(json);const id=selected?idOf(selected):'';await api(`/api/v1/master-data/f2/${resource.endpoint}${id?`/${encodeURIComponent(id)}`:''}`,{method:id?'PATCH':'POST',body:JSON.stringify(payload)});onToast(id?`${resource.title} atualizado.`:`${resource.title} criado.`);setSelected(null);setJson('{}');await load();}catch(e){setError(e instanceof Error?e.message:'JSON inválido ou operação recusada.');}finally{setBusy(false);}}
 async function remove(row:Row){if(resource.core){onNavigateAdmin();return;}const id=idOf(row);if(!id||!window.confirm('Desativar/excluir este registro?'))return;setBusy(true);setError('');try{await api(`/api/v1/master-data/f2/${resource.endpoint}/${encodeURIComponent(id)}`,{method:'DELETE'});onToast('Registro desativado.');setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao remover.');}finally{setBusy(false);}}
 async function runSearch(){setLoading(true);setError('');try{const r=await api<any>(`/api/v1/master-data/f2/search?q=${encodeURIComponent(query)}&limit=100`);const v=unwrap<Row[]>(r);setRows(Array.isArray(v)?v:[]);}catch(e){setError(e instanceof Error?e.message:'Falha na busca.');}finally{setLoading(false);}}
 async function runIntegrity(){setLoading(true);setError('');try{setHealth(await api('/api/v1/master-data/f2/integrity'));}catch(e){setError(e instanceof Error?e.message:'Falha na integridade.');}finally{setLoading(false);}}
 async function exportEntity(){setBusy(true);setError('');try{const r=await api<any>(`/api/v1/master-data/f2/bulk/export/${importEntity}`);const blob=new Blob([JSON.stringify(unwrap(r),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`kz-erp-f2-${importEntity}.json`;a.click();URL.revokeObjectURL(url);onToast('Exportação concluída.');}catch(e){setError(e instanceof Error?e.message:'Falha na exportação.');}finally{setBusy(false);}}
 async function importEntities(){setBusy(true);setError('');try{const payload=JSON.parse(importJson);if(!Array.isArray(payload))throw new Error('A importação deve ser um array JSON.');const r=await api<any>(`/api/v1/master-data/f2/bulk/import/${importEntity}`,{method:'POST',body:JSON.stringify(payload)});onToast(`Importação concluída: ${r?.inserted??r?.data?.inserted??0} registros.`);await load();}catch(e){setError(e instanceof Error?e.message:'Falha na importação.');}finally{setBusy(false);}}
 return <section className="f2-complete"><div className="f2-complete-head"><div><span className="eyebrow">F2 · DADOS MESTRES</span><h2>Cadastros completos</h2><p>Todos os cadastros F2 operam contra a API real, com tenant e permissões do usuário.</p></div><button className="secondary" onClick={()=>void load()} disabled={loading||busy}>Atualizar</button></div>
 <div className="f2-complete-tools"><button className={tool==='search'?'active':''} onClick={()=>setTool(tool==='search'?'none':'search')}>Busca global</button><button className={tool==='integrity'?'active':''} onClick={()=>{setTool('integrity');void runIntegrity();}}>Integridade</button><button className={tool==='io'?'active':''} onClick={()=>setTool(tool==='io'?'none':'io')}>Importar / exportar</button><button onClick={onNavigateAdmin}>Auditoria</button></div>
 {tool==='search'&&<div className="f2-tool"><div className="inline-form"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SKU, código, nome, parceiro…"/><button className="primary" onClick={()=>void runSearch()}>Buscar</button></div></div>}
 {tool==='integrity'&&<div className="f2-tool"><pre>{JSON.stringify(health,null,2)}</pre></div>}
 {tool==='io'&&<div className="f2-tool io-grid"><div><label>Entidade<select value={importEntity} onChange={e=>setImportEntity(e.target.value)}>{resources.filter(x=>!x.core).map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label><button className="secondary" onClick={()=>void exportEntity()} disabled={busy}>Exportar JSON</button></div><div><label>Importação JSON<textarea value={importJson} onChange={e=>setImportJson(e.target.value)}/></label><button className="primary" onClick={()=>void importEntities()} disabled={busy}>Importar</button></div></div>}
 {error&&<div className="f2-error">{error}</div>}
 <div className="f2-layout"><aside className="f2-menu">{resources.map(x=><button key={x.key} className={resource.key===x.key?'active':''} onClick={()=>{setTool('none');setResource(x)}}>{x.label}</button>)}</aside><div className="f2-content"><div className="f2-content-head"><div><small>{resource.core?'CORE':'F2'}</small><h3>{resource.title}</h3></div><button className="primary small" onClick={()=>{setSelected(null);setJson('{}')}} disabled={busy||resource.core}>{resource.core?'Abrir Administração':'Novo'}</button></div>{loading?<div className="state-box">Carregando…</div>:<div className="f2-table"><table><thead><tr><th>Registro</th><th>ID</th><th>Resumo</th><th>Ações</th></tr></thead><tbody>{rows.map(row=><tr key={idOf(row)}><td>{display(row)}</td><td><code>{idOf(row).slice(0,12)}</code></td><td>{row.active===false?'Inativo':'Ativo'}{row.kind?` · ${String(row.kind)}`:''}</td><td><button className="table-action" onClick={()=>select(row)}>Editar</button><button className="table-action" onClick={()=>void remove(row)} disabled={busy}>{resource.core?'Abrir':'Desativar'}</button></td></tr>)}{rows.length===0&&<tr><td colSpan={4}>Nenhum registro encontrado.</td></tr>}</tbody></table></div>}
 <div className="f2-editor"><div className="panel-head"><div><small>{selected?'EDIÇÃO':'CRIAÇÃO'}</small><h3>{resource.core?'Gerenciado pelo Core':selected?`Editar ${resource.title}`:`Novo ${resource.title}`}</h3></div></div><textarea value={json} onChange={e=>setJson(e.target.value)} disabled={resource.core} spellCheck={false}/><div className="form-actions"><button className="secondary" onClick={()=>setJson('{}')}>Limpar</button><button className="primary" onClick={()=>void save()} disabled={busy||resource.core}>{busy?'Salvando…':selected?'Salvar alterações':'Criar registro'}</button></div></div></div></div>
 <div className="f2-footnote">Centros de custo e estrutura organizacional já pertencem ao Core e continuam acessíveis pelo mesmo catálogo F2. A auditoria permanece no módulo de Administração.</div></section>;
}
