import React from 'react';
import './F2MasterDataPro.css';

type Api=<T=unknown>(path:string,options?:RequestInit)=>Promise<T>;
type Row={ [key:string]: any; _id?:string; id?:string; searchType?:string };
type Field={key:string;label:string;type?:'text'|'number'|'date'|'email'|'textarea'|'select'|'checkbox'|'roles'|'lookup';required?:boolean;full?:boolean;options?:string[];placeholder?:string;lookup?:string};
type Resource={key:string;label:string;title:string;group:string;path:string;fields:Field[]};
type LookupOption={id:string;label:string};

const relations=['related_to','contains','belongs_to','replaces','depends_on','references','derived_from','associated_with'];
const relationLabels:Record<string,string>={related_to:'Relacionado a',contains:'Contém',belongs_to:'Pertence a',replaces:'Substitui',depends_on:'Depende de',references:'Referencia',derived_from:'Derivado de',associated_with:'Associado a'};

const resources:Resource[]=[
 {key:'products',label:'Produtos',title:'Produtos',group:'Catálogo',path:'/api/v1/master-data/products',fields:[{key:'sku',label:'SKU',required:true},{key:'name',label:'Nome',required:true},{key:'unit',label:'Unidade',type:'lookup',lookup:'units',required:true},{key:'price',label:'Preço',type:'number',required:true},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'categories',label:'Categorias',title:'Categorias de produtos',group:'Catálogo',path:'/api/v1/master-data/f2/categories',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'parentId',label:'Categoria pai',type:'lookup',lookup:'categories'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'brands',label:'Marcas',title:'Marcas',group:'Catálogo',path:'/api/v1/master-data/f2/brands',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'units',label:'Unidades',title:'Unidades de medida',group:'Catálogo',path:'/api/v1/master-data/units',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'symbol',label:'Símbolo',required:true},{key:'kind',label:'Tipo',type:'select',required:true,options:['unit','weight','volume','length','area','time','other']},{key:'decimalPlaces',label:'Casas decimais',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'price_lists',label:'Listas de preços',title:'Listas de preços',group:'Comercial',path:'/api/v1/master-data/price-lists',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'currency',label:'Moeda',required:true,placeholder:'BRL'},{key:'validFrom',label:'Vigência inicial',type:'date'},{key:'validUntil',label:'Vigência final',type:'date'},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'prices',label:'Preços',title:'Preços',group:'Comercial',path:'/api/v1/master-data/prices',fields:[{key:'priceListId',label:'Lista de preços',type:'lookup',lookup:'price_lists',required:true},{key:'productId',label:'Produto',type:'lookup',lookup:'products',required:true},{key:'amount',label:'Valor',type:'number',required:true},{key:'minQuantity',label:'Quantidade mínima',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'parties',label:'Parceiros',title:'Parceiros',group:'Relacionamentos',path:'/api/v1/master-data/parties',fields:[{key:'code',label:'Código',required:true},{key:'kind',label:'Tipo',type:'select',required:true,options:['person','company']},{key:'name',label:'Nome / razão social',required:true},{key:'legalName',label:'Nome legal'},{key:'document',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Telefone'},{key:'roles',label:'Papéis',type:'roles',required:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'addresses',label:'Endereços',title:'Endereços',group:'Relacionamentos',path:'/api/v1/master-data/addresses',fields:[{key:'partyId',label:'Parceiro',type:'lookup',lookup:'parties',required:true},{key:'code',label:'Código',required:true},{key:'type',label:'Tipo',type:'select',required:true,options:['billing','shipping','commercial','residential','other']},{key:'label',label:'Rótulo'},{key:'recipientName',label:'Destinatário'},{key:'postalCode',label:'CEP',required:true},{key:'street',label:'Logradouro',required:true},{key:'number',label:'Número',required:true},{key:'complement',label:'Complemento'},{key:'district',label:'Bairro',required:true},{key:'city',label:'Cidade',required:true},{key:'state',label:'Estado',required:true},{key:'country',label:'País',placeholder:'Brasil'},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'contacts',label:'Contatos',title:'Pessoas e contatos',group:'Relacionamentos',path:'/api/v1/master-data/f2/contacts',fields:[{key:'partyId',label:'Parceiro',type:'lookup',lookup:'parties',required:true},{key:'name',label:'Nome',required:true},{key:'role',label:'Função'},{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Telefone'},{key:'mobile',label:'Celular'},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'warehouses',label:'Armazéns',title:'Armazéns',group:'Logística',path:'/api/v1/master-data/warehouses',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'locations',label:'Estrutura física',title:'Estrutura física do armazém',group:'Logística',path:'/api/v1/master-data/f2/warehouse-locations',fields:[{key:'warehouseId',label:'Armazém',type:'lookup',lookup:'warehouses',required:true},{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'kind',label:'Nível',type:'select',required:true,options:['zone','aisle','rack','shelf','bin']},{key:'parentId',label:'Localização pai',type:'lookup',lookup:'locations'},{key:'capacity',label:'Capacidade',type:'number'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'classifications',label:'Classificações',title:'Classificações auxiliares',group:'Organização',path:'/api/v1/master-data/f2/classifications',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo',required:true},{key:'parentId',label:'Classificação pai',type:'lookup',lookup:'classifications'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'cost_centers',label:'Centros de custo',title:'Centros de custo',group:'Organização',path:'/api/v1/master-data/f2/cost-centers',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'parentId',label:'Centro pai',type:'lookup',lookup:'cost_centers'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'org_units',label:'Estrutura organizacional',title:'Estrutura organizacional',group:'Organização',path:'/api/v1/master-data/f2/org-units',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo'},{key:'parentId',label:'Unidade pai',type:'lookup',lookup:'org_units'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
 {key:'relationships',label:'Relacionamentos',title:'Relacionamentos',group:'Governança',path:'/api/v1/master-data/f2/relationships',fields:[{key:'sourceType',label:'Tipo da origem',type:'select',required:true,options:resources.filter(x=>!['relationships','attachments'].includes(x.key)).map(x=>x.key)},{key:'sourceId',label:'Registro de origem',type:'lookup',required:true},{key:'relation',label:'Tipo de relação',type:'select',required:true,options:relations},{key:'targetType',label:'Tipo do destino',type:'select',required:true,options:resources.filter(x=>!['relationships','attachments'].includes(x.key)).map(x=>x.key)},{key:'targetId',label:'Registro de destino',type:'lookup',required:true}]},
 {key:'attachments',label:'Anexos',title:'Anexos e documentos',group:'Governança',path:'/api/v1/master-data/f2/attachments',fields:[]}
];
const lookupPaths:Record<string,string>={products:'/products',parties:'/parties',addresses:'/addresses',units:'/units',price_lists:'/price-lists',prices:'/prices',warehouses:'/warehouses',categories:'/f2/categories',brands:'/f2/brands',contacts:'/f2/contacts',locations:'/f2/warehouse-locations',classifications:'/f2/classifications',cost_centers:'/f2/cost-centers',org_units:'/f2/org-units'};
function idOf(r:Row){return String(r.id??r._id??'')}
function unwrap(v:any){const x=v?.data??v;return x?.items??x?.records??x}
function display(r:Row){return String(r.name??r.code??r.sku??r.fileName??r.symbol??r.relation??idOf(r))}
function groupResources(){return resources.reduce<Record<string,Resource[]>>((acc,r)=>{(acc[r.group]??=[]).push(r);return acc},{})}
function resourceFor(type?:string){if(!type)return undefined;const n=String(type).replace(/^f2_/,'');return resources.find(x=>x.key===n)||resources.find(x=>x.key.replace(/_/g,'')===n.replace(/_/g,''))}
function resourceLabel(key:string){return resources.find(x=>x.key===key)?.label??key}

export function F2MasterDataProfessional({api,onToast}:{api:Api;onToast:(message:string)=>void}){
 const [resource,setResource]=React.useState<Resource>(resources[0]);const [rows,setRows]=React.useState<Row[]>([]);const [selected,setSelected]=React.useState<Row|null>(null);const [form,setForm]=React.useState<Row>({});const [search,setSearch]=React.useState('');const [searchMode,setSearchMode]=React.useState(false);const [loading,setLoading]=React.useState(false);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const [notice,setNotice]=React.useState('');const [tool,setTool]=React.useState<'none'|'integrity'|'audit'|'io'>('none');const [toolData,setToolData]=React.useState<any>(null);const [importEntity,setImportEntity]=React.useState(resources[0].key);const [importJson,setImportJson]=React.useState('[\n  \n]');const [file,setFile]=React.useState<File|null>(null);const [lookups,setLookups]=React.useState<Record<string,LookupOption[]>>({});
 const groups=React.useMemo(groupResources,[]);
 const loadLookup=React.useCallback(async(key:string)=>{if(!key||lookups[key])return lookups[key]??[];const path=lookupPaths[key];if(!path)return [];try{const data=unwrap(await api(`/api/v1/master-data${path}?limit=1000&offset=0`));const options=(Array.isArray(data)?data:[]).map((x:any)=>({id:idOf(x),label:display(x)})).filter((x:LookupOption)=>x.id);setLookups(v=>({...v,[key]:options}));return options}catch{return []}},[api,lookups]);
 React.useEffect(()=>{const keys=resource.fields.map(f=>f.lookup).filter(Boolean) as string[];if(resource.key==='relationships'){if(form.sourceType)keys.push(form.sourceType);if(form.targetType)keys.push(form.targetType)}keys.forEach(k=>void loadLookup(k))},[resource,form.sourceType,form.targetType,loadLookup]);
 const load=React.useCallback(async()=>{if(searchMode||resource.key==='attachments')return;setLoading(true);setError('');try{if(resource.key==='addresses'){const parties=unwrap(await api('/api/v1/master-data/parties?limit=1000&offset=0')) as Row[];const data=(await Promise.all((parties||[]).map(async p=>{try{return unwrap(await api(`/api/v1/master-data/parties/${encodeURIComponent(idOf(p))}/addresses?limit=1000&offset=0`)) as Row[]}catch{return []}}))).flat();setRows(Array.isArray(data)?data:[])}else if(resource.key==='prices'){const lists=unwrap(await api('/api/v1/master-data/price-lists?limit=1000&offset=0')) as Row[];const data=(await Promise.all((lists||[]).map(async p=>{try{return unwrap(await api(`/api/v1/master-data/price-lists/${encodeURIComponent(idOf(p))}/prices?limit=1000&offset=0`)) as Row[]}catch{return []}}))).flat();setRows(Array.isArray(data)?data:[])}else{const data=unwrap(await api(`${resource.path}?limit=100&offset=0`));setRows(Array.isArray(data)?data:[])}}catch(e){setRows([]);setError(e instanceof Error?e.message:'Falha ao carregar o cadastro.')}finally{setLoading(false)}},[api,resource,searchMode]);
 React.useEffect(()=>{if(tool==='none')void load()},[load,tool]);
 React.useEffect(()=>{if(resource.key==='attachments')void (async()=>{setLoading(true);try{const data=unwrap(await api('/api/v1/master-data/f2/attachments?limit=100&offset=0'));setRows(Array.isArray(data)?data:[])}catch(e){setRows([]);setError(e instanceof Error?e.message:'Falha ao carregar os anexos.')}finally{setLoading(false)}})()},[api,resource,tool]);
 function fresh(){const x:Row={};for(const f of resource.fields)if(f.type==='checkbox')x[f.key]=true;setSelected(null);setForm(x);setError('');setNotice('');setFile(null)}
 function edit(row:Row){const target=resourceFor(row.searchType)||resource;const x:Row={...row,id:idOf(row)};delete x._id;delete x.searchType;for(const f of target.fields)if(f.type==='roles')x[f.key]=Array.isArray(x[f.key])?x[f.key].join(', '):String(x[f.key]??'');setResource(target);setSelected(row);setForm(x);setError('');setNotice('');window.scrollTo({top:0,behavior:'smooth'})}
 function setField(key:string,value:any){setForm(v=>({...v,[key]:value}))}
 function payload(){const p:Row={...form};delete p.id;delete p._id;delete p.searchType;for(const f of resource.fields){if(f.type==='roles')p[f.key]=String(p[f.key]??'').split(',').map((x:string)=>x.trim()).filter(Boolean);if(f.type==='number'&&p[f.key]!==''&&p[f.key]!=null)p[f.key]=Number(p[f.key]);}return p}
 async function save(){setBusy(true);setError('');setNotice('');try{const p=payload();for(const f of resource.fields)if(f.required&&(p[f.key]==null||p[f.key]===''||(Array.isArray(p[f.key])&&!p[f.key].length)))throw new Error(`${f.label} é obrigatório.`);if(resource.key==='attachments')throw new Error('Use o painel de anexos para enviar arquivos.');let endpoint=resource.path;if(resource.key==='addresses'){if(selected)endpoint=`/api/v1/master-data/addresses/${encodeURIComponent(idOf(selected))}`;else{const parent=String(p.partyId);delete p.partyId;endpoint=`/api/v1/master-data/parties/${encodeURIComponent(parent)}/addresses`}}else if(resource.key==='prices'){if(selected)endpoint=`/api/v1/master-data/prices/${encodeURIComponent(idOf(selected))}`;else{const parent=String(p.priceListId);delete p.priceListId;endpoint=`/api/v1/master-data/price-lists/${encodeURIComponent(parent)}/prices`}}await api(endpoint,{method:selected?'PATCH':'POST',body:JSON.stringify(p)});onToast(selected?'Registro atualizado.':'Registro criado.');setNotice(selected?'Alterações salvas com sucesso.':'Registro criado com sucesso.');fresh();await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o registro.')}finally{setBusy(false)}}
 async function remove(row:Row){const target=resourceFor(row.searchType)||resource;const id=idOf(row);if(!id||!window.confirm(`Desativar ${display(row)}?`))return;setBusy(true);setError('');try{let endpoint=`${target.path}/${encodeURIComponent(id)}`;if(target.key==='addresses'||target.key==='prices')endpoint=`/api/v1/master-data/${target.key}/${encodeURIComponent(id)}`;await api(endpoint,{method:'DELETE'});onToast('Registro desativado.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao desativar.')}finally{setBusy(false)}}
 async function doSearch(){const q=search.trim();if(q.length<2){setError('Digite pelo menos 2 caracteres para pesquisar.');return}setLoading(true);setError('');setSearchMode(true);try{const v=unwrap(await api(`/api/v1/master-data/f2/search?q=${encodeURIComponent(q)}`));const result:Record<string,any>=v?.results??{};setRows(Object.entries(result).flatMap(([type,items])=>(Array.isArray(items)?items:[]).map((x:any)=>({...x,searchType:type}))));}catch(e){setError(e instanceof Error?e.message:'Falha na pesquisa.')}finally{setLoading(false)}}
 function clearSearch(){setSearch('');setSearchMode(false);setError('')}
 async function toolRun(kind:'integrity'|'audit'|'io'){setTool(kind);setError('');if(kind==='io'){setToolData(null);return}try{setToolData(await api(`/api/v1/master-data/f2/${kind}`))}catch(e){setToolData(null);setError(e instanceof Error?e.message:'Não foi possível carregar esta ferramenta.')}}
 async function importData(){setBusy(true);setError('');try{const parsed=JSON.parse(importJson);if(!Array.isArray(parsed))throw new Error('A importação deve ser uma lista de registros.');const result=await api(`/api/v1/master-data/f2/bulk/import/${encodeURIComponent(importEntity)}`,{method:'POST',body:JSON.stringify(parsed)});setNotice('Importação concluída com sucesso.');setToolData(result);await load()}catch(e){setError(e instanceof Error?e.message:'JSON inválido ou importação recusada.')}finally{setBusy(false)}}
 async function exportData(){setBusy(true);try{const data=await api(`/api/v1/master-data/f2/bulk/export/${encodeURIComponent(resource.key)}`);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${resource.key}-export.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);onToast('Exportação concluída.')}catch(e){setError(e instanceof Error?e.message:'Falha na exportação.')}finally{setBusy(false)}}
 async function uploadAttachment(){if(!file){setError('Escolha um arquivo primeiro.');return}const entity=String(form.entityId??'');const entityType=String(form.entityType??'');if(!entity||!entityType){setError('Selecione a entidade e o registro antes do envio.');return}setBusy(true);setError('');try{await api('/api/v1/master-data/f2/attachments/upload',{method:'POST',body:file,headers:{'x-f2-entity-type':entityType,'x-f2-entity-id':entity,'x-f2-file-name':file.name,'x-f2-mime-type':file.type||'application/octet-stream'}});onToast('Arquivo enviado.');setNotice('Anexo enviado com sucesso.');setFile(null);const data=unwrap(await api('/api/v1/master-data/f2/attachments?limit=100&offset=0'));setRows(Array.isArray(data)?data:[])}catch(e){setError(e instanceof Error?e.message:'Falha ao enviar o arquivo.')}finally{setBusy(false)}}
 async function downloadAttachment(row:Row){const id=idOf(row);if(!id)return;try{const blob=await api<Blob>(`/api/v1/master-data/f2/attachments/${encodeURIComponent(id)}/download`);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=String(row.fileName??`anexo-${id}`);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'Falha ao baixar o arquivo.')}}
 function lookupLabel(key:string,id:any){return (lookups[key]??[]).find(x=>x.id===String(id))?.label??String(id??'—')}
 function renderField(field:Field){const value=form[field.key]??'';if(field.type==='checkbox')return <label className="f2-pro-check"><input type="checkbox" checked={Boolean(value)} onChange={e=>setField(field.key,e.target.checked)}/><span>{field.label}</span></label>;if(field.type==='lookup'){const lookupKey=field.lookup||(field.key==='sourceId'?String(form.sourceType??''):field.key==='targetId'?String(form.targetType??''):''),options=lookups[lookupKey]??[];return <label className={field.full?'f2-pro-field f2-pro-field-full':'f2-pro-field'}><span>{field.label}{field.required?' *':''}</span><select value={String(value)} onChange={e=>setField(field.key,e.target.value)} disabled={!lookupKey||!options.length}><option value="">{lookupKey?'Selecione…':'Selecione o tipo primeiro…'}</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>{value&&lookupKey?<small className="f2-pro-selected-hint">Selecionado: {lookupLabel(lookupKey,value)}</small>:null}</label>};if(field.type==='select')return <label className={field.full?'f2-pro-field f2-pro-field-full':'f2-pro-field'}><span>{field.label}{field.required?' *':''}</span><select value={String(value)} onChange={e=>setField(field.key,e.target.value)}><option value="">Selecione…</option>{(field.options??[]).map(o=><option key={o} value={o}>{relationLabels[o]??resourceLabel(o)}</option>)}</select></label>;if(field.type==='roles')return <label className="f2-pro-field f2-pro-field-full"><span>{field.label}{field.required?' *':''}</span><input value={String(value)} onChange={e=>setField(field.key,e.target.value)} placeholder="Ex.: cliente, fornecedor"/><small className="f2-pro-selected-hint">Separe os papéis por vírgula.</small></label>;if(field.type==='textarea')return <label className="f2-pro-field f2-pro-field-full"><span>{field.label}{field.required?' *':''}</span><textarea value={String(value)} onChange={e=>setField(field.key,e.target.value)} placeholder={field.placeholder} rows={4}/></label>;return <label className={field.full?'f2-pro-field f2-pro-field-full':'f2-pro-field'}><span>{field.label}{field.required?' *':''}</span><input type={field.type==='number'?'number':field.type==='date'?'date':field.type==='email'?'email':'text'} value={String(value)} onChange={e=>setField(field.key,e.target.value)} placeholder={field.placeholder}/></label>}

 return <section className="f2-pro"><header className="f2-pro-head"><div><div className="f2-pro-eyebrow">F2 · DADOS FUNDAMENTAIS</div><h1>Cadastros</h1><p>Central de dados mestre com formulários orientados ao negócio.</p></div><div className="f2-pro-head-actions"><button type="button" onClick={()=>{fresh();setTool('none')}}>＋ Novo</button></div></header>
  <div className="f2-pro-toolbar"><div className="f2-pro-search"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void doSearch()}} placeholder="Pesquisar por nome, código, SKU, documento ou parceiro…" aria-label="Pesquisar cadastros"/><button type="button" onClick={()=>void doSearch()}>Pesquisar</button>{searchMode&&<button type="button" className="secondary" onClick={clearSearch}>Limpar</button>}</div></div>
  <div className="f2-pro-layout"><aside className="f2-pro-nav">{Object.entries(groups).map(([group,list])=><div className="f2-pro-nav-group" key={group}><div className="f2-pro-nav-title">{group}</div>{list.map(x=><button type="button" key={x.key} className={resource.key===x.key?'active':''} onClick={()=>{setResource(x);setSearchMode(false);setTool('none');fresh()}}>{x.label}</button>)}</div>)}</aside>
   <main className="f2-pro-main">{error&&<div className="f2-pro-alert error">{error}</div>}{notice&&<div className="f2-pro-alert success">{notice}</div>}
    <div className="f2-pro-card"><div className="f2-pro-card-head"><div><h2>{resource.title}</h2><small>{searchMode?`${rows.length} resultado(s) para “${search}”`:`${rows.length} registro(s)`}</small></div><div className="f2-pro-card-actions"><button type="button" className="secondary" onClick={()=>void exportData()} disabled={busy||resource.key==='attachments'}>Exportar</button><button type="button" className="secondary" onClick={()=>void toolRun('integrity')}>Integridade</button><button type="button" className="secondary" onClick={()=>void toolRun('audit')}>Auditoria</button><button type="button" className="secondary" onClick={()=>void toolRun('io')}>Importar</button></div></div>
     {loading?<div className="f2-pro-empty">Carregando…</div>:resource.key==='attachments'?<AttachmentPanel api={api} form={form} setField={setField} file={file} setFile={setFile} upload={uploadAttachment} busy={busy} rows={rows} download={downloadAttachment}/>:<div className="f2-pro-table"><table><thead><tr><th>Registro</th><th>Identificação</th><th>Estado</th><th className="actions-col">Ações</th></tr></thead><tbody>{rows.map((row,i)=><tr key={`${idOf(row)}-${i}`}><td><strong>{display(row)}</strong></td><td>{row.code??row.sku??idOf(row)}</td><td>{row.active===false?'Inativo':'Ativo'}</td><td className="f2-pro-actions"><button type="button" onClick={()=>edit(row)}>Editar</button><button type="button" className="danger" onClick={()=>void remove(row)}>Desativar</button></td></tr>)}</tbody></table>{!rows.length&&<div className="f2-pro-empty">Nenhum registro encontrado.</div>}</div>}
    </div>
    {tool!=='none'&&<div className="f2-pro-card f2-pro-tool-panel"><div className="f2-pro-card-head"><div><h2>{tool==='integrity'?'Integridade':tool==='audit'?'Auditoria':'Importação'}</h2></div><button type="button" className="secondary" onClick={()=>setTool('none')}>Fechar</button></div>{tool==='io'?<div className="f2-pro-io"><label className="f2-pro-field"><span>Cadastro</span><select value={importEntity} onChange={e=>setImportEntity(e.target.value)}>{resources.filter(x=>x.key!=='attachments').map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label><label className="f2-pro-field f2-pro-field-full"><span>Registros em JSON</span><textarea value={importJson} onChange={e=>setImportJson(e.target.value)} rows={10}/></label><button type="button" onClick={()=>void importData()} disabled={busy}>Executar importação</button></div>:<pre>{JSON.stringify(toolData,null,2)}</pre>}</div>}
    <div className="f2-pro-card f2-pro-form-card"><div className="f2-pro-card-head"><div><h2>{selected?'Editar registro':'Novo registro'}</h2><small>Preencha somente os dados necessários ao processo.</small></div>{selected&&<button type="button" className="secondary" onClick={fresh}>Cancelar edição</button>}</div>{resource.key==='attachments'?<p className="f2-pro-helper">Os anexos são enviados pelo painel acima. O armazenamento, checksum e demais dados técnicos são gerenciados automaticamente.</p>:<><div className="f2-pro-form-grid">{resource.fields.map(f=><React.Fragment key={f.key}>{renderField(f)}</React.Fragment>)}</div><div className="f2-pro-form-actions"><button type="button" onClick={()=>void save()} disabled={busy}>{busy?'Salvando…':selected?'Salvar alterações':'Criar registro'}</button></div></>}</div>
   </main></div></section>
}

function AttachmentPanel({api,form,setField,file,setFile,upload,busy,rows,download}:{api:Api;form:Row;setField:(k:string,v:any)=>void;file:File|null;setFile:(f:File|null)=>void;upload:()=>Promise<void>;busy:boolean;rows:Row[];download:(r:Row)=>Promise<void>}){const entities=resources.filter(x=>!['attachments','relationships'].includes(x.key));const [entityRows,setEntityRows]=React.useState<Row[]>([]);const [entityLoading,setEntityLoading]=React.useState(false);React.useEffect(()=>{const type=String(form.entityType??'');if(!type){setEntityRows([]);return}const path=lookupPaths[type];if(!path){setEntityRows([]);return}setEntityLoading(true);void api(`/api/v1/master-data${path}?limit=1000&offset=0`).then(v=>setEntityRows(Array.isArray(unwrap(v))?unwrap(v):[])).catch(()=>setEntityRows([])).finally(()=>setEntityLoading(false))},[api,form.entityType]);return <div className="f2-pro-attachments"><div className="f2-pro-form-grid"><label className="f2-pro-field"><span>Tipo de entidade *</span><select value={String(form.entityType??'')} onChange={e=>{setField('entityType',e.target.value);setField('entityId','')}}><option value="">Selecione…</option>{entities.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label><label className="f2-pro-field"><span>Registro *</span><select value={String(form.entityId??'')} onChange={e=>setField('entityId',e.target.value)} disabled={!form.entityType||entityLoading}><option value="">{entityLoading?'Carregando…':'Selecione um registro…'}</option>{entityRows.map(x=><option key={idOf(x)} value={idOf(x)}>{display(x)}</option>)}</select></label><label className="f2-pro-field f2-pro-field-full"><span>Arquivo *</span><input type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/>{file&&<small className="f2-pro-selected-hint">Selecionado: {file.name} · {Math.ceil(file.size/1024)} KB</small>}</label></div><button type="button" onClick={()=>void upload()} disabled={busy||!file}>{busy?'Enviando…':'Enviar arquivo'}</button><div className="f2-pro-attachment-list">{rows.map((r,i)=><div className="f2-pro-attachment" key={`${idOf(r)}-${i}`}><div><strong>{r.fileName??'Arquivo'}</strong><small>{r.mimeType??'Arquivo'}{r.size?` · ${r.size} bytes`:''}</small></div><button type="button" className="secondary" onClick={()=>void download(r)}>Baixar</button></div>)}{!rows.length&&<div className="f2-pro-empty">Nenhum anexo encontrado.</div>}</div></div>}
