import React from 'react';
import { F2MasterDataProfessional } from './F2MasterDataProfessional';
type Session={accessToken:string;refreshToken:string;user?:{role?:string}};
const API=(import.meta.env.VITE_API_URL??'https://kz-erp.onrender.com').replace(/\/$/,'');
function isBinaryBody(body:BodyInit|undefined){return body instanceof Blob||body instanceof ArrayBuffer||body instanceof FormData}
const attachmentEntityTypes:Record<string,string>={products:'product',parties:'party',addresses:'address',units:'unit',price_lists:'price_list',prices:'price',warehouses:'warehouse',categories:'category',brands:'brand',contacts:'contact',locations:'location',classifications:'classification',cost_centers:'cost_center',org_units:'org_unit',relationships:'relationship'};
export function F2MasterData({session,onToast}:{session:Session;onToast:(message:string)=>void}){
 const api=React.useCallback(async<T=unknown>(path:string,options:RequestInit={})=>{const headers=new Headers(options.headers);headers.set('Accept','application/json');if(options.body!==undefined&&!isBinaryBody(options.body as BodyInit))headers.set('Content-Type','application/json');headers.set('Authorization',`Bearer ${session.accessToken}`);if(path==='/api/v1/master-data/f2/attachments/upload'){const current=headers.get('x-f2-entity-type');if(current&&attachmentEntityTypes[current])headers.set('x-f2-entity-type',attachmentEntityTypes[current]);}let requestPath=path;if(options.method==='DELETE'&&/^\/api\/v1\/master-data\/f2\/attachments\/[^/]+$/.test(path))requestPath=`${path}/file`;const response=await fetch(`${API}${requestPath}`,{...options,headers});const contentType=(response.headers.get('content-type')??'').toLowerCase();if(!response.ok){const body=await response.json().catch(()=>null) as any;throw new Error(body?.error?.message??body?.error?.code??`HTTP ${response.status}`)}if(!contentType.includes('application/json'))return (await response.blob()) as T;const body=await response.json().catch(()=>null) as any;return (body?.data??body) as T},[session.accessToken]);
 return <F2MasterDataProfessional api={api} onToast={onToast}/>;
}
