import React from 'react';
import './F2MasterDataPro.css';

type Api=<T=unknown>(path:string,options?:RequestInit)=>Promise<T>;
type Row=Record<string,any>&{_id?:string;id?:string};
type Field={key:string;label:string;type?:'text'|'number'|'date'|'email'|'textarea'|'select'|'checkbox'|'roles';required?:boolean;full?:boolean;options?:string[];placeholder?:string};
type Resource={key:string;label:string;title:string;group:string;core?:boolean;fields:Field[];path:string};
const relationTypes=['related_to','contains','belongs_to','replaces','depends_on','references','derived_from','associated_with'];
const resources:Resource[]=[
{key:'products',label:'Produtos',title:'Produtos',group:'Catálogo',path:'/api/v1/master-data/products',fields:[{key:'sku',label:'SKU',required:true},{key:'name',label:'Nome',required:true},{key:'unit',label:'Unidade',required:true},{key:'price',label:'Preço',type:'number',required:true},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'categories',label:'Categorias',title:'Categorias de produtos',group:'Catálogo',path:'/api/v1/master-data/f2/categories',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'parentId',label:'Categoria pai'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'brands',label:'Marcas',title:'Marcas',group:'Catálogo',path:'/api/v1/master-data/f2/brands',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'units',label:'Unidades',title:'Unidades de medida',group:'Catálogo',path:'/api/v1/master-data/units',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'symbol',label:'Símbolo',required:true},{key:'kind',label:'Tipo',type:'select',required:true,options:['unit','weight','volume','length','area','time','other']},{key:'decimalPlaces',label:'Casas decimais',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'price_lists',label:'Listas de preços',title:'Listas de preços',group:'Comercial',path:'/api/v1/master-data/price-lists',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'currency',label:'Moeda',required:true,placeholder:'BRL'},{key:'validFrom',label:'Vigência inicial',type:'date'},{key:'validUntil',label:'Vigência final',type:'date'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'prices',label:'Preços',title:'Preços',group:'Comercial',path:'/api/v1/master-data/prices',fields:[{key:'priceListId',label:'Lista de preços (ID)',required:true},{key:'productId',label:'Produto (ID)',required:true},{key:'amount',label:'Valor',type:'number',required:true},{key:'minQuantity',label:'Quantidade mínima',type:'number'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'parties',label:'Parceiros',title:'Parceiros',group:'Relacionamentos',path:'/api/v1/master-data/parties',fields:[{key:'code',label:'Código',required:true},{key:'kind',label:'Tipo',type:'select',required:true,options:['person','company']},{key:'name',label:'Nome / razão social',required:true},{key:'legalName',label:'Nome legal'},{key:'document',label:'Documento'},{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Telefone'},{key:'roles',label:'Papéis',type:'roles',required:true,placeholder:'customer, supplier'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'addresses',label:'Endereços',title:'Endereços',group:'Relacionamentos',path:'/api/v1/master-data/addresses',fields:[{key:'partyId',label:'Parceiro (ID)',required:true},{key:'code',label:'Código',required:true},{key:'type',label:'Tipo',type:'select',required:true,options:['billing','shipping','commercial','residential','other']},{key:'label',label:'Rótulo'},{key:'recipientName',label:'Destinatário'},{key:'postalCode',label:'CEP',required:true},{key:'street',label:'Logradouro',required:true},{key:'number',label:'Número',required:true},{key:'complement',label:'Complemento'},{key:'district',label:'Bairro',required:true},{key:'city',label:'Cidade',required:true},{key:'state',label:'Estado',required:true},{key:'country',label:'País'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'contacts',label:'Contatos',title:'Pessoas e contatos',group:'Relacionamentos',path:'/api/v1/master-data/f2/contacts',fields:[{key:'partyId',label:'Parceiro (ID)',required:true},{key:'name',label:'Nome',required:true},{key:'role',label:'Função'},{key:'email',label:'E-mail',type:'email'},{key:'phone',label:'Telefone'},{key:'mobile',label:'Celular'},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'warehouses',label:'Armazéns',title:'Armazéns',group:'Logística',path:'/api/v1/master-data/warehouses',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'locations',label:'Estrutura física',title:'Estrutura física do armazém',group:'Logística',path:'/api/v1/master-data/f2/warehouse-locations',fields:[{key:'warehouseId',label:'Armazém (ID)',required:true},{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'kind',label:'Nível',type:'select',required:true,options:['zone','aisle','rack','shelf','bin']},{key:'parentId',label:'Localização pai'},{key:'capacity',label:'Capacidade',type:'number'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'classifications',label:'Classificações',title:'Classificações auxiliares',group:'Organização',path:'/api/v1/master-data/f2/classifications',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo',required:true},{key:'parentId',label:'Classificação pai'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'cost_centers',label:'Centros de custo',title:'Centros de custo',group:'Organização',core:true,path:'/api/v1/master-data/f2/cost-centers',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'parentId',label:'Centro pai'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'org_units',label:'Estrutura organizacional',title:'Estrutura organizacional',group:'Organização',core:true,path:'/api/v1/master-data/f2/org-units',fields:[{key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo'},{key:'parentId',label:'Unidade pai'},{key:'description',label:'Descrição',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox'}]},
{key:'relationships',label:'Relacionamentos',title:'Relacionamentos',group:'Governança',path:'/api/v1/master-data/f2/relationships',fields:[{key:'sourceType',label:'Origem · tipo',required:true},{key:'sourceId',label:'Origem · ID',required:true},{key:'relation',label:'Relação',type:'select',required:true,options:relationTypes},{key:'targetType',label:'Destino · tipo',required:true},{key:'targetId',label:'Destino · ID',required:true},{key:'metadata',label:'Metadados JSON',type:'textarea',full:true}]},
{key:'attachments',label:'Anexos',title:'Anexos e documentos',group:'Governança',path:'/api/v1/master-data/f2/attachments',fields:[{key:'entityType',label:'Tipo da entidade',required:true},{key:'entityId',label:'Entidade (ID)',required:true},{key:'fileName',label:'Arquivo',required:true},{key:'mimeType',label:'MIME type',required:true},{key:'size',label:'Tamanho (bytes)',type:'number',required:true},{key:'storageKey',label:'Chave de armazenamento',required:true},{key:'storageManaged',label:'Gerenciado pelo armazenamento',type:'checkbox'},{key:'checksum',label:'Checksum'},{key:'metadata',label:'Metadados JSON',type:'textarea',full:true}]}
];
function idOf(r:Row){return String(r.id??r._id??'')}
function unwrap<T=any>(v:any):T{const value=v?.data??v;return (value?.items??value?.records??value) as T}
function formatValue(v:any){if(v===true)return 'Sim';if(v===false)return 'Não';if(v==null||v==='')return '—';if(Array.isArray(v))return v.join(', ');if(typeof v==='object')return '[objeto]';return String(v)}
function display(r:Row){return String(r.name??r.code??r.sku??r.fileName??r.relation??r.type??idOf(r))}
function inputValue(v:any,field:Field){if(field.type==='checkbox')return Boolean(v);if(field.type==='roles')return Array.isArray(v)?v.join(', '):String(v??'');if(field.type==='date'&&v)return String(v).slice(0,10);if(field.type==='textarea'&&typeof v==='object')return JSON.stringify(v,null,2);return v??''}
function groupResources(){return resources.reduce<Record<string,Resource[]>>((acc,r)=>{(acc[r.group]??=[]).push(r);return acc},{});}

export function F2MasterDataPro({api,onToast}:{api:Api;onToast:(message:string)=>void}){
 const[resource,setResource]=React.useState(resources[0]);const[rows,setRows]=React.useState<Row[]>([]);const[selected,setSelected]=React.useState<Row|null>(null);const[form,setForm]=React.useState<Row>({active:true});const[query,setQuery]=React.useState('');const[loading,setLoading]=React.useState(false);const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState('');const[notice,setNotice]=React.useState('');const[tool,setTool]=React.useState<'none'|'search'|'integrity'|'io'|'audit'>('none');const[health,setHealth]=React.useState<any>(null);const[audit,setAudit]=React.useState<Row[]>([]);const[importEntity,setImportEntity]=React.useState(resources[0].key);const[importJson,setImportJson]=React.useState('[\n\n]');const[file,setFile]=React.useState<File|null>(null);
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{let data:any;if(resource.key==='addresses'){const parties=unwrap<Row[]>(await api('/api/v1/master-data/parties?limit=1000&offset=0'));const groups=await Promise.all(parties.map(async p=>{try{return unwrap<Row[]>(await api(`/api/v1/master-data/parties/${encodeURIComponent(idOf(p))}/addresses?limit=1000&offset=0`))}catch{return[]}}));data=groups.flat()}else if(resource.key==='prices'){const lists=unwrap<Row[]>(await api('/api/v1/master-data/price-lists?limit=1000&offset=0'));const groups=await Promise.all(lists.map(async p=>{try{return unwrap<Row[]>(await api(`/api/v1/master-data/price-lists/${encodeURIComponent(idOf(p))}/prices?limit=1000&offset=0`))}catch{return[]}}));data=groups.flat()}else data=unwrap<Row[]>(await api(`${resource.path}?limit=100&offset=0`));setRows(Array.isArray(data)?data:[])}catch(e){setRows([]);setError(e instanceof Error?e.message:'Não foi possível carregar o cadastro.')}finally{setLoading(false)}},[api,resource]);
 React.useEffect(()=>{setSelected(null);setForm({active:true});if(tool==='none')void load()},[load,tool]);
 function startNew(){setSelected(null);const next:Row={active:true};for(const f of resource.fields)if(f.type==='checkbox'&&next[f.key]===undefined)next[f.key]=true;setForm(next);setError('');setNotice('')}
 function edit(r:Row){setSelected(r);const next:Row={...r};delete next._id;next.id=idOf(r);for(const f of resource.fields)next[f.key]=inputValue(next[f.key],f);setForm(next);setError('');setNotice('');window.scrollTo({top:0,behavior:'smooth'})}
 function setField(key:string,value:any){setForm(v=>({...v,[key]:value}))}
 function buildPayload(){const p:Row={...form};delete p.id;delete p._id;for(const f of resource.fields){if(f.type==='roles')p[f.key]=String(p[f.key]??'').split(',').map(x=>x.trim()).filter(Boolean);if(f.type==='number'&&p[f.key]!=='')p[f.key]=Number(p[f.key]);if(f.type==='textarea'&&(f.key==='metadata')&&typeof p[f.key]==='string'&&p[f.key].trim())try{p[f.key]=JSON.parse(p[f.key])}catch{throw new Error(`${f.label} precisa conter JSON válido.`)}}return p}
 async function save(){setBusy(true);setError('');setNotice('');try{const payload=buildPayload();for(const f of resource.fields)if(f.required&&(payload[f.key]==null||payload[f.key]===''||(Array.isArray(payload[f.key])&&!payload[f.key].length)))throw new Error(`${f.label} é obrigatório.`);let endpoint=resource.path;let method=selected?'PATCH':'POST';if(resource.key==='addresses'){if(selected){endpoint=`/api/v1/master-data/addresses/${encodeURIComponent(idOf(selected))}`}else{const partyId=String(payload.partyId??'');if(!partyId)throw new Error('Parceiro é obrigatório.');delete payload.partyId;endpoint=`/api/v1/master-data/parties/${encodeURIComponent(partyId)}/addresses`}}else if(resource.key==='prices'){if(selected){endpoint=`/api/v1/master-data/prices/${encodeURIComponent(idOf(selected))}`}else{const listId=String(payload.priceListId??'');if(!listId)throw new Error('Lista de preços é obrigatória.');delete payload.priceListId;endpoint=`/api/v1/master-data/price-lists/${encodeURIComponent(listId)}/prices`}}else if(resource.key==='attachments'){throw new Error('Anexos são enviados pelo controle de arquivos abaixo.')}await api(endpoint,{method,body:JSON.stringify(payload)});onToast(selected?'Registro atualizado com sucesso.':'Registro criado com sucesso.');setNotice(selected?'Alterações salvas.':'Registro criado.');setSelected(null);startNew();await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}
 async function remove(r:Row){const id=idOf(r);if(!id||!window.confirm(`Desativar ${display(r)}?`))return;setBusy(true);setError('');try{let endpoint=`${resource.path}/${encodeURIComponent(id)}`;if(resource.key==='addresses')endpoint=`/api/v1/master-data/addresses/${encodeURIComponent(id)}`;if(resource.key==='prices')endpoint=`/api/v1/master-data/prices/${encodeURIComponent(id)}`;await api(endpoint,{method:'DELETE'});onToast('Registro desativado.');if(selected&&idOf(selected)===id)startNew();await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível desativar.')}finally{setBusy(false)}}
 async function search(){if(query.trim().length<2){setError('Digite pelo menos 2 caracteres.');return}setLoading(true);setError('');try{const value=unwrap<any>(await api(`/api/v1/master-data/f2/search?q=${encodeURIComponent(query.trim())}`));const result=value?.results??{};const flat=Object.entries(result).flatMap(([type,items])=>(Array.isArray(items)?items:[]).map((x:any)=>({...x,searchType:type})));setRows(flat as Row[]);setNotice(`${flat.length} resultado(s) encontrado(s).`)}catch(e){setError(e instanceof Error?e.message:'Falha na busca.')}finally{setLoading(false)}}
 async function integrity(){setLoading(true);setError('');try{setHealth(await api('/api/v1/master-data/f2/integrity'));setTool('integrity')}catch(e){setError(e instanceof Error?e.message:'Falha na verificação.')}finally{setLoading(false)}}
 async function auditLoad(){setLoading(true);setError('');try{const v=unwrap<Row[]>(await api('/api/v1/core/audit?limit=100&offset=0'));setAudit(Array.isArray(v)?v:[]);setTool('audit')}catch(e){setError(e instanceof Error?e.message:'Falha na auditoria.')}finally{setLoading(false)}}
 async function exportEntity(){setBusy(true);setError('');try{const v=await api<any>(`/api/v1/master-data/f2/bulk/export/${importEntity}`);const blob=new Blob([JSON.stringify(unwrap(v),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`kz-erp-f2-${importEntity}.json`;a.click();URL.revokeObjectURL(url);onToast('Exportação concluída.')}catch(e){setError(e instanceof Error?e.message:'Falha na exportação.')}finally{setBusy(false)}}
 async function importBatch(){setBusy(true);setError('');try{const p=JSON.parse(importJson);if(!Array.isArray(p))throw new Error('A importação precisa ser um array JSON.');const v=unwrap<any>(await api(`/api/v1/master-data/f2/bulk/import/${importEntity}`,{method:'POST',body:JSON.stringify(p)}));onToast(`Importação concluída: ${v?.inserted??0} registros.`);await load()}catch(e){setError(e instanceof Error?e.message:'Falha na importação.')}finally{setBusy(false)}}
 async function upload(){if(!file||!selected)throw new Error('Selecione um registro e um arquivo.');setBusy(true);setError('');try{const entityType=resource.key==='locations'?'location':resource.key.replace(/s$/,'');await api('/api/v1/master-data/f2/attachments/upload',{method:'POST',headers:{'x-f2-entity-type':entityType,'x-f2-entity-id':idOf(selected),'x-f2-file-name':file.name,'x-f2-mime-type':file.type||'application/octet-stream'},body:file});onToast('Anexo enviado.');setFile(null)}catch(e){setError(e instanceof Error?e.message:'Falha no upload.')}finally{setBusy(false)}}
 const grouped=groupResources();const canEdit=resource.key!=='attachments';
 return <section className="f2-pro">
  <div className="f2-pro-head"><div><span className="eyebrow">F2 · DADOS MESTRES</span><h2>Cadastros</h2><p>Gestão estruturada dos dados mestres, com busca, governança, importação e integração à operação.</p></div><div className="f2-pro-head-actions"><button className="secondary" onClick={()=>void load()} disabled={loading||busy}>Atualizar</button><button className="primary" onClick={startNew} disabled={!canEdit||busy}>Novo registro</button></div></div>
  <div className="f2-pro-toolbar"><div className="f2-pro-search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="Buscar por nome, código, SKU ou parceiro…"/><button className="primary" onClick={()=>void search()} disabled={loading}>Buscar</button></div><button className={`f2-pro-tool ${tool==='integrity'?'active':''}`} onClick={()=>void integrity()}>Integridade</button><button className={`f2-pro-tool ${tool==='io'?'active':''}`} onClick={()=>setTool(tool==='io'?'none':'io')}>Importar / exportar</button><button className={`f2-pro-tool ${tool==='audit'?'active':''}`} onClick={()=>void auditLoad()}>Auditoria</button></div>
  {tool==='integrity'&&<div className="f2-pro-card"><div className="f2-pro-card-head"><div><small>GOVERNANÇA</small><h3>Integridade dos dados</h3><p>Verificação de referências, hierarquias e relacionamentos do tenant.</p></div></div><div className="f2-pro-tool-panel"><pre>{JSON.stringify(health,null,2)}</pre></div></div>}
  {tool==='audit'&&<div className="f2-pro-card"><div className="f2-pro-card-head"><div><small>AUDITORIA</small><h3>Atividade administrativa</h3><p>Últimos 100 eventos disponíveis para o usuário autenticado.</p></div></div><div className="f2-pro-tool-panel"><pre>{JSON.stringify(audit,null,2)}</pre></div></div>}
  {tool==='io'&&<div className="f2-pro-card"><div className="f2-pro-card-head"><div><small>IO · F2</small><h3>Importação e exportação</h3><p>Transporte estruturado de dados mestres em JSON.</p></div></div><div className="f2-pro-io"><div><label>Entidade<select value={importEntity} onChange={e=>setImportEntity(e.target.value)}>{resources.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></label><button className="secondary" onClick={()=>void exportEntity()} disabled={busy}>Exportar JSON</button></div><div><label>Registros JSON<textarea value={importJson} onChange={e=>setImportJson(e.target.value)}/></label><button className="primary" onClick={()=>void importBatch()} disabled={busy}>Importar registros</button></div></div></div>}
  {error&&<div className="f2-pro-error">{error}</div>}{notice&&<div className="f2-pro-success">{notice}</div>}
  <div className="f2-pro-layout"><nav className="f2-pro-nav">{Object.entries(grouped).map(([group,list])=><React.Fragment key={group}><div className="f2-pro-nav-section">{group}</div>{list.map(r=><button key={r.key} className={resource.key===r.key?'active':''} onClick={()=>{setTool('none');setResource(r)}}>{r.label}</button>)}</React.Fragment>)}</nav>
   <div className="f2-pro-main"><div className="f2-pro-card"><div className="f2-pro-card-head"><div><small>{resource.core?'CORE':'F2'} · {resource.group.toUpperCase()}</small><h3>{resource.title}</h3><p>{rows.length} registro(s) carregado(s)</p></div><div className="f2-pro-card-actions"><button className="secondary" onClick={startNew} disabled={!canEdit}>Limpar formulário</button></div></div>
    {loading?<div className="f2-pro-loading">Carregando dados…</div>:rows.length?<div className="f2-pro-table"><table><thead><tr><th>Registro</th><th>Identificação</th><th>Status</th><th>Resumo</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={`${resource.key}-${idOf(r)}`}><td><span className="f2-pro-primary">{display(r)}</span>{r.description&&<span className="f2-pro-secondary">{String(r.description).slice(0,80)}</span>}</td><td><span className="f2-pro-id">{idOf(r).slice(0,16)}</span>{r.code&&<span className="f2-pro-secondary">Código {r.code}</span>}</td><td><span className={`f2-pro-status ${r.active===false?'inactive':'active'}`}><i/>{r.active===false?'Inativo':'Ativo'}</span></td><td>{formatValue(r.kind??r.type??r.relation??r.symbol??r.email)}</td><td><div className="f2-pro-actions">{canEdit&&<button onClick={()=>edit(r)}>Editar</button>}<button className="danger" onClick={()=>void remove(r)} disabled={busy}>Desativar</button></div></td></tr>)}</tbody></table></div>:<div className="f2-pro-empty"><strong>Nenhum registro encontrado</strong>Crie o primeiro registro ou ajuste os filtros de pesquisa.</div>}
   </div>
   {canEdit&&<div className="f2-pro-card"><div className="f2-pro-card-head"><div><small>{selected?'EDIÇÃO':'CRIAÇÃO'} · FORMULÁRIO</small><h3>{selected?`Editar ${resource.title}`:`Novo ${resource.title}`}</h3><p>Campos estruturados e validação antes do envio à API.</p></div></div><div className="f2-pro-form"><div className="f2-pro-form-grid">{resource.fields.map(f=><div key={f.key} className={`f2-pro-field ${f.full?'full':''}`}>{f.type==='checkbox'?<label className="f2-pro-check"><input type="checkbox" checked={Boolean(form[f.key])} onChange={e=>setField(f.key,e.target.checked)}/><span>{f.label}</span></label>:<><label htmlFor={`f2-${f.key}`}>{f.label}{f.required&&<span>*</span>}</label>{f.type==='textarea'?<textarea id={`f2-${f.key}`} value={String(form[f.key]??'')} onChange={e=>setField(f.key,e.target.value)} placeholder={f.placeholder}/>:f.type==='select'?<select id={`f2-${f.key}`} value={String(form[f.key]??'')} onChange={e=>setField(f.key,e.target.value)}><option value="">Selecione…</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input id={`f2-${f.key}`} type={f.type==='number'?'number':f.type==='date'?'date':f.type==='email'?'email':'text'} value={String(form[f.key]??'')} onChange={e=>setField(f.key,e.target.value)} placeholder={f.type==='roles'?'customer, supplier':f.placeholder}/>}</>}</div>)}</div>{resource.key==='relationships'&&<div className="f2-pro-hint">Use os tipos de entidade aceitos pelo F2 e IDs pertencentes ao mesmo tenant. Relações disponíveis: {relationTypes.join(' · ')}.</div>}{resource.key==='locations'&&<div className="f2-pro-hint">A hierarquia segue Zone → Aisle → Rack → Shelf → Bin. A localização pai deve pertencer ao mesmo armazém.</div>}<div className="f2-pro-form-actions"><button className="secondary" onClick={startNew} disabled={busy}>Cancelar</button><button className="primary" onClick={()=>void save()} disabled={busy}>{busy?'Salvando…':selected?'Salvar alterações':'Criar registro'}</button></div></div></div>}
   {selected&&<div className="f2-pro-card"><div className="f2-pro-card-head"><div><small>DOCUMENTOS</small><h3>Anexos do registro</h3><p>Arquivos armazenados no fluxo de anexos da F2.</p></div></div><div className="f2-pro-side"><div className="f2-pro-file"><input type="file" onChange={e=>setFile(e.target.files?.[0]??null)} disabled={busy}/><button className="primary" onClick={()=>void upload()} disabled={busy||!file} style={{marginTop:9}}>Enviar arquivo</button></div></div></div>}
  </div></div>
 </section>;
}
