import React from 'react';
import './LogisticsPage.css';

type Session = { accessToken: string; refreshToken?: string };
type Shipment = { id:string; number:string; status:'draft'|'ready'|'in_transit'|'delivered'|'cancelled'; carrier?:string; trackingCode?:string; warehouseId:string; customerId?:string; destination:{name:string;city:string;state:string;address:string;postalCode:string}; lines:{productId:string;description?:string;quantity:string}[]; createdAt:string; updatedAt:string };
type Props = { session: Session; onToast:(message:string)=>void; onSession:(session:Session)=>void };
const API=(import.meta.env.VITE_API_URL??'https://kz-erp.onrender.com').replace(/\/$/,'');
const labels:Record<Shipment['status'],string>={draft:'Rascunho',ready:'Pronto',in_transit:'Em trânsito',delivered:'Entregue',cancelled:'Cancelado'};
const next:Record<string,Array<{action:'ready'|'dispatch'|'deliver'|'cancel';label:string}>>={draft:[{action:'ready',label:'Preparar'},{action:'cancel',label:'Cancelar'}],ready:[{action:'dispatch',label:'Despachar'},{action:'cancel',label:'Cancelar'}],in_transit:[{action:'deliver',label:'Entregar'},{action:'cancel',label:'Cancelar'}],delivered:[],cancelled:[]};
async function call<T>(path:string,session:Session,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);headers.set('Accept','application/json');if(options.body!==undefined)headers.set('Content-Type','application/json');headers.set('Authorization',`Bearer ${session.accessToken}`);const response=await fetch(`${API}${path}`,{...options,headers});const body=await response.json().catch(()=>null) as {data?:T;error?:{message?:string;code?:string}};if(response.status===401)throw new Error('Sessão expirada. Atualize a sessão no menu Configurações.');if(!response.ok)throw new Error(body.error?.message??body.error?.code??`HTTP ${response.status}`);return (body.data??body) as T;}
export function LogisticsPage({session,onToast}:Props){const [items,setItems]=React.useState<Shipment[]>([]);const [status,setStatus]=React.useState('');const [loading,setLoading]=React.useState(true);const [error,setError]=React.useState('');const [busy,setBusy]=React.useState<string|null>(null);const [selected,setSelected]=React.useState<Shipment|null>(null);
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const query=status?`&status=${encodeURIComponent(status)}`:'';const data=await call<{items:Shipment[]}>('/api/v1/logistics/shipments?limit=50&offset=0'+query,session);setItems(data.items)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar expedições.')}finally{setLoading(false)}},[session,status]);
 React.useEffect(()=>{void load()},[load]);
 async function transition(id:string,action:string){setBusy(id);try{const data=await call<{shipment:Shipment}>(`/api/v1/logistics/shipments/${id}/${action}`,session,{method:'POST',body:JSON.stringify({})});setItems(current=>current.map(x=>x.id===id?data.shipment:x));if(selected?.id===id)setSelected(data.shipment);onToast(`Expedição atualizada: ${labels[data.shipment.status]}.`)}catch(e){onToast(e instanceof Error?e.message:'Não foi possível atualizar a expedição.')}finally{setBusy(null)}}
 return <section className="module-page logistics-page"><div className="module-intro"><span className="tag">F7 • LOGÍSTICA</span><div className="logistics-heading"><div><h2>Expedições</h2><p>Controle de transporte sincronizado com a API real do KORCZAK ERP.</p></div><button className="secondary" onClick={()=>void load()} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div></div><div className="logistics-toolbar"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os estados</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><span>{items.length} expedição(ões)</span></div>{loading?<div className="panel state-card">Carregando expedições…</div>:error?<div className="panel state-card error-state"><strong>Não foi possível carregar</strong><span>{error}</span><button className="secondary" onClick={()=>void load()}>Tentar novamente</button></div>:items.length===0?<div className="panel state-card"><strong>Nenhuma expedição encontrada</strong><span>Quando uma expedição for criada pela API, ela aparecerá aqui.</span></div>:<div className="logistics-list">{items.map(item=><article className="panel shipment-card" key={item.id} onClick={()=>setSelected(item)}><div><span className={`status status-${item.status}`}>{labels[item.status]}</span><h3>{item.number}</h3><p>{item.destination.name} · {item.destination.city}/{item.destination.state}</p></div><div className="shipment-meta"><span>{item.lines.length} linha(s)</span><span>{item.carrier??'Transportadora não definida'}</span>{item.trackingCode&&<span>Rastreio: {item.trackingCode}</span>}</div><div className="shipment-actions">{next[item.status].map(action=><button key={action.action} className={action.action==='cancel'?'danger':'secondary'} disabled={busy===item.id} onClick={e=>{e.stopPropagation();void transition(item.id,action.action)}}>{busy===item.id?'…':action.label}</button>)}</div></article>)}</div>}{selected&&<div className="panel shipment-detail"><div className="detail-header"><div><small>EXPEDIÇÃO</small><h3>{selected.number}</h3></div><button className="secondary" onClick={()=>setSelected(null)}>Fechar</button></div><dl><dt>Estado</dt><dd>{labels[selected.status]}</dd><dt>Destino</dt><dd>{selected.destination.address}, {selected.destination.city}/{selected.destination.state} — {selected.destination.postalCode}</dd><dt>Transportadora</dt><dd>{selected.carrier??'—'}</dd><dt>Rastreio</dt><dd>{selected.trackingCode??'—'}</dd></dl><div className="detail-lines"><strong>Itens</strong>{selected.lines.map(line=><div key={line.productId}><span>{line.description??line.productId}</span><span>{line.quantity}</span></div>)}</div></div>}</section>}
