import React from 'react';
import { createRoot } from 'react-dom/client';
import { getCurrentWindow } from '@tauri-apps/api/window';
import './styles.css';
import { checkForUpdate } from './updater';
import { F2MasterData } from './F2MasterData';
import { StockPage } from './StockPage';
import { SalesPage } from './SalesPage';

type View = 'overview' | 'cadastros' | 'operacoes' | 'vendas' | 'financeiro' | 'fiscal' | 'relatorios' | 'configuracoes';
type Session = { accessToken: string; refreshToken: string; expiresIn?: number; user?: { id?: string; name?: string; email?: string; role?: string }; companyId?: string };
type ApiError = { error?: { code?: string; message?: string; details?: unknown }; requestId?: string };
type SystemInfo = { name: string; version: string; integrationNamespaces: string[] };
type Company = { name: string; slug: string; active?: boolean };
type Me = { user: { id: string; email: string; name: string; role: string }; companyId: string };
const API = (import.meta.env.VITE_API_URL ?? 'https://kz-erp.onrender.com').replace(/\/$/, '');
const APP_VERSION = import.meta.env.VITE_APP_VERSION ?? '0.1.3';
const nav: { id: View; label: string; icon: string; implemented: boolean }[] = [
  { id: 'overview', label: 'Visão geral', icon: '⌂', implemented: true },
  { id: 'cadastros', label: 'Cadastros', icon: '▦', implemented: true },
  { id: 'operacoes', label: 'Estoque', icon: '⇄', implemented: true },
  { id: 'vendas', label: 'Vendas', icon: '◇', implemented: true },
  { id: 'financeiro', label: 'Financeiro', icon: '◈', implemented: false },
  { id: 'fiscal', label: 'Fiscal', icon: '◇', implemented: false },
  { id: 'relatorios', label: 'Relatórios', icon: '▤', implemented: false },
  { id: 'configuracoes', label: 'Configurações', icon: '⚙', implemented: true }
];
function readSession(): Session | null { try { const raw = localStorage.getItem('kz-erp-session'); return raw ? JSON.parse(raw) as Session : null; } catch { return null; } }
function saveSession(session: Session) { localStorage.setItem('kz-erp-session', JSON.stringify(session)); }
function clearSession() { localStorage.removeItem('kz-erp-session'); }
async function requestRaw(path: string, options: RequestInit = {}, token?: string): Promise<Response> { const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), 12000); try { const headers = new Headers(options.headers); if (options.body !== undefined) headers.set('Content-Type', 'application/json'); headers.set('Accept', 'application/json'); if (token) headers.set('Authorization', `Bearer ${token}`); return await fetch(`${API}${path}`, { ...options, headers, signal: controller.signal }); } finally { window.clearTimeout(timer); } }
async function parseResponse<T>(response: Response): Promise<T> { const body = await response.json().catch(() => null) as { data?: T } & ApiError | null; if (!response.ok) throw new Error(body?.error?.message ?? body?.error?.code ?? `HTTP ${response.status}`); return (body?.data ?? body) as T; }
async function api<T>(path: string, options: RequestInit = {}, token?: string): Promise<T> { return parseResponse<T>(await requestRaw(path, options, token)); }
async function apiWithSession<T>(path: string, session: Session, options: RequestInit = {}, onRefresh?: (next: Session) => void): Promise<T> { let response = await requestRaw(path, options, session.accessToken); if (response.status !== 401 || !session.refreshToken) return parseResponse<T>(response); try { const refreshed = await api<{ accessToken: string; refreshToken: string; expiresIn: number }>('/api/v1/auth/refresh', { method: 'POST', body: JSON.stringify({ refreshToken: session.refreshToken }) }); const next = { ...session, ...refreshed }; saveSession(next); onRefresh?.(next); response = await requestRaw(path, options, next.accessToken); return parseResponse<T>(response); } catch { clearSession(); throw new Error('Sessão expirada. Entre novamente.'); } }
function WindowControls() { const win = getCurrentWindow(); return <div className="window-controls" data-tauri-drag-region><button aria-label="Minimizar" onClick={() => void win.minimize()}>−</button><button aria-label="Maximizar ou restaurar" onClick={() => void win.toggleMaximize()}>□</button><button className="close-window" aria-label="Fechar" onClick={() => void win.close()}>×</button></div>; }
function Titlebar({ status }: { status: string }) { const win = getCurrentWindow(); return <div className="titlebar" data-tauri-drag-region onDoubleClick={() => void win.toggleMaximize()}><div className="titlebar-brand"><span className="brand-mark mini">KZ</span><strong>KORCZAK ERP</strong><span className="titlebar-status">{status}</span></div><WindowControls /></div>; }
function App() {
  const [view, setView] = React.useState<View>('overview'); const [apiStatus, setApiStatus] = React.useState<'connecting'|'online'|'offline'>('connecting'); const [session, setSession] = React.useState<Session|null>(readSession); const [company, setCompany] = React.useState<Company|null>(null); const [me, setMe] = React.useState<Me|null>(null); const [system, setSystem] = React.useState<SystemInfo|null>(null); const [updateStatus, setUpdateStatus] = React.useState('Verificando atualizações…'); const [loginOpen, setLoginOpen] = React.useState(false); const [toast, setToast] = React.useState(''); const [healthError, setHealthError] = React.useState('');
  const checkConnection = React.useCallback(async () => { setApiStatus('connecting'); setHealthError(''); try { await api<{status:string}>('/health'); const info = await api<SystemInfo>('/api/v1/system'); setSystem(info); setApiStatus('online'); } catch(error) { setApiStatus('offline'); setHealthError(error instanceof Error ? error.message : 'Falha de conexão'); } }, []);
  React.useEffect(() => { void checkConnection(); void checkForUpdate(setUpdateStatus); }, [checkConnection]);
  const hydrateSession = React.useCallback(async(current:Session) => { try { const [identity, companyData] = await Promise.all([apiWithSession<Me>('/api/v1/core/me',current,{},setSession),apiWithSession<{company:Company}>('/api/v1/core/company',current,{},setSession)]); setMe(identity); setCompany(companyData.company); } catch(error) { clearSession(); setSession(null); setMe(null); setCompany(null); setToast(error instanceof Error ? error.message : 'Sessão inválida.'); } },[]);
  React.useEffect(() => { if(session) void hydrateSession(session); },[session,hydrateSession]);
  function logout(){const current=session;clearSession();setSession(null);setMe(null);setCompany(null);if(current?.refreshToken)void api('/api/v1/auth/logout',{method:'POST',body:JSON.stringify({refreshToken:current.refreshToken})}).catch(()=>undefined);setToast('Sessão encerrada.');}
  const title=nav.find(item=>item.id===view)?.label??'Visão geral'; const statusLabel=apiStatus==='online'?'API online':apiStatus==='connecting'?'Conectando…':'API offline';
  return <div className="app-root"><Titlebar status={statusLabel}/><div className="shell"><aside><div className="brand"><div className="brand-mark">KZ</div><div><strong>KORCZAK</strong><small>ERP</small></div></div><div className="workspace"><span className={`workspace-dot ${apiStatus==='online'?'online':''}`}/>{company?.name??(session?'Carregando empresa…':'Não autenticado')}</div><nav>{nav.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}><span>{item.icon}</span>{item.label}{!item.implemented&&<small className="nav-badge">PREPARADO</small>}</button>)}</nav><div className="side-status"><span className={`dot ${apiStatus==='online'?'online':''}`}/> API {statusLabel}<br/><small>{updateStatus}</small></div></aside><main><header><div><p className="eyebrow">KORCZAK TECHNOLOGIES / KORCZAK ERP</p><h1>{title}</h1></div><div className="header-actions"><div className="connection"><span className={`dot ${apiStatus==='online'?'online':''}`}/> {statusLabel}</div>{session?<button className="user-button" onClick={logout}>{me?.user.name??session.user?.email??'Conta'} <span>↪</span></button>:<button className="primary small" onClick={()=>setLoginOpen(true)}>Entrar</button>}</div></header>{apiStatus==='offline'&&<div className="banner-error"><strong>API indisponível</strong><span>{healthError||'Não foi possível conectar ao backend.'}</span><button onClick={()=>void checkConnection()}>Tentar novamente</button></div>}{view==='overview'&&<Dashboard apiStatus={apiStatus} session={session} company={company} system={system} onLogin={()=>setLoginOpen(true)} onNavigate={setView}/>} {view==='cadastros'&&(session?<F2MasterData session={session} onToast={setToast}/>:<AuthRequired onLogin={()=>setLoginOpen(true)}/>)}{view==='operacoes'&&(session?<StockPage session={session} onToast={setToast} onSession={setSession}/>:<AuthRequired onLogin={()=>setLoginOpen(true)}/>)}{view==='vendas'&&(session?<SalesPage session={session} onToast={setToast}/>:<AuthRequired onLogin={()=>setLoginOpen(true)}/>)} {view==='configuracoes'&&<SettingsPage session={session} me={me} company={company} system={system} updateStatus={updateStatus} onCheckUpdate={()=>void checkForUpdate(setUpdateStatus)} onRetryApi={()=>void checkConnection()} onRefresh={()=>session&&void hydrateSession(session)} onLogout={logout}/>} {(view==='financeiro'||view==='fiscal'||view==='relatorios')&&<PreparedModule title={title}/>}</main></div>{loginOpen&&<Login onClose={()=>setLoginOpen(false)} onSuccess={next=>{saveSession(next);setSession(next);setLoginOpen(false);setToast('Login realizado.');}}/>}{toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}</div>;
}
function detectPlatform(){if(typeof navigator==='undefined')return 'Linux';const ua=navigator.userAgent.toLowerCase();if(ua.includes('win'))return 'Windows';if(ua.includes('mac'))return 'macOS';if(ua.includes('linux'))return 'Linux';return 'Desktop';}
function SettingsPage({session,me,company,system,updateStatus,onCheckUpdate,onRetryApi,onRefresh,onLogout}:{session:Session|null;me:Me|null;company:Company|null;system:SystemInfo|null;updateStatus:string;onCheckUpdate:()=>void;onRetryApi:()=>void;onRefresh:()=>void;onLogout:()=>void}){const platform=detectPlatform();const namespaces=system?.integrationNamespaces??['CORE','WMS','TMS','CRM'];return <section className="module-page"><div className="module-intro"><span className="tag">SISTEMA</span><h2>Configurações</h2><p>Informações da sessão, do aplicativo e da plataforma obtidas dos serviços reais.</p></div>{session?<div className="settings-grid"><article className="panel software-info"><div className="software-logo" role="img" aria-label="Logo Korczak Technologies"/><div><small>APLICATIVO</small><h3>KORCZAK ERP</h3><p className="update-note">Sistema de gestão empresarial da Korczak Technologies, preparado para integrar-se ao ecossistema KOS por contratos e namespaces.</p><div className="software-meta"><div><small>VERSÃO</small><strong>v{APP_VERSION}</strong></div><div><small>PLATAFORMA</small><strong>{platform}</strong></div><div><small>AMBIENTE</small><strong>Desktop</strong></div><div><small>ECOSSISTEMA</small><strong>KOS</strong></div></div></div></article><article className="panel"><small>INTEGRAÇÃO</small><h3>Arquitetura KOS</h3><dl><dt>Produto</dt><dd>KORCZAK ERP</dd><dt>Ecossistema</dt><dd>KOS</dd><dt>Namespaces</dt><dd>{namespaces.join(' · ')}</dd><dt>API</dt><dd>{API}</dd></dl></article><article className="panel"><small>SESSÃO</small><h3>Usuário atual</h3><dl><dt>Nome</dt><dd>{me?.user.name??'—'}</dd><dt>E-mail</dt><dd>{me?.user.email??session.user?.email??'—'}</dd><dt>Role</dt><dd>{me?.user.role??'—'}</dd><dt>Empresa</dt><dd>{company?.name??'—'} ({company?.slug??'—'})</dd></dl><div className="panel-actions"><button className="secondary" onClick={onRefresh}>Atualizar</button><button className="danger" onClick={onLogout}>Sair</button></div></article><article className="panel"><small>API</small><h3>Conectividade</h3><dl><dt>Endereço</dt><dd>{API}</dd><dt>Status</dt><dd>{system?'Online':'Indisponível'}</dd><dt>Versão</dt><dd>{system?.version??'—'}</dd></dl><div className="panel-actions"><button className="secondary" onClick={onRetryApi}>Tentar atualizar API</button></div></article><article className="panel update-panel"><small>ATUALIZAÇÕES</small><h3>Aplicativo</h3><div className="update-status"><span className={`dot ${/Atualizado|instalando|reiniciando/i.test(updateStatus)?'online':''}`}/>{updateStatus}</div><p className="update-note">A atualização é verificada pela API de releases e instalada como pacote .deb no Linux. Durante a instalação, o aplicativo é reiniciado automaticamente quando a operação for concluída.</p><div className="panel-actions"><button className="primary" onClick={onCheckUpdate}>Verificar e atualizar</button></div></article></div>:<AuthRequired onLogin={()=>undefined}/>}</section>}
function Dashboard({apiStatus,session,company,system,onLogin,onNavigate}:{apiStatus:string;session:Session|null;company:Company|null;system:SystemInfo|null;onLogin:()=>void;onNavigate:(view:View)=>void}){return <><section className="hero"><div className="hero-copy"><span className="tag">ERP • LINUX DESKTOP</span><h2>Operação centralizada.<br/><em>Dados reais, estado real.</em></h2><p>O centro operacional da Korczak, conectado à API oficial, com isolamento por empresa e sem acesso direto do desktop ao MongoDB.</p><div className="hero-actions">{session?<button className="primary" onClick={()=>onNavigate('cadastros')}>Abrir operação <span>→</span></button>:<button className="primary" onClick={onLogin}>Acessar ERP <span>→</span></button>}<span className="secure">● API server-side · MongoDB protegido</span></div></div><div className="orb"><div>KZ</div><span>{apiStatus==='online'?'ONLINE':apiStatus.toUpperCase()}</span></div></section><section className="metrics"><Metric label="SISTEMA" value={apiStatus==='online'?'Operacional':apiStatus==='connecting'?'Conectando…':'Offline'} detail={system?`v${system.version}`:'Health check'} state={apiStatus==='online'}/><Metric label="EMPRESA" value={company?.name??(session?'Carregando…':'Não autenticado')} detail={company?.slug??'Sessão necessária'} state={!!company}/><Metric label="USUÁRIO" value={session?(session.user?.name??'Autenticado'):'Não autenticado'} detail={session?.user?.role??'Faça login'} state={!!session}/><Metric label="INTEGRAÇÕES" value={system?`${system.integrationNamespaces.length} namespaces`:'Não carregado'} detail="Contratos da API" state={!!system}/></section></>}
function Metric({label,value,detail,state}:{label:string;value:string;detail:string;state?:boolean}){return <article className="metric"><small>{label}</small><strong>{value}</strong><span><i className={`dot ${state?'online':''}`}/>{detail}</span></article>}
function PreparedModule({title}:{title:string}){return <section className="prepared"><div className="prepared-mark">—</div><span className="tag">MÓDULO PREPARADO</span><h2>{title}</h2><p>A API deste módulo ainda está em implementação. A navegação está disponível, mas nenhuma operação fictícia é apresentada.</p></section>}
function AuthRequired({onLogin}:{onLogin:()=>void}){return <section className="state-box auth-required"><strong>Autenticação necessária.</strong><p>Entre com uma conta válida para consultar e alterar dados reais.</p><button className="primary small" onClick={onLogin}>Entrar</button></section>}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="form-card" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><span className="eyebrow">KORCZAK ERP</span><h2>{title}</h2>{children}</div></div>}
function Login({onClose,onSuccess}:{onClose:()=>void;onSuccess:(session:Session)=>void}){const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');const[companySlug,setCompanySlug]=React.useState('');const[error,setError]=React.useState('');const[loading,setLoading]=React.useState(false);async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const data=await api<{accessToken:string;refreshToken:string;expiresIn:number}>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password,...(companySlug?{companySlug}: {})})});onSuccess({...data,user:{email}})}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.')}finally{setLoading(false)}}return <Modal title="Entrar no sistema" onClose={onClose}><div className="login-mark">KZ</div><p className="login-subtitle">Acesse sua empresa com autenticação real.</p><form onSubmit={submit}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoFocus/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Empresa <span>opcional</span><input value={companySlug} onChange={e=>setCompanySlug(e.target.value)} placeholder="minha-empresa"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary login-submit" disabled={loading}>{loading?'Entrando…':'Entrar'} <span>→</span></button></form></Modal>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
