import './F1Admin.css';
import { mount } from './DesktopApp';
import './KorczakDesignSystem.css';
import './KorczakModulePolish.css';
import './OverviewPremium.css';
import './F1Premium.css';
import './StockPremium.css';
import './SalesPremium.css';
import './FinancePremium.css';
import './PreparedPremium.css';
import './GlobalPremium.css';
mount();
